use std::time::Duration;

pub const LIVE_PUBLISH_MIN_INTERVAL_MS: u64 = 1_000;
pub const LIVE_PUBLISH_FAST_INTERVAL_MS: u64 = 200;
pub const LIVE_SCALAR_TELEMETRY_INTERVAL_MS: u64 = 200;
pub const LIVE_TABLE_ROWS_MIN_REFETCH_MS: u32 = 1_000;

pub const LIVE_REALTIME_REPLAY_CAPACITY: usize = 512;
pub const LIVE_REALTIME_HEARTBEAT_SECS: u64 = 15;
pub const LIVE_REALTIME_COALESCE_WINDOW_MS: u32 = 250;
pub const LIVE_REALTIME_FIELD_SAMPLE_COALESCE_WINDOW_MS: u32 = 2_000;
pub const LIVE_REALTIME_DIAGNOSTICS_SUMMARY_WINDOW_MS: u32 = 5_000;
pub const LIVE_REALTIME_RECONNECT_MS: u32 = 5_000;
pub const LIVE_STATUS_REFRESH_MS: u32 = 5_000;
pub const LIVE_ERROR_RETRY_MS: u32 = 1_000;

pub const LIVE_PUBLISH_MIN_INTERVAL: Duration = Duration::from_millis(LIVE_PUBLISH_MIN_INTERVAL_MS);
pub const LIVE_PUBLISH_FAST_INTERVAL: Duration =
    Duration::from_millis(LIVE_PUBLISH_FAST_INTERVAL_MS);
pub const LIVE_SCALAR_TELEMETRY_INTERVAL: Duration =
    Duration::from_millis(LIVE_SCALAR_TELEMETRY_INTERVAL_MS);
