[package]
name = "fullmag-api"
version.workspace = true
edition.workspace = true
publish.workspace = true

[features]
default = []
cuda = ["fullmag-runner/cuda"]
fem-gpu = ["fullmag-runner/fem-gpu"]
stage-autosave-hdf5 = ["fullmag-runner/stage-autosave-hdf5"]
swagger-ui = ["dep:utoipa-swagger-ui"]

[dependencies]
anyhow.workspace = true
async-stream = "0.3"
axum.workspace = true
base64 = "0.22"
chrono = { version = "0.4", features = ["serde"] }
futures-core = "0.3"
serde.workspace = true
serde_json.workspace = true
sha2 = "0.10"
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
tower-http = { version = "0.6", features = ["cors", "fs"] }
fullmag-authoring = { path = "../fullmag-authoring" }
fullmag-ir = { path = "../fullmag-ir" }
fullmag-plan = { path = "../fullmag-plan" }
fullmag-quantities = { path = "../fullmag-quantities" }
fullmag-runner = { path = "../fullmag-runner" }
fullmag-session = { path = "../fullmag-session" }
png = "0.17"
tiny-skia = "0.11"
fontdue = "0.9"
utoipa = { version = "5", features = ["axum_extras", "chrono"] }
utoipa-swagger-ui = { version = "8", features = ["axum"], optional = true }
uuid = { version = "1", features = ["v4"] }

[dev-dependencies]
tower = { version = "0.5", features = ["util"] }
