"""Geometry asset, meshing, and voxelization helpers for backend lowering."""

from ._mesh_targets import (
    ResolvedAirboxTarget,
    ResolvedObjectPreviewTarget,
    ResolvedSharedDomainTargets,
    ResolvedSharedObjectTarget,
    SharedDomainBuildReport,
    resolve_object_preview_target,
    resolve_shared_domain_targets,
)
from .asset_pipeline import (
    realize_fdm_grid_asset,
    realize_fem_domain_mesh_asset,
    realize_fem_domain_mesh_asset_from_components,
    realize_fem_mesh_asset,
)
from .gmsh_bridge import (
    MESH_SIZE_CALIBRATIONS,
    MESH_SIZE_PRESETS,
    AirboxOptions,
    ComponentDescriptor,
    MeshData,
    MeshOptions,
    MeshQualityReport,
    MeshStatisticsReport,
    MeshStatisticsScope,
    SharedDomainMeshResult,
    SizeFieldData,
    add_air_box,
    extract_per_domain_quality,
    generate_box_mesh,
    generate_cylinder_mesh,
    generate_difference_mesh,
    generate_mesh,
    generate_mesh_from_file,
    generate_shared_domain_mesh_from_components,
    remesh_with_size_field,
    resolve_mesh_size_controls,
)
from .quality import MeshValidationReport, validate_mesh
from .periodic import PeriodicBoundaryPair, periodic_x, periodic_y, periodic_z
from .surface_assets import SurfaceAsset, export_geometry_to_stl, load_surface_asset
from .voxelization import VoxelMaskData, voxelize_geometry
from .mesh_controls import (
    boundary_layers,
    edge_distance_threshold,
    interface_shell,
    nearest_curve_to_point,
    nearest_surface_to_point,
    object_core_relaxation,
    surface_shell,
)

__all__ = [
    "MESH_SIZE_CALIBRATIONS",
    "MESH_SIZE_PRESETS",
    "AirboxOptions",
    "ComponentDescriptor",
    "MeshData",
    "MeshOptions",
    "PeriodicBoundaryPair",
    "MeshQualityReport",
    "MeshStatisticsReport",
    "MeshStatisticsScope",
    "MeshValidationReport",
    "SharedDomainMeshResult",
    "SizeFieldData",
    "SurfaceAsset",
    "VoxelMaskData",
    "add_air_box",
    "boundary_layers",
    "edge_distance_threshold",
    "export_geometry_to_stl",
    "extract_per_domain_quality",
    "generate_box_mesh",
    "generate_cylinder_mesh",
    "generate_difference_mesh",
    "generate_mesh",
    "generate_mesh_from_file",
    "generate_shared_domain_mesh_from_components",
    "interface_shell",
    "load_surface_asset",
    "nearest_curve_to_point",
    "nearest_surface_to_point",
    "object_core_relaxation",
    "periodic_x",
    "periodic_y",
    "periodic_z",
    "ResolvedAirboxTarget",
    "ResolvedObjectPreviewTarget",
    "ResolvedSharedDomainTargets",
    "ResolvedSharedObjectTarget",
    "SharedDomainBuildReport",
    "resolve_object_preview_target",
    "resolve_shared_domain_targets",
    "realize_fdm_grid_asset",
    "realize_fem_domain_mesh_asset",
    "realize_fem_domain_mesh_asset_from_components",
    "realize_fem_mesh_asset",
    "remesh_with_size_field",
    "resolve_mesh_size_controls",
    "surface_shell",
    "validate_mesh",
    "voxelize_geometry",
]
