"use client";

import { useState, Suspense, lazy } from "react";
import { useSimulation } from "../../lib/useSimulation";
import type { StepStats } from "../../lib/useSimulation";

const MagnetizationView3D = lazy(
  () => import("../../components/preview/MagnetizationView3D")
);
const ScalarPlot = lazy(() => import("../../components/plots/ScalarPlot"));

type Tab = "3d" | "scalars" | "metadata";
type ScalarField = "e_ex" | "max_dm_dt" | "max_h_eff";

export default function RunsPage() {
  const sim = useSimulation();
  const [tab, setTab] = useState<Tab>("3d");
  const [scalarField, setScalarField] = useState<ScalarField>("e_ex");
  const [irJson, setIrJson] = useState("");
  const [until, setUntil] = useState("2e-9");

  const lastStep = sim.steps[sim.steps.length - 1] as StepStats | undefined;

  const handleLaunch = () => {
    try {
      const problem = JSON.parse(irJson);
      sim.startRun(problem, parseFloat(until));
    } catch {
      alert("Invalid ProblemIR JSON");
    }
  };

  const handleDemo = () => {
    // Fetch the example IR from API
    fetch(
      `${process.env.NEXT_PUBLIC_API_URL || "http://localhost:8080"}/v1/meta/vision`
    ).then(() => {
      // Use bootstrap_example IR generated by `fullmag example-ir`
      fetch(`${process.env.NEXT_PUBLIC_API_URL || "http://localhost:8080"}/v1/run`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ until_seconds: parseFloat(until) }),
      });
    });
  };

  return (
    <>
      <div className="page-header">
        <h1 className="page-title">Live Simulation</h1>
        <p className="page-subtitle">
          Launch a simulation and watch it evolve in real-time
        </p>
      </div>

      {/* Launch panel */}
      <div className="card" style={{ marginBottom: "var(--sp-6)" }}>
        <div className="card-header">
          <div>
            <h2 className="card-title">Launch Run</h2>
            <p className="card-subtitle">
              Paste ProblemIR JSON and set simulation time
            </p>
          </div>
          <span
            className={`badge badge-${
              sim.status === "running"
                ? "success"
                : sim.status === "completed"
                ? "info"
                : sim.status === "error"
                ? "error"
                : "default"
            }`}
          >
            <span className="badge-dot" />
            {sim.status}
          </span>
        </div>
        <div className="card-body">
          <div style={{ display: "flex", gap: "var(--sp-4)", alignItems: "end" }}>
            <div style={{ flex: 1 }}>
              <label
                style={{
                  fontSize: "var(--text-sm)",
                  color: "var(--text-muted)",
                  display: "block",
                  marginBottom: "var(--sp-1)",
                }}
              >
                ProblemIR JSON
              </label>
              <textarea
                value={irJson}
                onChange={(e) => setIrJson(e.target.value)}
                placeholder='Paste output of: fullmag example-ir'
                rows={4}
                style={{
                  width: "100%",
                  fontFamily: "var(--font-mono)",
                  fontSize: "var(--text-sm)",
                  background: "var(--bg-raised)",
                  color: "var(--text-primary)",
                  border: "1px solid var(--border)",
                  borderRadius: "var(--radius-md)",
                  padding: "var(--sp-3)",
                  resize: "vertical",
                }}
              />
            </div>
            <div>
              <label
                style={{
                  fontSize: "var(--text-sm)",
                  color: "var(--text-muted)",
                  display: "block",
                  marginBottom: "var(--sp-1)",
                }}
              >
                Until (s)
              </label>
              <input
                type="text"
                value={until}
                onChange={(e) => setUntil(e.target.value)}
                style={{
                  width: "120px",
                  fontFamily: "var(--font-mono)",
                  fontSize: "var(--text-sm)",
                  background: "var(--bg-raised)",
                  color: "var(--text-primary)",
                  border: "1px solid var(--border)",
                  borderRadius: "var(--radius-md)",
                  padding: "var(--sp-2) var(--sp-3)",
                }}
              />
            </div>
            <button
              onClick={handleLaunch}
              disabled={sim.status === "running" || !irJson.trim()}
              style={{
                padding: "var(--sp-2) var(--sp-6)",
                background: "var(--accent)",
                color: "#fff",
                border: "none",
                borderRadius: "var(--radius-md)",
                cursor:
                  sim.status === "running" ? "not-allowed" : "pointer",
                fontSize: "var(--text-sm)",
                fontWeight: 600,
                opacity: sim.status === "running" ? 0.5 : 1,
              }}
            >
              {sim.status === "running" ? "Running…" : "Launch"}
            </button>
          </div>
        </div>
      </div>

      {/* Live metrics */}
      {lastStep && (
        <div className="metric-grid" style={{ marginBottom: "var(--sp-6)" }}>
          <MetricCard label="Step" value={lastStep.step.toString()} />
          <MetricCard
            label="Time"
            value={lastStep.time.toExponential(2)}
            unit="s"
          />
          <MetricCard
            label="E_ex"
            value={lastStep.e_ex.toExponential(3)}
            unit="J"
            accent="info"
          />
          <MetricCard
            label="max |dm/dt|"
            value={lastStep.max_dm_dt.toExponential(2)}
            accent="warning"
          />
        </div>
      )}

      {/* Tab bar */}
      {sim.steps.length > 0 && (
        <div className="card">
          <div
            className="card-header"
            style={{ borderBottom: "1px solid var(--border)" }}
          >
            <div
              style={{
                display: "flex",
                gap: "var(--sp-1)",
              }}
            >
              {(["3d", "scalars", "metadata"] as Tab[]).map((t) => (
                <button
                  key={t}
                  onClick={() => setTab(t)}
                  style={{
                    padding: "var(--sp-2) var(--sp-4)",
                    background: tab === t ? "var(--bg-raised)" : "transparent",
                    color:
                      tab === t ? "var(--text-primary)" : "var(--text-muted)",
                    border: "none",
                    borderRadius: "var(--radius-md)",
                    cursor: "pointer",
                    fontSize: "var(--text-sm)",
                    fontWeight: tab === t ? 600 : 400,
                    textTransform: "capitalize",
                  }}
                >
                  {t === "3d" ? "3D Preview" : t === "scalars" ? "Scalars" : "Metadata"}
                </button>
              ))}
            </div>

            {tab === "scalars" && (
              <select
                value={scalarField}
                onChange={(e) =>
                  setScalarField(e.target.value as ScalarField)
                }
                style={{
                  background: "var(--bg-raised)",
                  color: "var(--text-primary)",
                  border: "1px solid var(--border)",
                  borderRadius: "var(--radius-md)",
                  padding: "var(--sp-1) var(--sp-3)",
                  fontSize: "var(--text-sm)",
                }}
              >
                <option value="e_ex">E_ex</option>
                <option value="max_dm_dt">max |dm/dt|</option>
                <option value="max_h_eff">max |H_eff|</option>
              </select>
            )}
          </div>
          <div className="card-body" style={{ padding: 0 }}>
            <Suspense
              fallback={
                <div
                  style={{
                    padding: "var(--sp-12)",
                    textAlign: "center",
                    color: "var(--text-muted)",
                  }}
                >
                  Loading…
                </div>
              }
            >
              {tab === "3d" && (
                <MagnetizationView3D
                  grid={sim.grid}
                  magnetization={sim.magnetization}
                />
              )}
              {tab === "scalars" && (
                <div style={{ padding: "var(--sp-4)" }}>
                  <ScalarPlot steps={sim.steps} yField={scalarField} />
                </div>
              )}
              {tab === "metadata" && (
                <pre
                  style={{
                    padding: "var(--sp-4)",
                    fontFamily: "var(--font-mono)",
                    fontSize: "var(--text-sm)",
                    color: "var(--text-secondary)",
                    maxHeight: "400px",
                    overflow: "auto",
                    lineHeight: 1.5,
                  }}
                >
                  {JSON.stringify(
                    {
                      status: sim.status,
                      grid: sim.grid,
                      totalSteps: sim.steps.length,
                      lastStep,
                    },
                    null,
                    2
                  )}
                </pre>
              )}
            </Suspense>
          </div>
        </div>
      )}
    </>
  );
}

function MetricCard({
  label,
  value,
  unit,
  accent,
}: {
  label: string;
  value: string;
  unit?: string;
  accent?: "success" | "error" | "warning" | "info";
}) {
  const accentColor = accent ? `var(--${accent})` : "var(--text-primary)";

  return (
    <div className="card metric-card">
      <div className="metric-label">{label}</div>
      <div className="metric-value" style={{ color: accentColor }}>
        {value}
        {unit && <span className="metric-unit"> {unit}</span>}
      </div>
    </div>
  );
}
