#include "frequency_domain/linearized_dynamic_pencil.hpp"
#include "frequency_domain/canonical_digest.hpp"

#include <cmath>

namespace fullmag::fem::frequency_domain {
namespace {
bool valid(const LinearizedDynamicPencil &p, const std::vector<std::complex<double>> &in, std::vector<std::complex<double>> *out) { return out != nullptr && in.size() == p.dimension(); }
std::complex<double> phase_i(FrequencyDomainPhaseConvention phase) { return phase == FrequencyDomainPhaseConvention::exp_i_omega_t ? std::complex<double>{0.0, 1.0} : std::complex<double>{0.0, -1.0}; }
void apply_dense(const std::vector<std::complex<double>> &m, std::uint64_t n, const std::vector<std::complex<double>> &in, std::vector<std::complex<double>> *out, bool adjoint) { out->assign(n, {}); for (std::uint64_t r=0;r<n;++r) for (std::uint64_t c=0;c<n;++c) { const auto value=adjoint ? std::conj(m[c*n+r]) : m[r*n+c]; (*out)[r]+=value*in[c]; } }
void add_complex_matrix(CanonicalDigestBuilder *digest, std::string_view name, const std::vector<std::complex<double>> &matrix) { for (std::size_t index=0; index<matrix.size(); ++index) { const std::string prefix=std::string(name)+"["+std::to_string(index)+"]"; digest->add_double(prefix+".real", matrix[index].real()); digest->add_double(prefix+".imag", matrix[index].imag()); } }
std::string semantic_digest(const DynamicPencilMetadata &metadata, std::uint64_t dimension, const std::string &dependency_digest) { CanonicalDigestBuilder digest("linearized_dynamic_pencil.identity.v1"); digest.add_u64("dimension",dimension); digest.add_double("gamma0_m_per_a_s",metadata.gamma0_m_per_a_s); digest.add_u64("phase_convention",static_cast<std::uint64_t>(metadata.phase_convention)); digest.add_string("dependency_digest",dependency_digest); return digest.sha256_hex(); }
} // namespace
LinearizedDynamicPencil LinearizedDynamicPencil::from_dense_row_major(const DynamicPencilMetadata &metadata, std::uint64_t dimension, std::vector<std::complex<double>> l, std::vector<std::complex<double>> b_alpha, std::string dependency_digest) { LinearizedDynamicPencil result; result.metadata_=metadata; result.dimension_=dimension; result.l_=std::move(l); result.b_alpha_=std::move(b_alpha); result.dependency_digest_=std::move(dependency_digest); result.digest_=semantic_digest(metadata,dimension,result.dependency_digest_); CanonicalDigestBuilder representation("linearized_dynamic_pencil.representation.v1"); representation.add_string("semantic_digest",result.digest_); representation.add_string("kind","dense_row_major"); add_complex_matrix(&representation,"L",result.l_); add_complex_matrix(&representation,"B_alpha",result.b_alpha_); result.representation_digest_=representation.sha256_hex(); return result; }
LinearizedDynamicPencil LinearizedDynamicPencil::from_real_callbacks(const DynamicPencilMetadata &metadata, std::uint64_t dimension, LinearizedDynamicPencilRealCallbacks callbacks, std::string dependency_digest, std::string operator_source) { LinearizedDynamicPencil result; result.metadata_=metadata; result.dimension_=dimension; result.real_callbacks_=callbacks; result.has_real_callbacks_=callbacks.apply_l_and_b_alpha != nullptr || (callbacks.apply_l != nullptr && callbacks.apply_b_alpha != nullptr); result.dependency_digest_=std::move(dependency_digest); result.digest_=semantic_digest(metadata,dimension,result.dependency_digest_); CanonicalDigestBuilder representation("linearized_dynamic_pencil.representation.v1"); representation.add_string("semantic_digest",result.digest_); representation.add_string("kind","real_callbacks"); representation.add_string("operator_source",operator_source); result.representation_digest_=representation.sha256_hex(); return result; }
FrequencyDomainStatus LinearizedDynamicPencil::apply_L(const std::vector<std::complex<double>> &in, std::vector<std::complex<double>> *out) const noexcept { if(!valid(*this,in,out)) return FrequencyDomainStatus::validation_error; if (l_.size()==dimension_*dimension_) { apply_dense(l_,dimension_,in,out,false); return FrequencyDomainStatus::ok; } if (!has_real_callbacks_) return FrequencyDomainStatus::unavailable; std::vector<double> in_real(dimension_),in_imag(dimension_),out_real(dimension_),out_imag(dimension_),unused(dimension_); for(std::uint64_t i=0;i<dimension_;++i){in_real[i]=in[i].real();in_imag[i]=in[i].imag();} char error_message[128]{}; const auto apply = [&](const double *input,double *output) { if (real_callbacks_.apply_l != nullptr) return real_callbacks_.apply_l(real_callbacks_.context,input,output,error_message); if (real_callbacks_.apply_l_and_b_alpha != nullptr) return real_callbacks_.apply_l_and_b_alpha(real_callbacks_.context,input,output,unused.data(),error_message); return FrequencyDomainStatus::unavailable; }; const auto status_real=apply(in_real.data(),out_real.data()); if(status_real!=FrequencyDomainStatus::ok) return status_real; const auto status_imag=apply(in_imag.data(),out_imag.data()); if(status_imag!=FrequencyDomainStatus::ok) return status_imag; out->resize(dimension_); for(std::uint64_t i=0;i<dimension_;++i)(*out)[i]={out_real[i],out_imag[i]}; return FrequencyDomainStatus::ok; }
FrequencyDomainStatus LinearizedDynamicPencil::apply_B_alpha(const std::vector<std::complex<double>> &in, std::vector<std::complex<double>> *out) const noexcept { if(!valid(*this,in,out)) return FrequencyDomainStatus::validation_error; if (b_alpha_.size()==dimension_*dimension_) { apply_dense(b_alpha_,dimension_,in,out,false); return FrequencyDomainStatus::ok; } if (!has_real_callbacks_) return FrequencyDomainStatus::unavailable; std::vector<double> in_real(dimension_),in_imag(dimension_),out_real(dimension_),out_imag(dimension_),unused(dimension_); for(std::uint64_t i=0;i<dimension_;++i){in_real[i]=in[i].real();in_imag[i]=in[i].imag();} char error_message[128]{}; const auto apply = [&](const double *input,double *output) { if (real_callbacks_.apply_b_alpha != nullptr) return real_callbacks_.apply_b_alpha(real_callbacks_.context,input,output,error_message); if (real_callbacks_.apply_l_and_b_alpha != nullptr) return real_callbacks_.apply_l_and_b_alpha(real_callbacks_.context,input,unused.data(),output,error_message); return FrequencyDomainStatus::unavailable; }; const auto status_real=apply(in_real.data(),out_real.data()); if(status_real!=FrequencyDomainStatus::ok) return status_real; const auto status_imag=apply(in_imag.data(),out_imag.data()); if(status_imag!=FrequencyDomainStatus::ok) return status_imag; out->resize(dimension_); for(std::uint64_t i=0;i<dimension_;++i)(*out)[i]={out_real[i],out_imag[i]}; return FrequencyDomainStatus::ok; }
FrequencyDomainStatus LinearizedDynamicPencil::apply_Aomega(double omega, FrequencyDomainPhaseConvention phase, const std::vector<std::complex<double>> &in, std::vector<std::complex<double>> *out) const noexcept { if(!std::isfinite(omega)||!valid(*this,in,out)) return FrequencyDomainStatus::validation_error; std::vector<std::complex<double>> l,b; const auto l_status=apply_L(in,&l); if(l_status!=FrequencyDomainStatus::ok) return l_status; const auto b_status=apply_B_alpha(in,&b); if(b_status!=FrequencyDomainStatus::ok) return b_status; out->resize(dimension_); const auto coeff=phase_i(phase)*omega; for(std::uint64_t i=0;i<dimension_;++i)(*out)[i]=coeff*b[i]-l[i]; return FrequencyDomainStatus::ok; }
FrequencyDomainStatus LinearizedDynamicPencil::apply_fused_Aomega(double omega, FrequencyDomainPhaseConvention phase, const std::vector<std::complex<double>> &in, std::vector<std::complex<double>> *out) const noexcept { return apply_Aomega(omega,phase,in,out); }
FrequencyDomainStatus LinearizedDynamicPencil::apply_Aomega_adjoint(double omega, FrequencyDomainPhaseConvention phase, const std::vector<std::complex<double>> &in, std::vector<std::complex<double>> *out) const noexcept { if(!std::isfinite(omega)||!valid(*this,in,out)) return FrequencyDomainStatus::validation_error; if (l_.size()!=dimension_*dimension_||b_alpha_.size()!=dimension_*dimension_) return FrequencyDomainStatus::unavailable; std::vector<std::complex<double>> l,b; apply_dense(l_,dimension_,in,&l,true); apply_dense(b_alpha_,dimension_,in,&b,true); out->resize(dimension_); const auto coeff=std::conj(phase_i(phase)*omega); for(std::uint64_t i=0;i<dimension_;++i)(*out)[i]=coeff*b[i]-l[i]; return FrequencyDomainStatus::ok; }
FrequencyDomainStatus LinearizedDynamicPencil::apply_Aomega_real_split(double omega, FrequencyDomainPhaseConvention phase, const double *in_real, const double *in_imag, double *out_real, double *out_imag, double *l_real, double *l_imag, double *b_real, double *b_imag, char error_message[128]) const noexcept { if (!has_real_callbacks_ || !std::isfinite(omega) || in_real == nullptr || in_imag == nullptr || out_real == nullptr || out_imag == nullptr || l_real == nullptr || l_imag == nullptr || b_real == nullptr || b_imag == nullptr) return FrequencyDomainStatus::validation_error; FrequencyDomainStatus status = FrequencyDomainStatus::ok; if (real_callbacks_.apply_l_and_b_alpha != nullptr) { status = real_callbacks_.apply_l_and_b_alpha(real_callbacks_.context, in_real, l_real, b_real, error_message); if (status != FrequencyDomainStatus::ok) return status; status = real_callbacks_.apply_l_and_b_alpha(real_callbacks_.context, in_imag, l_imag, b_imag, error_message); if (status != FrequencyDomainStatus::ok) return status; } else { const auto apply = [&](LinearizedDynamicPencilRealApply callback, const double *in, double *out) { return callback(real_callbacks_.context, in, out, error_message); }; status = apply(real_callbacks_.apply_l, in_real, l_real); if(status != FrequencyDomainStatus::ok) return status; status = apply(real_callbacks_.apply_l, in_imag, l_imag); if(status != FrequencyDomainStatus::ok) return status; status = apply(real_callbacks_.apply_b_alpha, in_real, b_real); if(status != FrequencyDomainStatus::ok) return status; status = apply(real_callbacks_.apply_b_alpha, in_imag, b_imag); if(status != FrequencyDomainStatus::ok) return status; } const double sign = phase == FrequencyDomainPhaseConvention::exp_i_omega_t ? 1.0 : -1.0; for(std::uint64_t i=0;i<dimension_;++i) { out_real[i] = -sign * omega * b_imag[i] - l_real[i]; out_imag[i] = sign * omega * b_real[i] - l_imag[i]; } return FrequencyDomainStatus::ok; }
} // namespace fullmag::fem::frequency_domain
