[package]
name = "fullmag-runner"
version.workspace = true
edition.workspace = true
publish.workspace = true

[features]
default = []
cuda = ["dep:fullmag-fdm-sys", "fullmag-fdm-sys/build-native"]
fdm-native-cpu = ["dep:fullmag-fdm-sys", "fullmag-fdm-sys/build-native-cpu"]
fem-gpu = ["dep:fullmag-fem-sys", "fullmag-fem-sys/build-native"]
stage-autosave-hdf5 = ["dep:hdf5"]

[dependencies]
fullmag-engine = { path = "../fullmag-engine", features = ["parallel"] }
fullmag-fdm-demag = { path = "../fullmag-fdm-demag" }
fullmag-fdm-sys = { path = "../fullmag-fdm-sys", optional = true }
fullmag-fem-sys = { path = "../fullmag-fem-sys", optional = true }
fullmag-ir = { path = "../fullmag-ir" }
fullmag-plan = { path = "../fullmag-plan" }
fullmag-quantities = { path = "../fullmag-quantities" }
rayon = "1.10"
rustfft = "6.4"
nalgebra = "0.33"
num-complex = "0.4"
serde = { workspace = true }
serde_json = { workspace = true, features = ["raw_value"] }
sha2 = "0.10"
uuid = { version = "1", features = ["v4"] }
hdf5 = { version = "0.8", optional = true }

[target.'cfg(unix)'.dependencies]
libc = "0.2"
