import type {
  BackendCapabilities,
  ScriptBuilderMagneticInteractionEntry,
  ScriptBuilderMagneticInteractionKind,
} from "./types";

export type PhysicsCatalogId =
  | "exchange"
  | "demag"
  | "zeeman"
  | "interfacial_dmi"
  | "bulk_dmi"
  | "uniaxial_anisotropy"
  | "cubic_anisotropy"
  | "thermal_noise"
  | "oersted"
  | "magnetoelastic"
  | "spin_transfer_torque"
  | "spin_orbit_torque"
  | "boundary_correction";

export interface PhysicsCatalogEntry {
  id: PhysicsCatalogId;
  label: string;
  description: string;
  detail: string;
  scope: "object" | "global" | "coupling" | "runtime";
  backendTerms: string[];
  objectInteractionKind?: ScriptBuilderMagneticInteractionKind;
  defaultRequired?: boolean;
  parameterHints?: string[];
}

export interface PhysicsCapabilityViewEntry {
  id: PhysicsCatalogId;
  label: string;
  description: string;
  detail: string;
  scope: PhysicsCatalogEntry["scope"];
  available: boolean;
  active: boolean;
  authorableInObjectPanel: boolean;
  required: boolean;
  backendTerms: string[];
  parameterHints: string[];
}

const CATALOG: PhysicsCatalogEntry[] = [
  {
    id: "exchange",
    label: "Exchange",
    description: "Short-range spin alignment term.",
    detail: "Controls stiffness of neighboring magnetization directions and remains mandatory for ferromagnetic objects.",
    scope: "object",
    backendTerms: ["exchange"],
    objectInteractionKind: "exchange",
    defaultRequired: true,
  },
  {
    id: "demag",
    label: "Demagnetization",
    description: "Magnetostatic self-interaction of the sample.",
    detail: "Backend realization depends on discretization and engine; UI should report the resolved path explicitly.",
    scope: "global",
    backendTerms: ["demag_tensor_fft_newell", "demag_poisson_robin", "demag_poisson_dirichlet"],
    objectInteractionKind: "demag",
    defaultRequired: true,
    parameterHints: ["Demag realization is configured at study/runtime level."],
  },
  {
    id: "zeeman",
    label: "Zeeman / External Field",
    description: "Couples magnetization to applied magnetic field.",
    detail: "Typically driven by study-level bias/probe fields or explicit field-setting stages.",
    scope: "global",
    backendTerms: ["zeeman"],
  },
  {
    id: "interfacial_dmi",
    label: "Interfacial DMI",
    description: "Chiral interfacial exchange with preferred rotation sense.",
    detail: "Authoring currently binds it through the object physics stack and material Dind metadata.",
    scope: "object",
    backendTerms: ["interfacial_dmi"],
    objectInteractionKind: "interfacial_dmi",
    parameterHints: ["Dind [J/m^2]", "Optional interface normal [x, y, z]"],
  },
  {
    id: "bulk_dmi",
    label: "Bulk DMI",
    description: "Chiral bulk Dzyaloshinskii-Moriya interaction.",
    detail: "Present in the Python/backend model, but not yet first-class in the scene authoring object panel.",
    scope: "object",
    backendTerms: ["bulk_dmi"],
    parameterHints: ["D [J/m^2]"],
  },
  {
    id: "uniaxial_anisotropy",
    label: "Uniaxial Anisotropy",
    description: "Single easy-axis or easy-plane anisotropy term.",
    detail: "Useful for crystalline easy-axis materials and interface-driven perpendicular anisotropy models.",
    scope: "object",
    backendTerms: ["uniaxial_anisotropy"],
    objectInteractionKind: "uniaxial_anisotropy",
    parameterHints: ["Ku1 [J/m^3]", "Ku2 [J/m^3]", "Axis [x, y, z]"],
  },
  {
    id: "cubic_anisotropy",
    label: "Cubic Anisotropy",
    description: "Magnetocrystalline anisotropy with multiple crystal axes.",
    detail: "Supported by backend capability profiles, but not yet exposed as a first-class object interaction editor.",
    scope: "object",
    backendTerms: ["cubic_anisotropy"],
    parameterHints: ["Kc1/Kc2/Kc3 [J/m^3]", "Axis1 [x, y, z]", "Axis2 [x, y, z]"],
  },
  {
    id: "thermal_noise",
    label: "Thermal Noise",
    description: "Brown thermal fluctuations in the stochastic LLG.",
    detail: "Requires explicit temperature/seed semantics and is backend-dependent for reproducibility.",
    scope: "global",
    backendTerms: ["thermal"],
    parameterHints: ["Temperature [K]", "Optional RNG seed"],
  },
  {
    id: "oersted",
    label: "Oersted Field",
    description: "Field generated by current-carrying conductors or transport solutions.",
    detail: "Can come from analytical cylinder models or named current-transport modules in the Python DSL.",
    scope: "global",
    backendTerms: ["oersted"],
    parameterHints: ["Current source or analytical cylinder", "Time dependence envelope"],
  },
  {
    id: "magnetoelastic",
    label: "Magnetoelastic Coupling",
    description: "Couples magnetic and elastic subsystems.",
    detail: "This is a cross-domain coupling, so it should not be reduced to a simple object-local checkbox.",
    scope: "coupling",
    backendTerms: ["magnetoelastic"],
    parameterHints: ["Magnet reference", "Elastic body", "Magnetostriction law"],
  },
  {
    id: "spin_transfer_torque",
    label: "Spin-Transfer Torque",
    description: "Current-driven torque from spin-polarized transport.",
    detail: "Backend profiles may support Slonczewski/Zhang-Li subsets even if the scene editor does not expose all module variants yet.",
    scope: "global",
    backendTerms: ["stt"],
    parameterHints: ["Current source or density", "Polarization / beta / lambda"],
  },
  {
    id: "spin_orbit_torque",
    label: "Spin-Orbit Torque",
    description: "Torque driven by spin Hall or related interfacial effects.",
    detail: "Capability availability should be visible even when authoring support is still catching up.",
    scope: "global",
    backendTerms: ["sot"],
    parameterHints: ["Torque model", "Current source", "Spin Hall parameters"],
  },
  {
    id: "boundary_correction",
    label: "Boundary Correction",
    description: "Backend-side boundary operator refinement.",
    detail: "This is a runtime/operator capability rather than a public physics term, but it matters for explaining solver behavior.",
    scope: "runtime",
    backendTerms: ["boundary_correction"],
  },
];

const BY_ID = new Map(CATALOG.map((entry) => [entry.id, entry] as const));
const BACKEND_TERM_TO_ID = new Map<string, PhysicsCatalogId>();

for (const entry of CATALOG) {
  for (const term of entry.backendTerms) {
    BACKEND_TERM_TO_ID.set(term, entry.id);
  }
}

export function getPhysicsCatalog(): PhysicsCatalogEntry[] {
  return CATALOG;
}

export function getPhysicsCatalogEntry(id: PhysicsCatalogId): PhysicsCatalogEntry | null {
  return BY_ID.get(id) ?? null;
}

export function mapBackendTermToCatalogId(term: string): PhysicsCatalogId | null {
  return BACKEND_TERM_TO_ID.get(term) ?? null;
}

export function buildPhysicsCapabilityView(
  capabilities: BackendCapabilities | null | undefined,
  physicsStack: readonly ScriptBuilderMagneticInteractionEntry[] | null | undefined = null,
): PhysicsCapabilityViewEntry[] {
  const availableIds = new Set<PhysicsCatalogId>();
  for (const term of capabilities?.supported_terms ?? []) {
    const id = mapBackendTermToCatalogId(term);
    if (id) availableIds.add(id);
  }

  const activeKinds = new Set(
    (physicsStack ?? [])
      .filter((entry) => entry.enabled !== false)
      .map((entry) => entry.kind),
  );

  return CATALOG.map((entry) => {
    const objectKind = entry.objectInteractionKind;
    const active =
      objectKind != null
        ? activeKinds.has(objectKind) || Boolean(entry.defaultRequired)
        : false;

    return {
      id: entry.id,
      label: entry.label,
      description: entry.description,
      detail: entry.detail,
      scope: entry.scope,
      available: availableIds.has(entry.id),
      active,
      authorableInObjectPanel: objectKind != null,
      required: Boolean(entry.defaultRequired),
      backendTerms: entry.backendTerms,
      parameterHints: entry.parameterHints ?? [],
    };
  });
}
