[package]
name = "fullmag-engine"
version.workspace = true
edition.workspace = true
publish.workspace = true

[features]
default = []
parallel = ["dep:rayon"]
telemetry = []

[dependencies]
fullmag-ir = { path = "../fullmag-ir" }
fullmag-fdm-demag = { path = "../fullmag-fdm-demag" }
rustfft = "6.4"
rayon = { version = "1.10", optional = true }
serde = { version = "1", features = ["derive"] }
sha2 = "0.10"

[dev-dependencies]
serde_json = "1"
