//! Canonical quantity catalog — the single source of truth for all quantity metadata.

use crate::descriptor::{NormalizationHint, QuantityDomain, QuantityLocation, QuantitySpec};
use crate::id::{normalize_quantity_id, QuantityId};
use crate::{QuantityComponent, QuantityShape};

const CATALOG: [QuantitySpec; 44] = [
    QuantitySpec {
        id: QuantityId::M,
        label: "Magnetization",
        description: "Reduced magnetization vector (|m|=1)",
        shape: QuantityShape::VectorField,
        unit: "dimensionless",
        interactive_preview: true,
        cached_preview: true,
        quick_access_label: Some("M"),
        scalar_metric_key: None,
        ui_exposed: true,
        n_comp: 3,
        location: QuantityLocation::Node,
        domain: QuantityDomain::MagneticOnly,
        normalization_hint: NormalizationHint::UnitVector,
        default_component: QuantityComponent::Vector3,
        supports_preview_2d: true,
        supports_preview_3d: true,
        supports_history: false,
        supports_export: true,
    },
    QuantitySpec {
        id: QuantityId::HEx,
        label: "Exchange Field",
        description: "Exchange effective field contribution",
        shape: QuantityShape::VectorField,
        unit: "A/m",
        interactive_preview: true,
        cached_preview: true,
        quick_access_label: Some("H_ex"),
        scalar_metric_key: None,
        ui_exposed: true,
        n_comp: 3,
        location: QuantityLocation::Node,
        domain: QuantityDomain::MagneticOnly,
        normalization_hint: NormalizationHint::MaxAbs,
        default_component: QuantityComponent::Vector3,
        supports_preview_2d: true,
        supports_preview_3d: true,
        supports_history: false,
        supports_export: true,
    },
    QuantitySpec {
        id: QuantityId::HDemag,
        label: "Demagnetization Field",
        description: "Demagnetizing (stray) field",
        shape: QuantityShape::VectorField,
        unit: "A/m",
        interactive_preview: true,
        cached_preview: true,
        quick_access_label: Some("H_demag"),
        scalar_metric_key: None,
        ui_exposed: true,
        n_comp: 3,
        location: QuantityLocation::Node,
        domain: QuantityDomain::FullDomain,
        normalization_hint: NormalizationHint::MaxAbs,
        default_component: QuantityComponent::Vector3,
        supports_preview_2d: true,
        supports_preview_3d: true,
        supports_history: false,
        supports_export: true,
    },
    QuantitySpec {
        id: QuantityId::HExt,
        label: "External Field",
        description: "Externally applied magnetic field",
        shape: QuantityShape::VectorField,
        unit: "A/m",
        interactive_preview: true,
        cached_preview: true,
        quick_access_label: Some("H_ext"),
        scalar_metric_key: None,
        ui_exposed: true,
        n_comp: 3,
        location: QuantityLocation::Node,
        domain: QuantityDomain::FullDomain,
        normalization_hint: NormalizationHint::MaxAbs,
        default_component: QuantityComponent::Vector3,
        supports_preview_2d: true,
        supports_preview_3d: true,
        supports_history: false,
        supports_export: true,
    },
    QuantitySpec {
        id: QuantityId::HAnt,
        label: "Antenna Field",
        description: "Microwave antenna excitation field",
        shape: QuantityShape::VectorField,
        unit: "A/m",
        interactive_preview: true,
        cached_preview: true,
        quick_access_label: Some("H_ant"),
        scalar_metric_key: None,
        ui_exposed: true,
        n_comp: 3,
        location: QuantityLocation::Node,
        domain: QuantityDomain::FullDomain,
        normalization_hint: NormalizationHint::MaxAbs,
        default_component: QuantityComponent::Vector3,
        supports_preview_2d: true,
        supports_preview_3d: true,
        supports_history: false,
        supports_export: true,
    },
    QuantitySpec {
        id: QuantityId::HEff,
        label: "Effective Field",
        description: "Total effective magnetic field",
        shape: QuantityShape::VectorField,
        unit: "A/m",
        interactive_preview: true,
        cached_preview: true,
        quick_access_label: Some("H_eff"),
        scalar_metric_key: None,
        ui_exposed: true,
        n_comp: 3,
        location: QuantityLocation::Node,
        domain: QuantityDomain::FullDomain,
        normalization_hint: NormalizationHint::MaxAbs,
        default_component: QuantityComponent::Vector3,
        supports_preview_2d: true,
        supports_preview_3d: true,
        supports_history: false,
        supports_export: true,
    },
    QuantitySpec {
        id: QuantityId::Torque,
        label: "Torque",
        description: "Total Landau-Lifshitz torque divided by gamma0, matching mumax torque",
        shape: QuantityShape::VectorField,
        unit: "T",
        interactive_preview: true,
        cached_preview: true,
        quick_access_label: Some("τ"),
        scalar_metric_key: None,
        ui_exposed: true,
        n_comp: 3,
        location: QuantityLocation::Node,
        domain: QuantityDomain::MagneticOnly,
        normalization_hint: NormalizationHint::MaxAbs,
        default_component: QuantityComponent::Magnitude,
        supports_preview_2d: true,
        supports_preview_3d: true,
        supports_history: false,
        supports_export: false,
    },
    QuantitySpec {
        id: QuantityId::HAni,
        label: "Anisotropy Field",
        description: "Uniaxial anisotropy effective field",
        shape: QuantityShape::VectorField,
        unit: "A/m",
        interactive_preview: true,
        cached_preview: true,
        quick_access_label: Some("H_ani"),
        scalar_metric_key: None,
        ui_exposed: true,
        n_comp: 3,
        location: QuantityLocation::Node,
        domain: QuantityDomain::MagneticOnly,
        normalization_hint: NormalizationHint::MaxAbs,
        default_component: QuantityComponent::Vector3,
        supports_preview_2d: true,
        supports_preview_3d: true,
        supports_history: false,
        supports_export: true,
    },
    QuantitySpec {
        id: QuantityId::HDmi,
        label: "DMI Field",
        description: "Interfacial Dzyaloshinskii-Moriya effective field",
        shape: QuantityShape::VectorField,
        unit: "A/m",
        interactive_preview: true,
        cached_preview: true,
        quick_access_label: Some("H_dmi"),
        scalar_metric_key: None,
        ui_exposed: true,
        n_comp: 3,
        location: QuantityLocation::Node,
        domain: QuantityDomain::MagneticOnly,
        normalization_hint: NormalizationHint::MaxAbs,
        default_component: QuantityComponent::Vector3,
        supports_preview_2d: true,
        supports_preview_3d: true,
        supports_history: false,
        supports_export: true,
    },
    QuantitySpec {
        id: QuantityId::HMel,
        label: "Magnetoelastic Field",
        description: "Magnetoelastic coupling effective field",
        shape: QuantityShape::VectorField,
        unit: "A/m",
        interactive_preview: true,
        cached_preview: true,
        quick_access_label: Some("H_mel"),
        scalar_metric_key: None,
        ui_exposed: true,
        n_comp: 3,
        location: QuantityLocation::Node,
        domain: QuantityDomain::MagneticOnly,
        normalization_hint: NormalizationHint::MaxAbs,
        default_component: QuantityComponent::Vector3,
        supports_preview_2d: true,
        supports_preview_3d: true,
        supports_history: false,
        supports_export: true,
    },
    QuantitySpec {
        id: QuantityId::U,
        label: "Displacement",
        description: "Mechanical displacement field",
        shape: QuantityShape::VectorField,
        unit: "m",
        interactive_preview: false,
        cached_preview: false,
        quick_access_label: Some("u"),
        scalar_metric_key: None,
        ui_exposed: false,
        n_comp: 3,
        location: QuantityLocation::Node,
        domain: QuantityDomain::FullDomain,
        normalization_hint: NormalizationHint::MaxAbs,
        default_component: QuantityComponent::Vector3,
        supports_preview_2d: false,
        supports_preview_3d: false,
        supports_history: false,
        supports_export: true,
    },
    QuantitySpec {
        id: QuantityId::Eps,
        label: "Strain",
        description: "Small-strain tensor in Voigt notation",
        shape: QuantityShape::VectorField,
        unit: "1",
        interactive_preview: false,
        cached_preview: false,
        quick_access_label: Some("eps"),
        scalar_metric_key: None,
        ui_exposed: false,
        n_comp: 6,
        location: QuantityLocation::Cell,
        domain: QuantityDomain::FullDomain,
        normalization_hint: NormalizationHint::MaxAbs,
        default_component: QuantityComponent::Magnitude,
        supports_preview_2d: false,
        supports_preview_3d: false,
        supports_history: false,
        supports_export: true,
    },
    QuantitySpec {
        id: QuantityId::Sigma,
        label: "Stress",
        description: "Cauchy stress tensor in Voigt notation",
        shape: QuantityShape::VectorField,
        unit: "Pa",
        interactive_preview: false,
        cached_preview: false,
        quick_access_label: Some("sigma"),
        scalar_metric_key: None,
        ui_exposed: false,
        n_comp: 6,
        location: QuantityLocation::Cell,
        domain: QuantityDomain::FullDomain,
        normalization_hint: NormalizationHint::MaxAbs,
        default_component: QuantityComponent::Magnitude,
        supports_preview_2d: false,
        supports_preview_3d: false,
        supports_history: false,
        supports_export: true,
    },
    QuantitySpec {
        id: QuantityId::HAniCubic,
        label: "Cubic Anisotropy Field",
        description: "Cubic magnetocrystalline anisotropy effective field",
        shape: QuantityShape::VectorField,
        unit: "A/m",
        interactive_preview: true,
        cached_preview: true,
        quick_access_label: Some("H_ani_cubic"),
        scalar_metric_key: None,
        ui_exposed: true,
        n_comp: 3,
        location: QuantityLocation::Node,
        domain: QuantityDomain::MagneticOnly,
        normalization_hint: NormalizationHint::MaxAbs,
        default_component: QuantityComponent::Vector3,
        supports_preview_2d: true,
        supports_preview_3d: true,
        supports_history: false,
        supports_export: true,
    },
    QuantitySpec {
        id: QuantityId::HDmiBulk,
        label: "Bulk DMI Field",
        description: "Bulk Dzyaloshinskii-Moriya effective field",
        shape: QuantityShape::VectorField,
        unit: "A/m",
        interactive_preview: true,
        cached_preview: true,
        quick_access_label: Some("H_dmi_bulk"),
        scalar_metric_key: None,
        ui_exposed: true,
        n_comp: 3,
        location: QuantityLocation::Node,
        domain: QuantityDomain::MagneticOnly,
        normalization_hint: NormalizationHint::MaxAbs,
        default_component: QuantityComponent::Vector3,
        supports_preview_2d: true,
        supports_preview_3d: true,
        supports_history: false,
        supports_export: true,
    },
    QuantitySpec {
        id: QuantityId::HOe,
        label: "Oersted Field",
        description: "Current-induced Oersted field",
        shape: QuantityShape::VectorField,
        unit: "A/m",
        interactive_preview: true,
        cached_preview: true,
        quick_access_label: Some("H_oe"),
        scalar_metric_key: None,
        ui_exposed: true,
        n_comp: 3,
        location: QuantityLocation::Node,
        domain: QuantityDomain::FullDomain,
        normalization_hint: NormalizationHint::MaxAbs,
        default_component: QuantityComponent::Vector3,
        supports_preview_2d: true,
        supports_preview_3d: true,
        supports_history: false,
        supports_export: true,
    },
    QuantitySpec {
        id: QuantityId::HTherm,
        label: "Thermal Noise Field",
        description: "Stochastic thermal noise field (Langevin dynamics)",
        shape: QuantityShape::VectorField,
        unit: "A/m",
        interactive_preview: true,
        cached_preview: true,
        quick_access_label: Some("H_therm"),
        scalar_metric_key: None,
        ui_exposed: true,
        n_comp: 3,
        location: QuantityLocation::Node,
        domain: QuantityDomain::MagneticOnly,
        normalization_hint: NormalizationHint::MaxAbs,
        default_component: QuantityComponent::Vector3,
        supports_preview_2d: true,
        supports_preview_3d: true,
        supports_history: false,
        supports_export: true,
    },
    QuantitySpec {
        id: QuantityId::EEx,
        label: "Exchange Energy",
        description: "Exchange energy contribution",
        shape: QuantityShape::GlobalScalar,
        unit: "J",
        interactive_preview: false,
        cached_preview: false,
        quick_access_label: None,
        scalar_metric_key: Some("e_ex"),
        ui_exposed: true,
        n_comp: 1,
        location: QuantityLocation::Global,
        domain: QuantityDomain::MagneticOnly,
        normalization_hint: NormalizationHint::None,
        default_component: QuantityComponent::Magnitude,
        supports_preview_2d: false,
        supports_preview_3d: false,
        supports_history: true,
        supports_export: true,
    },
    QuantitySpec {
        id: QuantityId::EDemag,
        label: "Demagnetization Energy",
        description: "Demagnetization energy contribution",
        shape: QuantityShape::GlobalScalar,
        unit: "J",
        interactive_preview: false,
        cached_preview: false,
        quick_access_label: None,
        scalar_metric_key: Some("e_demag"),
        ui_exposed: true,
        n_comp: 1,
        location: QuantityLocation::Global,
        domain: QuantityDomain::MagneticOnly,
        normalization_hint: NormalizationHint::None,
        default_component: QuantityComponent::Magnitude,
        supports_preview_2d: false,
        supports_preview_3d: false,
        supports_history: true,
        supports_export: true,
    },
    QuantitySpec {
        id: QuantityId::EExt,
        label: "External Energy",
        description: "Zeeman energy due to external field",
        shape: QuantityShape::GlobalScalar,
        unit: "J",
        interactive_preview: false,
        cached_preview: false,
        quick_access_label: None,
        scalar_metric_key: Some("e_ext"),
        ui_exposed: true,
        n_comp: 1,
        location: QuantityLocation::Global,
        domain: QuantityDomain::FullDomain,
        normalization_hint: NormalizationHint::None,
        default_component: QuantityComponent::Magnitude,
        supports_preview_2d: false,
        supports_preview_3d: false,
        supports_history: true,
        supports_export: true,
    },
    QuantitySpec {
        id: QuantityId::EAni,
        label: "Anisotropy Energy",
        description: "Magnetocrystalline anisotropy energy",
        shape: QuantityShape::GlobalScalar,
        unit: "J",
        interactive_preview: false,
        cached_preview: false,
        quick_access_label: None,
        scalar_metric_key: Some("e_ani"),
        ui_exposed: true,
        n_comp: 1,
        location: QuantityLocation::Global,
        domain: QuantityDomain::MagneticOnly,
        normalization_hint: NormalizationHint::None,
        default_component: QuantityComponent::Magnitude,
        supports_preview_2d: false,
        supports_preview_3d: false,
        supports_history: true,
        supports_export: true,
    },
    QuantitySpec {
        id: QuantityId::EDmi,
        label: "DMI Energy",
        description: "Dzyaloshinskii-Moriya interaction energy",
        shape: QuantityShape::GlobalScalar,
        unit: "J",
        interactive_preview: false,
        cached_preview: false,
        quick_access_label: None,
        scalar_metric_key: Some("e_dmi"),
        ui_exposed: true,
        n_comp: 1,
        location: QuantityLocation::Global,
        domain: QuantityDomain::MagneticOnly,
        normalization_hint: NormalizationHint::None,
        default_component: QuantityComponent::Magnitude,
        supports_preview_2d: false,
        supports_preview_3d: false,
        supports_history: true,
        supports_export: true,
    },
    QuantitySpec {
        id: QuantityId::EEl,
        label: "Elastic Energy",
        description: "Mechanical elastic strain energy",
        shape: QuantityShape::GlobalScalar,
        unit: "J",
        interactive_preview: false,
        cached_preview: false,
        quick_access_label: None,
        scalar_metric_key: Some("e_el"),
        ui_exposed: false,
        n_comp: 1,
        location: QuantityLocation::Global,
        domain: QuantityDomain::FullDomain,
        normalization_hint: NormalizationHint::None,
        default_component: QuantityComponent::Magnitude,
        supports_preview_2d: false,
        supports_preview_3d: false,
        supports_history: true,
        supports_export: true,
    },
    QuantitySpec {
        id: QuantityId::EKinEl,
        label: "Elastic Kinetic Energy",
        description: "Mechanical kinetic energy for elastodynamics",
        shape: QuantityShape::GlobalScalar,
        unit: "J",
        interactive_preview: false,
        cached_preview: false,
        quick_access_label: None,
        scalar_metric_key: Some("e_kin_el"),
        ui_exposed: false,
        n_comp: 1,
        location: QuantityLocation::Global,
        domain: QuantityDomain::FullDomain,
        normalization_hint: NormalizationHint::None,
        default_component: QuantityComponent::Magnitude,
        supports_preview_2d: false,
        supports_preview_3d: false,
        supports_history: true,
        supports_export: true,
    },
    QuantitySpec {
        id: QuantityId::ElasticResidualNorm,
        label: "Elastic Residual Norm",
        description: "Mechanical solver residual norm",
        shape: QuantityShape::GlobalScalar,
        unit: "1",
        interactive_preview: false,
        cached_preview: false,
        quick_access_label: None,
        scalar_metric_key: Some("elastic_residual_norm"),
        ui_exposed: false,
        n_comp: 1,
        location: QuantityLocation::Global,
        domain: QuantityDomain::FullDomain,
        normalization_hint: NormalizationHint::None,
        default_component: QuantityComponent::Magnitude,
        supports_preview_2d: false,
        supports_preview_3d: false,
        supports_history: true,
        supports_export: true,
    },
    QuantitySpec {
        id: QuantityId::ETotal,
        label: "Total Energy",
        description: "Total micromagnetic energy",
        shape: QuantityShape::GlobalScalar,
        unit: "J",
        interactive_preview: false,
        cached_preview: false,
        quick_access_label: None,
        scalar_metric_key: Some("e_total"),
        ui_exposed: true,
        n_comp: 1,
        location: QuantityLocation::Global,
        domain: QuantityDomain::FullDomain,
        normalization_hint: NormalizationHint::None,
        default_component: QuantityComponent::Magnitude,
        supports_preview_2d: false,
        supports_preview_3d: false,
        supports_history: true,
        supports_export: true,
    },
    QuantitySpec {
        id: QuantityId::ModeAmplitude,
        label: "Mode Amplitude",
        description: "Spin-wave eigenmode amplitude",
        shape: QuantityShape::SpatialScalar,
        unit: "dimensionless",
        interactive_preview: false,
        cached_preview: false,
        quick_access_label: None,
        scalar_metric_key: None,
        ui_exposed: false,
        n_comp: 1,
        location: QuantityLocation::Node,
        domain: QuantityDomain::MagneticOnly,
        normalization_hint: NormalizationHint::MaxAbs,
        default_component: QuantityComponent::Magnitude,
        supports_preview_2d: false,
        supports_preview_3d: false,
        supports_history: false,
        supports_export: true,
    },
    QuantitySpec {
        id: QuantityId::ModeReal,
        label: "Mode Real Part",
        description: "Real part of spin-wave eigenmode",
        shape: QuantityShape::VectorField,
        unit: "dimensionless",
        interactive_preview: false,
        cached_preview: false,
        quick_access_label: None,
        scalar_metric_key: None,
        ui_exposed: false,
        n_comp: 3,
        location: QuantityLocation::Node,
        domain: QuantityDomain::MagneticOnly,
        normalization_hint: NormalizationHint::MaxAbs,
        default_component: QuantityComponent::Vector3,
        supports_preview_2d: false,
        supports_preview_3d: false,
        supports_history: false,
        supports_export: true,
    },
    QuantitySpec {
        id: QuantityId::ModeImag,
        label: "Mode Imaginary Part",
        description: "Imaginary part of spin-wave eigenmode",
        shape: QuantityShape::VectorField,
        unit: "dimensionless",
        interactive_preview: false,
        cached_preview: false,
        quick_access_label: None,
        scalar_metric_key: None,
        ui_exposed: false,
        n_comp: 3,
        location: QuantityLocation::Node,
        domain: QuantityDomain::MagneticOnly,
        normalization_hint: NormalizationHint::MaxAbs,
        default_component: QuantityComponent::Vector3,
        supports_preview_2d: false,
        supports_preview_3d: false,
        supports_history: false,
        supports_export: true,
    },
    QuantitySpec {
        id: QuantityId::ModePhase,
        label: "Mode Phase",
        description: "Phase of spin-wave eigenmode",
        shape: QuantityShape::SpatialScalar,
        unit: "rad",
        interactive_preview: false,
        cached_preview: false,
        quick_access_label: None,
        scalar_metric_key: None,
        ui_exposed: false,
        n_comp: 1,
        location: QuantityLocation::Node,
        domain: QuantityDomain::MagneticOnly,
        normalization_hint: NormalizationHint::None,
        default_component: QuantityComponent::Magnitude,
        supports_preview_2d: false,
        supports_preview_3d: false,
        supports_history: false,
        supports_export: true,
    },
    // ── Second wave (QB-17): energy densities, torques, dm/dt ──
    QuantitySpec {
        id: QuantityId::EdenEx,
        label: "Exchange Energy Density",
        description: "Spatial exchange energy density",
        shape: QuantityShape::SpatialScalar,
        unit: "J/m³",
        interactive_preview: true,
        cached_preview: false,
        quick_access_label: Some("ε_ex"),
        scalar_metric_key: None,
        ui_exposed: true,
        n_comp: 1,
        location: QuantityLocation::Cell,
        domain: QuantityDomain::MagneticOnly,
        normalization_hint: NormalizationHint::MaxAbs,
        default_component: QuantityComponent::Magnitude,
        supports_preview_2d: true,
        supports_preview_3d: false,
        supports_history: false,
        supports_export: true,
    },
    QuantitySpec {
        id: QuantityId::EdenDemag,
        label: "Demagnetization Energy Density",
        description: "Spatial demagnetization energy density",
        shape: QuantityShape::SpatialScalar,
        unit: "J/m³",
        interactive_preview: true,
        cached_preview: false,
        quick_access_label: Some("ε_demag"),
        scalar_metric_key: None,
        ui_exposed: true,
        n_comp: 1,
        location: QuantityLocation::Cell,
        domain: QuantityDomain::MagneticOnly,
        normalization_hint: NormalizationHint::MaxAbs,
        default_component: QuantityComponent::Magnitude,
        supports_preview_2d: true,
        supports_preview_3d: false,
        supports_history: false,
        supports_export: true,
    },
    QuantitySpec {
        id: QuantityId::EdenExt,
        label: "Zeeman Energy Density",
        description: "Spatial Zeeman (external field) energy density",
        shape: QuantityShape::SpatialScalar,
        unit: "J/m³",
        interactive_preview: true,
        cached_preview: false,
        quick_access_label: Some("ε_ext"),
        scalar_metric_key: None,
        ui_exposed: true,
        n_comp: 1,
        location: QuantityLocation::Cell,
        domain: QuantityDomain::MagneticOnly,
        normalization_hint: NormalizationHint::MaxAbs,
        default_component: QuantityComponent::Magnitude,
        supports_preview_2d: true,
        supports_preview_3d: false,
        supports_history: false,
        supports_export: true,
    },
    QuantitySpec {
        id: QuantityId::EdenAni,
        label: "Anisotropy Energy Density",
        description: "Spatial anisotropy energy density",
        shape: QuantityShape::SpatialScalar,
        unit: "J/m³",
        interactive_preview: true,
        cached_preview: false,
        quick_access_label: Some("ε_ani"),
        scalar_metric_key: None,
        ui_exposed: true,
        n_comp: 1,
        location: QuantityLocation::Cell,
        domain: QuantityDomain::MagneticOnly,
        normalization_hint: NormalizationHint::MaxAbs,
        default_component: QuantityComponent::Magnitude,
        supports_preview_2d: true,
        supports_preview_3d: false,
        supports_history: false,
        supports_export: true,
    },
    QuantitySpec {
        id: QuantityId::EdenDmi,
        label: "DMI Energy Density",
        description: "Spatial Dzyaloshinskii-Moriya energy density",
        shape: QuantityShape::SpatialScalar,
        unit: "J/m³",
        interactive_preview: true,
        cached_preview: false,
        quick_access_label: Some("ε_dmi"),
        scalar_metric_key: None,
        ui_exposed: true,
        n_comp: 1,
        location: QuantityLocation::Cell,
        domain: QuantityDomain::MagneticOnly,
        normalization_hint: NormalizationHint::MaxAbs,
        default_component: QuantityComponent::Magnitude,
        supports_preview_2d: true,
        supports_preview_3d: false,
        supports_history: false,
        supports_export: true,
    },
    QuantitySpec {
        id: QuantityId::EdenTotal,
        label: "Total Energy Density",
        description: "Spatial total energy density (sum of all contributions)",
        shape: QuantityShape::SpatialScalar,
        unit: "J/m³",
        interactive_preview: true,
        cached_preview: false,
        quick_access_label: Some("ε_total"),
        scalar_metric_key: None,
        ui_exposed: true,
        n_comp: 1,
        location: QuantityLocation::Cell,
        domain: QuantityDomain::MagneticOnly,
        normalization_hint: NormalizationHint::MaxAbs,
        default_component: QuantityComponent::Magnitude,
        supports_preview_2d: true,
        supports_preview_3d: false,
        supports_history: false,
        supports_export: true,
    },
    QuantitySpec {
        id: QuantityId::MatMs,
        label: "Material Ms",
        description: "Resolved saturation magnetization distribution",
        shape: QuantityShape::SpatialScalar,
        unit: "A/m",
        interactive_preview: true,
        cached_preview: false,
        quick_access_label: Some("Ms"),
        scalar_metric_key: None,
        ui_exposed: true,
        n_comp: 1,
        location: QuantityLocation::Cell,
        domain: QuantityDomain::MagneticOnly,
        normalization_hint: NormalizationHint::None,
        default_component: QuantityComponent::Magnitude,
        supports_preview_2d: true,
        supports_preview_3d: true,
        supports_history: false,
        supports_export: true,
    },
    QuantitySpec {
        id: QuantityId::MatAex,
        label: "Material Aex",
        description: "Resolved exchange stiffness distribution",
        shape: QuantityShape::SpatialScalar,
        unit: "J/m",
        interactive_preview: true,
        cached_preview: false,
        quick_access_label: Some("Aex"),
        scalar_metric_key: None,
        ui_exposed: true,
        n_comp: 1,
        location: QuantityLocation::Cell,
        domain: QuantityDomain::MagneticOnly,
        normalization_hint: NormalizationHint::None,
        default_component: QuantityComponent::Magnitude,
        supports_preview_2d: true,
        supports_preview_3d: true,
        supports_history: false,
        supports_export: true,
    },
    QuantitySpec {
        id: QuantityId::MatAlpha,
        label: "Material alpha",
        description: "Resolved Gilbert damping distribution",
        shape: QuantityShape::SpatialScalar,
        unit: "1",
        interactive_preview: true,
        cached_preview: false,
        quick_access_label: Some("alpha"),
        scalar_metric_key: None,
        ui_exposed: true,
        n_comp: 1,
        location: QuantityLocation::Cell,
        domain: QuantityDomain::MagneticOnly,
        normalization_hint: NormalizationHint::None,
        default_component: QuantityComponent::Magnitude,
        supports_preview_2d: true,
        supports_preview_3d: true,
        supports_history: false,
        supports_export: true,
    },
    QuantitySpec {
        id: QuantityId::MatDind,
        label: "Material Dind",
        description: "Resolved interfacial DMI distribution",
        shape: QuantityShape::SpatialScalar,
        unit: "J/m²",
        interactive_preview: true,
        cached_preview: false,
        quick_access_label: Some("Dind"),
        scalar_metric_key: None,
        ui_exposed: true,
        n_comp: 1,
        location: QuantityLocation::Cell,
        domain: QuantityDomain::MagneticOnly,
        normalization_hint: NormalizationHint::None,
        default_component: QuantityComponent::Magnitude,
        supports_preview_2d: true,
        supports_preview_3d: true,
        supports_history: false,
        supports_export: true,
    },
    QuantitySpec {
        id: QuantityId::MatDbulk,
        label: "Material Dbulk",
        description: "Resolved bulk DMI distribution",
        shape: QuantityShape::SpatialScalar,
        unit: "J/m³",
        interactive_preview: true,
        cached_preview: false,
        quick_access_label: Some("Dbulk"),
        scalar_metric_key: None,
        ui_exposed: true,
        n_comp: 1,
        location: QuantityLocation::Cell,
        domain: QuantityDomain::MagneticOnly,
        normalization_hint: NormalizationHint::None,
        default_component: QuantityComponent::Magnitude,
        supports_preview_2d: true,
        supports_preview_3d: true,
        supports_history: false,
        supports_export: true,
    },
    QuantitySpec {
        id: QuantityId::DmDt,
        label: "dm/dt",
        description: "Rate of magnetization change (spatial vector)",
        shape: QuantityShape::VectorField,
        unit: "1/s",
        interactive_preview: false,
        cached_preview: false,
        quick_access_label: Some("dm/dt"),
        scalar_metric_key: None,
        ui_exposed: false,
        n_comp: 3,
        location: QuantityLocation::Node,
        domain: QuantityDomain::MagneticOnly,
        normalization_hint: NormalizationHint::MaxAbs,
        default_component: QuantityComponent::Magnitude,
        supports_preview_2d: true,
        supports_preview_3d: true,
        supports_history: false,
        supports_export: true,
    },
    QuantitySpec {
        id: QuantityId::TorqueStt,
        label: "Spin-Transfer Torque",
        description: "Adiabatic / field-like spin-transfer torque",
        shape: QuantityShape::VectorField,
        unit: "1/s",
        interactive_preview: false,
        cached_preview: false,
        quick_access_label: Some("τ_STT"),
        scalar_metric_key: None,
        ui_exposed: false,
        n_comp: 3,
        location: QuantityLocation::Node,
        domain: QuantityDomain::MagneticOnly,
        normalization_hint: NormalizationHint::MaxAbs,
        default_component: QuantityComponent::Magnitude,
        supports_preview_2d: true,
        supports_preview_3d: true,
        supports_history: false,
        supports_export: true,
    },
    QuantitySpec {
        id: QuantityId::TorqueSot,
        label: "Spin-Orbit Torque",
        description: "Damping-like spin-orbit torque",
        shape: QuantityShape::VectorField,
        unit: "1/s",
        interactive_preview: false,
        cached_preview: false,
        quick_access_label: Some("τ_SOT"),
        scalar_metric_key: None,
        ui_exposed: false,
        n_comp: 3,
        location: QuantityLocation::Node,
        domain: QuantityDomain::MagneticOnly,
        normalization_hint: NormalizationHint::MaxAbs,
        default_component: QuantityComponent::Magnitude,
        supports_preview_2d: true,
        supports_preview_3d: true,
        supports_history: false,
        supports_export: true,
    },
];

/// Return the full immutable catalog.
pub fn quantity_catalog() -> &'static [QuantitySpec] {
    &CATALOG
}

/// Alias matching the legacy runner API name.
pub fn quantity_specs() -> &'static [QuantitySpec] {
    quantity_catalog()
}

/// Look up a single quantity spec by its string ID.
pub fn quantity_spec(id: &str) -> Option<&'static QuantitySpec> {
    let normalized = normalize_quantity_id(id).ok()?;
    CATALOG.iter().find(|spec| spec.id == normalized)
}

/// Return a list of all defined quantity IDs.
pub fn all_quantity_ids() -> Vec<&'static str> {
    CATALOG.iter().map(|spec| spec.id.as_str()).collect()
}

/// IDs of quantities that support interactive (live) preview.
pub fn interactive_preview_quantity_ids() -> Vec<&'static str> {
    CATALOG
        .iter()
        .filter(|spec| spec.ui_exposed && spec.interactive_preview)
        .map(|spec| spec.id.as_str())
        .collect()
}

/// IDs of quantities that should be cached for instant switching.
pub fn cached_preview_quantity_ids() -> Vec<&'static str> {
    CATALOG
        .iter()
        .filter(|spec| {
            spec.ui_exposed && spec.cached_preview && spec.shape == QuantityShape::VectorField
        })
        .map(|spec| spec.id.as_str())
        .collect()
}

/// Look up the display unit for a quantity.
pub fn quantity_unit(id: &str) -> &'static str {
    quantity_spec(id).map(|spec| spec.unit).unwrap_or("")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn mechanical_magnetoelastic_quantities_are_canonical_but_not_previewed_yet() {
        let expected = [
            ("u", QuantityShape::VectorField, "m"),
            ("eps", QuantityShape::VectorField, "1"),
            ("sigma", QuantityShape::VectorField, "Pa"),
            ("E_el", QuantityShape::GlobalScalar, "J"),
            ("E_kin_el", QuantityShape::GlobalScalar, "J"),
            ("elastic_residual_norm", QuantityShape::GlobalScalar, "1"),
        ];

        for (id, shape, unit) in expected {
            let spec = quantity_spec(id).expect("mechanical quantity should be catalogued");
            assert_eq!(
                normalize_quantity_id(id).expect("known quantity").as_str(),
                id
            );
            assert_eq!(spec.shape, shape);
            assert_eq!(spec.unit, unit);
            assert!(!spec.interactive_preview);
            assert!(!spec.cached_preview);
        }
    }

    #[test]
    fn material_parameter_quantities_are_spatial_scalars_for_viewport_debugging() {
        let expected = [
            ("mat_ms", "Material Ms", "A/m"),
            ("mat_aex", "Material Aex", "J/m"),
            ("mat_alpha", "Material alpha", "1"),
            ("mat_dind", "Material Dind", "J/m²"),
            ("mat_dbulk", "Material Dbulk", "J/m³"),
        ];

        for (id, label, unit) in expected {
            let spec = quantity_spec(id).expect("material quantity should be catalogued");
            assert_eq!(
                normalize_quantity_id(id).expect("known quantity").as_str(),
                id
            );
            assert_eq!(spec.label, label);
            assert_eq!(spec.shape, QuantityShape::SpatialScalar);
            assert_eq!(spec.unit, unit);
            assert_eq!(spec.n_comp, 1);
            assert_eq!(spec.domain, QuantityDomain::MagneticOnly);
            assert!(spec.interactive_preview);
            assert!(spec.ui_exposed);
            assert!(spec.supports_preview_3d);
        }
    }
}
