#include "core/fem_element_quadrature_material.hpp"
#include "cpu/mfem/interactions/anisotropy_cubic.hpp"

#include <array>
#include <cmath>
#include <cstdlib>
#include <iostream>
#include <limits>
#include <map>
#include <stdexcept>
#include <vector>

namespace {
using Powers = std::array<unsigned, 4>;
using Polynomial = std::map<Powers, double>;
struct Element { std::array<std::size_t, 4> nodes; double volume_m3; };
struct Integral { double value = 0.0; double absolute_terms = 0.0; std::size_t terms = 0u; };
[[noreturn]] void fail(const char *message) { std::cerr << "FAIL: " << message << '\n'; std::exit(1); }
void check(bool condition, const char *message) { if (!condition) fail(message); }
double gamma_n(std::size_t n) { const double u = std::numeric_limits<double>::epsilon() / 2.0; return static_cast<double>(n) * u / (1.0 - static_cast<double>(n) * u); }
double factorial(unsigned n) { double result = 1.0; for (unsigned i = 2u; i <= n; ++i) result *= static_cast<double>(i); return result; }
double monomial_integral(const Element &element, const Powers &powers) { unsigned degree = 0u; double result = 6.0 * element.volume_m3; for (unsigned power : powers) { degree += power; result *= factorial(power); } return result / factorial(degree + 3u); }
Polynomial linear(const std::array<double, 4> &values) { Polynomial result; for (std::size_t i = 0; i < 4u; ++i) { Powers powers{}; ++powers[i]; result[powers] += values[i]; } return result; }
Polynomial add(const Polynomial &a, const Polynomial &b) { Polynomial result = a; for (const auto &[powers, value] : b) result[powers] += value; return result; }
Polynomial scale(const Polynomial &a, double factor) { Polynomial result; for (const auto &[powers, value] : a) result[powers] += factor * value; return result; }
Polynomial multiply(const Polynomial &a, const Polynomial &b) { Polynomial result; for (const auto &[ap, av] : a) for (const auto &[bp, bv] : b) { Powers p{}; for (std::size_t i = 0; i < 4u; ++i) p[i] = ap[i] + bp[i]; result[p] += av * bv; } return result; }
Polynomial square(const Polynomial &a) { return multiply(a, a); }
Integral integrate(const Element &element, const Polynomial &polynomial) { Integral result; for (const auto &[powers, value] : polynomial) { const double term = value * monomial_integral(element, powers); result.value += term; result.absolute_terms += std::fabs(term); ++result.terms; } return result; }
std::array<double, 4> projection(const std::vector<double> &values, const Element &element, const std::array<double, 3> &axis) { std::array<double, 4> result{}; for (std::size_t i = 0; i < 4u; ++i) { const std::size_t base = 3u * element.nodes[i]; result[i] = values[base] * axis[0] + values[base + 1u] * axis[1] + values[base + 2u] * axis[2]; } return result; }
std::array<double, 4> scalar(const std::vector<double> &values, const Element &element) { std::array<double, 4> result{}; for (std::size_t i = 0; i < 4u; ++i) result[i] = values[element.nodes[i]]; return result; }
Polynomial sigma(const Polynomial &m1, const Polynomial &m2, const Polynomial &m3) { return add(add(multiply(square(m1), square(m2)), multiply(square(m2), square(m3))), multiply(square(m1), square(m3))); }
Polynomial sigma_derivative(const Polynomial &m1, const Polynomial &m2, const Polynomial &m3, const Polynomial &p1, const Polynomial &p2, const Polynomial &p3) { return scale(add(add(add(multiply(multiply(m1,p1),square(m2)), multiply(square(m1),multiply(m2,p2))), add(multiply(multiply(m2,p2),square(m3)), multiply(square(m2),multiply(m3,p3)))), add(multiply(multiply(m1,p1),square(m3)), multiply(square(m1),multiply(m3,p3)))), 2.0); }
Polynomial energy(const Element &element, const std::vector<double> &m, const std::vector<double> &k1, const std::vector<double> &k2, const std::vector<double> &k3, const std::array<double, 3> &a1, const std::array<double, 3> &a2) { const std::array<double,3> a3 = {a1[1]*a2[2]-a1[2]*a2[1], a1[2]*a2[0]-a1[0]*a2[2], a1[0]*a2[1]-a1[1]*a2[0]}; const auto m1=linear(projection(m,element,a1)), m2=linear(projection(m,element,a2)), m3=linear(projection(m,element,a3)), s=sigma(m1,m2,m3); return add(add(multiply(linear(scalar(k1,element)),s),multiply(linear(scalar(k2,element)),multiply(multiply(square(m1),square(m2)),square(m3)))),multiply(linear(scalar(k3,element)),square(s))); }
// Keep the Kc2 derivative expanded separately to avoid a numerical field or Context dependency.
Polynomial exact_derivative(const Element &element, const std::vector<double> &m, const std::vector<double> &p, const std::vector<double> &k1, const std::vector<double> &k2, const std::vector<double> &k3, const std::array<double, 3> &a1, const std::array<double, 3> &a2) { const std::array<double,3> a3 = {a1[1]*a2[2]-a1[2]*a2[1], a1[2]*a2[0]-a1[0]*a2[2], a1[0]*a2[1]-a1[1]*a2[0]}; const auto m1=linear(projection(m,element,a1)),m2=linear(projection(m,element,a2)),m3=linear(projection(m,element,a3)),p1=linear(projection(p,element,a1)),p2=linear(projection(p,element,a2)),p3=linear(projection(p,element,a3)),s=sigma(m1,m2,m3),ds=sigma_derivative(m1,m2,m3,p1,p2,p3); const auto k2term=scale(add(add(multiply(multiply(p1,m1),multiply(square(m2),square(m3))),multiply(multiply(p2,m2),multiply(square(m1),square(m3)))),multiply(multiply(p3,m3),multiply(square(m1),square(m2)))),2.0); return add(add(multiply(linear(scalar(k1,element)),ds),multiply(linear(scalar(k2,element)),k2term)),multiply(linear(scalar(k3,element)),scale(multiply(s,ds),2.0))); }
Integral all_energy(const std::vector<Element> &elements, const std::vector<double> &m, const std::vector<double> &k1, const std::vector<double> &k2, const std::vector<double> &k3, const std::array<double,3> &a1, const std::array<double,3> &a2) { Integral total; for (const auto &element : elements) { const auto part=integrate(element,energy(element,m,k1,k2,k3,a1,a2)); total.value+=part.value; total.absolute_terms+=part.absolute_terms; total.terms+=part.terms; } return total; }
Integral all_derivative(const std::vector<Element> &elements, const std::vector<double> &m, const std::vector<double> &p, const std::vector<double> &k1, const std::vector<double> &k2, const std::vector<double> &k3, const std::array<double,3> &a1, const std::array<double,3> &a2) { Integral total; for (const auto &element : elements) { const auto part=integrate(element,exact_derivative(element,m,p,k1,k2,k3,a1,a2)); total.value+=part.value; total.absolute_terms+=part.absolute_terms; total.terms+=part.terms; } return total; }
fullmag::fem::P1TetrahedralMaterialRealization sharp_realization() { return {6u, {{{{0u,1u,2u,3u}},1.0/6.0}, {{{0u,1u,2u,4u}},1.0/3.0}, {{{0u,1u,2u,5u}},1.0/2.0}}, {0u,1u}, {fullmag::fem::MaterialCoefficientLocation::element_dg0,{0.7e6,1.1e6,9.0e6}}, {fullmag::fem::MaterialCoefficientLocation::element_dg0,{8e-12,13e-12,0.0}}}; }
void active_scope_contract() { const auto material=sharp_realization(); const std::vector<Element> active={{{{0u,1u,2u,3u}},1.0/6.0},{{{0u,1u,2u,4u}},1.0/3.0}}; const std::vector<Element> all={active[0],active[1],{{{0u,1u,2u,5u}},1.0/2.0}}; const std::vector<double> m={0.2,-0.4,1.7,-0.1,0.6,1.3,0.5,0.1,-1.2,0.9,-0.3,1.4,-0.7,0.8,1.2,2.0,-1.0,0.5}; const std::vector<double> p={-0.3,0.1,0.2,0.4,-0.6,0.5,-0.2,0.7,-0.1,0.8,0.3,-0.4,0.6,-0.5,0.9,-0.4,0.6,-0.8}; const std::vector<double> k1={1.1e5,2.3e5,-0.8e5,3.1e5,1.7e5,9.7e5},k2={0.4e5,-0.2e5,0.7e5,0.1e5,-0.5e5,6.2e5},k3={-0.3e5,0.6e5,0.2e5,-0.7e5,0.4e5,3.9e5}; const std::array<double,3> a1={1.0,0.0,0.0},a2={0.0,1.0,0.0}; const auto expected=all_energy(active,m,k1,k2,k3,a1,a2), wrong=all_energy(all,m,k1,k2,k3,a1,a2); const double actual=fullmag::fem::cubic_anisotropy_energy_from_material_realization(material,m,k1,k2,k3,a1,a2); check(std::fabs(actual-expected.value)<=gamma_n(130u+expected.terms)*expected.absolute_terms,"sharp cubic energy must use active realization ordinals"); check(std::fabs(actual-wrong.value)>1e-6*std::fabs(wrong.value-expected.value),"including air tetrahedron must be observably wrong"); const auto expected_derivative=all_derivative(active,m,p,k1,k2,k3,a1,a2); const double analytic=fullmag::fem::cubic_anisotropy_directional_derivative_from_material_realization(material,m,p,k1,k2,k3,a1,a2); check(std::fabs(analytic-expected_derivative.value)<=gamma_n(160u+expected_derivative.terms)*expected_derivative.absolute_terms,"sharp cubic derivative must match active barycentric oracle"); constexpr double epsilon=1e-5; auto plus=m,minus=m; for(std::size_t i=0;i<m.size();++i){plus[i]+=epsilon*p[i];minus[i]-=epsilon*p[i];} const auto plus_oracle=all_energy(active,plus,k1,k2,k3,a1,a2),minus_oracle=all_energy(active,minus,k1,k2,k3,a1,a2); const double central=(fullmag::fem::cubic_anisotropy_energy_from_material_realization(material,plus,k1,k2,k3,a1,a2)-fullmag::fem::cubic_anisotropy_energy_from_material_realization(material,minus,k1,k2,k3,a1,a2))/(2.0*epsilon); const double exact_remainder=std::fabs((plus_oracle.value-minus_oracle.value)/(2.0*epsilon)-expected_derivative.value); const double roundoff=(gamma_n(130u+plus_oracle.terms)*plus_oracle.absolute_terms+gamma_n(130u+minus_oracle.terms)*minus_oracle.absolute_terms)/(2.0*epsilon)+gamma_n(2u)*(std::fabs(plus_oracle.value)+std::fabs(minus_oracle.value))/(2.0*epsilon); check(std::fabs(central-analytic)<=exact_remainder+roundoff+gamma_n(160u+expected_derivative.terms)*expected_derivative.absolute_terms,"central derivative must retain termwise roundoff and degree-nine remainder"); }
void rejects_invalid_contracts() { const auto material=sharp_realization(); const std::vector<double> m(18u,1.0),p(18u,0.5),k(6u,1.0); bool axes=false; try { static_cast<void>(fullmag::fem::cubic_anisotropy_energy_from_material_realization(material,m,k,k,k,{1.0,0.0,0.0},{0.5,0.5,0.0})); } catch(const std::invalid_argument &) { axes=true; } check(axes,"sharp cubic helper must reject nonorthogonal axes"); const fullmag::fem::P1TetrahedralMaterialRealization nodal(4u,{{{{0u,1u,2u,3u}},1.0/6.0}},{0u},{fullmag::fem::MaterialCoefficientLocation::nodal_p1,{1e6,1e6,1e6,1e6}},{fullmag::fem::MaterialCoefficientLocation::element_dg0,{0.0}}); bool ms=false; try { static_cast<void>(fullmag::fem::cubic_anisotropy_energy_from_material_realization(nodal,std::vector<double>(12u,1.0),std::vector<double>(4u,1.0),std::vector<double>(4u,1.0),std::vector<double>(4u,1.0),{1.0,0.0,0.0},{0.0,1.0,0.0})); } catch(const std::invalid_argument &) { ms=true; } check(ms,"sharp cubic helper must reject non-DG0 Ms"); }
} // namespace
int main() { active_scope_contract(); rejects_invalid_contracts(); return 0; }
