pub mod handlers;
pub mod middleware;

#[cfg(test)]
mod tests;

use axum::{
    routing::{get, post},
    Router,
};
use std::sync::Arc;

use crate::types::AppState;

/// Build the canonical resource-first v1 router.
pub fn build_v1_router() -> Router<Arc<AppState>> {
    Router::new()
        .route(
            "/v1/asyncapi.json",
            get(handlers::realtime::get_asyncapi_document),
        )
        .route(
            "/v1/docs/asyncapi",
            get(handlers::realtime::get_asyncapi_docs),
        )
        .route("/v1/live/current/status", get(handlers::status::get_status))
        .route(
            "/v1/live/current/ws",
            get(handlers::realtime::ws_current_live),
        )
        .route(
            "/v1/live/current/domain/meta",
            get(handlers::domain::get_domain_meta),
        )
        .route(
            "/v1/live/current/domain/topology",
            get(handlers::domain::get_domain_topology),
        )
        .route(
            "/v1/live/current/quantities/catalog",
            get(handlers::quantities::get_quantities_catalog),
        )
        .route(
            "/v1/live/current/fields/catalog",
            get(handlers::fields::get_field_catalog),
        )
        .route(
            "/v1/live/current/fields/:quantity_id/meta",
            get(handlers::fields::get_field_meta),
        )
        .route(
            "/v1/live/current/fields/:quantity_id/vector",
            get(handlers::fields::get_field_vector),
        )
        .route(
            "/v1/live/current/scalars",
            get(handlers::scalars::get_scalars),
        )
        .route(
            "/v1/live/current/display",
            get(handlers::display::get_display)
                .put(handlers::display::replace_display)
                .patch(handlers::display::patch_display),
        )
        .route(
            "/v1/live/current/workspace/selection",
            get(handlers::workspace::get_workspace_selection)
                .put(handlers::workspace::replace_workspace_selection),
        )
        .route(
            "/v1/live/current/workspace/tree/active-node",
            get(handlers::workspace::get_workspace_active_node)
                .put(handlers::workspace::replace_workspace_active_node),
        )
        .route(
            "/v1/live/current/workspace/ribbon",
            get(handlers::workspace::get_workspace_ribbon)
                .put(handlers::workspace::replace_workspace_ribbon),
        )
        .route(
            "/v1/live/current/workspace/layout",
            get(handlers::workspace::get_workspace_layout)
                .put(handlers::workspace::replace_workspace_layout),
        )
        .route(
            "/v1/live/current/mesh/summary",
            get(handlers::mesh::get_mesh_summary),
        )
        .route(
            "/v1/live/current/mesh/capabilities",
            get(handlers::mesh::get_mesh_capabilities),
        )
        .route(
            "/v1/live/current/mesh/builds/active",
            get(handlers::mesh::get_mesh_active_build),
        )
        .route(
            "/v1/live/current/mesh/builds/history",
            get(handlers::mesh::get_mesh_build_history),
        )
        .route(
            "/v1/live/current/mesh/builds/last-success",
            get(handlers::mesh::get_mesh_last_successful_build),
        )
        .route(
            "/v1/live/current/mesh/builds/commands",
            post(handlers::mesh::submit_mesh_build_command),
        )
        .route(
            "/v1/live/current/mesh/universe/config",
            get(handlers::mesh::get_mesh_universe_config)
                .put(handlers::mesh::replace_mesh_universe_config),
        )
        .route(
            "/v1/live/current/mesh/universe/report",
            get(handlers::mesh::get_mesh_universe_report),
        )
        .route(
            "/v1/live/current/mesh/universe/quality",
            get(handlers::mesh::get_mesh_universe_quality),
        )
        .route(
            "/v1/live/current/mesh/shared-domain/config",
            get(handlers::mesh::get_mesh_shared_domain_config)
                .put(handlers::mesh::replace_mesh_shared_domain_config),
        )
        .route(
            "/v1/live/current/mesh/shared-domain/report",
            get(handlers::mesh::get_mesh_shared_domain_report),
        )
        .route(
            "/v1/live/current/mesh/shared-domain/quality",
            get(handlers::mesh::get_mesh_shared_domain_quality),
        )
        .route(
            "/v1/live/current/mesh/shared-domain/manifest",
            get(handlers::mesh::get_mesh_shared_domain_manifest),
        )
        .route(
            "/v1/live/current/mesh/shared-domain/topology",
            get(handlers::mesh::get_mesh_shared_domain_topology),
        )
        .route(
            "/v1/live/current/mesh/objects/:object_id/config",
            get(handlers::mesh::get_mesh_object_config)
                .put(handlers::mesh::replace_mesh_object_config),
        )
        .route(
            "/v1/live/current/mesh/objects/:object_id/report",
            get(handlers::mesh::get_mesh_object_report),
        )
        .route(
            "/v1/live/current/mesh/objects/:object_id/quality",
            get(handlers::mesh::get_mesh_object_quality),
        )
        .route(
            "/v1/live/current/mesh/objects/:object_id/size-field",
            get(handlers::mesh::get_mesh_object_size_field),
        )
        .route(
            "/v1/live/current/mesh/objects/:object_id/topology",
            get(handlers::mesh::get_mesh_object_topology),
        )
        .route(
            "/v1/live/current/mesh/interfaces/:interface_id/config",
            get(handlers::mesh::get_mesh_interface_config)
                .put(handlers::mesh::replace_mesh_interface_config),
        )
        .route(
            "/v1/live/current/mesh/interfaces/:interface_id/report",
            get(handlers::mesh::get_mesh_interface_report),
        )
        .route(
            "/v1/live/current/mesh/interfaces/:interface_id/quality",
            get(handlers::mesh::get_mesh_interface_quality),
        )
        .route(
            "/v1/live/current/authoring/scene",
            get(handlers::authoring::get_authoring_scene)
                .put(handlers::authoring::replace_authoring_scene)
                .patch(handlers::authoring::patch_authoring_scene),
        )
        .route(
            "/v1/live/current/authoring/transactions",
            post(handlers::authoring::commit_authoring_transaction),
        )
        .route(
            "/v1/live/current/authoring/study/runtime",
            get(handlers::authoring::get_authoring_study_runtime)
                .patch(handlers::authoring::patch_authoring_study_runtime),
        )
        .route(
            "/v1/live/current/authoring/model/materials/:material_id",
            get(handlers::authoring::get_authoring_material)
                .patch(handlers::authoring::patch_authoring_material),
        )
        .route(
            "/v1/live/current/authoring/physics/objects/:object_id/interactions/:interaction_kind",
            get(handlers::authoring::get_authoring_object_interaction)
                .patch(handlers::authoring::patch_authoring_object_interaction),
        )
        .route(
            "/v1/live/current/authoring/script/source",
            get(handlers::authoring::get_authoring_script_source),
        )
        .route(
            "/v1/live/current/authoring/script/sync",
            post(handlers::authoring::sync_authoring_script),
        )
        .route(
            "/v1/live/current/commands",
            post(handlers::commands::submit_command),
        )
        .route(
            "/v1/live/current/commands/status",
            get(handlers::runtime::get_command_status),
        )
        .route(
            "/v1/live/current/commands/:command_id",
            get(handlers::runtime::get_command_detail),
        )
        .route(
            "/v1/live/current/assets/import",
            post(handlers::assets::import_asset),
        )
        .route(
            "/v1/live/current/runs/current",
            get(handlers::runtime::get_current_run),
        )
        .route(
            "/v1/live/current/stages/execution",
            get(handlers::runtime::get_stage_execution),
        )
        .route(
            "/v1/live/current/solver/status",
            get(handlers::runtime::get_solver_status),
        )
        .route(
            "/v1/live/current/solver/energies/current",
            get(handlers::runtime::get_solver_energies_current),
        )
        .route(
            "/v1/live/current/solver/energies/history",
            get(handlers::runtime::get_solver_energies_history),
        )
        .route(
            "/v1/live/current/artifacts",
            get(handlers::artifacts::list_artifacts),
        )
        .route(
            "/v1/live/current/artifacts/:artifact_id",
            get(handlers::artifacts::get_artifact),
        )
        .route(
            "/v1/live/current/eigen/spectrum",
            get(handlers::eigen::get_spectrum),
        )
        .route(
            "/v1/live/current/eigen/mode",
            get(handlers::eigen::get_mode),
        )
        .route(
            "/v1/live/current/eigen/dispersion",
            get(handlers::eigen::get_dispersion),
        )
        .route(
            "/v1/live/current/eigen/branches",
            get(handlers::eigen::get_branches),
        )
        .route(
            "/v1/live/current/logs/engine",
            get(handlers::system::get_engine_log),
        )
        .route(
            "/v1/live/current/gpu/telemetry",
            get(handlers::gpu::get_gpu_telemetry),
        )
        .route(
            "/v1/live/current/session/export",
            post(handlers::session::export_session),
        )
        .route(
            "/v1/live/current/session/import/inspect",
            post(handlers::session::inspect_session),
        )
        .route(
            "/v1/live/current/session/import/commit",
            post(handlers::session::commit_session),
        )
        .route(
            "/v1/live/current/session/checkpoints",
            get(handlers::session::list_checkpoints),
        )
        .route(
            "/v1/live/current/session/recovery",
            get(handlers::session::list_recovery),
        )
        .route(
            "/v1/live/current/session/recovery/clear",
            post(handlers::session::clear_recovery),
        )
        .route("/v1/capabilities", get(handlers::system::get_capabilities))
        .route("/v1/health", get(handlers::system::get_health))
        .layer(axum::middleware::from_fn(
            middleware::request_id::request_id_middleware,
        ))
        .layer(axum::middleware::from_fn(
            middleware::version::contract_version_middleware,
        ))
}
