# Resolve the Windows PETSc/SLEPc/MPI provider slice from one pinned prefix.
#
# This module deliberately does not claim PE, ABI, or runtime compatibility. It
# makes the CMake provider contract deterministic and records concrete files
# selected by imported targets for the packaging and PE gates.

include_guard(GLOBAL)

function(_fullmag_windows_modal_fail message_text)
    message(FATAL_ERROR "Fullmag Windows modal provider: ${message_text}")
endfunction()

function(_fullmag_windows_modal_path_within_prefix path prefix output_variable)
    get_filename_component(_modal_path_real "${path}" REALPATH)
    get_filename_component(_modal_prefix_real "${prefix}" REALPATH)
    file(TO_CMAKE_PATH "${_modal_path_real}" _modal_path_norm)
    file(TO_CMAKE_PATH "${_modal_prefix_real}" _modal_prefix_norm)
    string(TOLOWER "${_modal_path_norm}" _modal_path_lower)
    string(TOLOWER "${_modal_prefix_norm}" _modal_prefix_lower)
    string(LENGTH "${_modal_prefix_lower}" _modal_prefix_length)
    string(LENGTH "${_modal_path_lower}" _modal_path_length)
    set(_modal_inside FALSE)
    if(_modal_path_length GREATER_EQUAL _modal_prefix_length)
        string(SUBSTRING "${_modal_path_lower}" 0 ${_modal_prefix_length} _modal_head)
        if(_modal_head STREQUAL _modal_prefix_lower)
            if(_modal_path_length EQUAL _modal_prefix_length)
                set(_modal_inside TRUE)
            else()
                string(SUBSTRING "${_modal_path_lower}" ${_modal_prefix_length} 1 _modal_separator)
                if(_modal_separator STREQUAL "/")
                    set(_modal_inside TRUE)
                endif()
            endif()
        endif()
    endif()
    set(${output_variable} "${_modal_inside}" PARENT_SCOPE)
endfunction()

function(_fullmag_windows_modal_reset_receipt)
    set_property(GLOBAL PROPERTY FULLMAG_WINDOWS_MODAL_RECEIPT_FILES "")
    set_property(GLOBAL PROPERTY FULLMAG_WINDOWS_MODAL_RECEIPT_CONFIGS "")
    set_property(GLOBAL PROPERTY FULLMAG_WINDOWS_MODAL_RECEIPT_TARGETS "")
    set_property(GLOBAL PROPERTY FULLMAG_WINDOWS_MODAL_VISITED_TARGETS "")
endfunction()

function(_fullmag_windows_modal_append_unique property_name value)
    get_property(_modal_values GLOBAL PROPERTY "${property_name}")
    if(NOT _modal_values)
        set(_modal_values "")
    endif()
    file(TO_CMAKE_PATH "${value}" _modal_value_norm)
    string(TOLOWER "${_modal_value_norm}" _modal_value_key)
    set(_modal_seen FALSE)
    foreach(_modal_existing IN LISTS _modal_values)
        file(TO_CMAKE_PATH "${_modal_existing}" _modal_existing_norm)
        string(TOLOWER "${_modal_existing_norm}" _modal_existing_key)
        if(_modal_existing_key STREQUAL _modal_value_key)
            set(_modal_seen TRUE)
            break()
        endif()
    endforeach()
    if(NOT _modal_seen)
        list(APPEND _modal_values "${value}")
        set_property(GLOBAL PROPERTY "${property_name}" "${_modal_values}")
    endif()
endfunction()

function(_fullmag_windows_modal_require_file path prefix role extension output_variable)
    if(NOT IS_ABSOLUTE "${path}")
        _fullmag_windows_modal_fail("${role} must be an absolute path: ${path}")
    endif()
    if(NOT EXISTS "${path}" OR IS_DIRECTORY "${path}")
        _fullmag_windows_modal_fail("${role} is missing or is a directory: ${path}")
    endif()
    get_filename_component(_modal_real "${path}" REALPATH)
    _fullmag_windows_modal_path_within_prefix("${_modal_real}" "${prefix}" _modal_inside)
    if(NOT _modal_inside)
        _fullmag_windows_modal_fail("${role} escapes FULLMAG_FEM_DEPENDENCY_PREFIX: ${path}")
    endif()
    get_filename_component(_modal_extension "${_modal_real}" EXT)
    string(TOLOWER "${_modal_extension}" _modal_extension_lower)
    string(TOLOWER ".${extension}" _modal_expected_extension)
    if(NOT _modal_extension_lower STREQUAL _modal_expected_extension)
        _fullmag_windows_modal_fail("${role} must use ${_modal_expected_extension}: ${path}")
    endif()
    file(SIZE "${_modal_real}" _modal_size)
    if(_modal_size EQUAL 0)
        _fullmag_windows_modal_fail("${role} is empty: ${path}")
    endif()
    _fullmag_windows_modal_append_unique(FULLMAG_WINDOWS_MODAL_RECEIPT_FILES "${_modal_real}")
    set(${output_variable} "${_modal_real}" PARENT_SCOPE)
endfunction()

function(_fullmag_windows_modal_require_directory path prefix role)
    if(NOT IS_ABSOLUTE "${path}" OR NOT IS_DIRECTORY "${path}")
        _fullmag_windows_modal_fail("${role} must be an existing absolute directory: ${path}")
    endif()
    get_filename_component(_modal_real "${path}" REALPATH)
    _fullmag_windows_modal_path_within_prefix("${_modal_real}" "${prefix}" _modal_inside)
    if(NOT _modal_inside)
        _fullmag_windows_modal_fail("${role} escapes FULLMAG_FEM_DEPENDENCY_PREFIX: ${path}")
    endif()
endfunction()

function(_fullmag_windows_modal_select_config package_name prefix output_config output_directory)
    if(package_name STREQUAL "MPI")
        set(_modal_relative_locations
            "MPIConfig.cmake"
            "lib/cmake/mpi/MPIConfig.cmake"
            "lib/cmake/MPI/MPIConfig.cmake"
            "share/mpi/MPIConfig.cmake"
            "share/cmake/mpi/MPIConfig.cmake"
            "share/cmake/MPI/MPIConfig.cmake"
        )
    elseif(package_name STREQUAL "PETSc")
        set(_modal_relative_locations
            "PETScConfig.cmake"
            "lib/cmake/petsc/PETScConfig.cmake"
            "lib/cmake/PETSc/PETScConfig.cmake"
            "share/petsc/PETScConfig.cmake"
            "share/cmake/petsc/PETScConfig.cmake"
            "share/cmake/PETSc/PETScConfig.cmake"
        )
    elseif(package_name STREQUAL "SLEPc")
        set(_modal_relative_locations
            "SLEPcConfig.cmake"
            "lib/cmake/slepc/SLEPcConfig.cmake"
            "lib/cmake/SLEPc/SLEPcConfig.cmake"
            "share/slepc/SLEPcConfig.cmake"
            "share/cmake/slepc/SLEPcConfig.cmake"
            "share/cmake/SLEPc/SLEPcConfig.cmake"
        )
    else()
        _fullmag_windows_modal_fail("unsupported provider package ${package_name}")
    endif()

    set(_modal_configs "")
    set(_modal_config_keys "")
    foreach(_modal_relative IN LISTS _modal_relative_locations)
        set(_modal_candidate "${prefix}/${_modal_relative}")
        if(EXISTS "${_modal_candidate}" AND NOT IS_DIRECTORY "${_modal_candidate}")
            get_filename_component(_modal_config "${_modal_candidate}" REALPATH)
            _fullmag_windows_modal_path_within_prefix("${_modal_config}" "${prefix}" _modal_inside)
            if(NOT _modal_inside)
                _fullmag_windows_modal_fail("${package_name} config escapes the dependency prefix: ${_modal_candidate}")
            endif()
            file(TO_CMAKE_PATH "${_modal_config}" _modal_config_norm)
            string(TOLOWER "${_modal_config_norm}" _modal_config_key)
            list(FIND _modal_config_keys "${_modal_config_key}" _modal_seen_index)
            if(_modal_seen_index EQUAL -1)
                list(APPEND _modal_configs "${_modal_config}")
                list(APPEND _modal_config_keys "${_modal_config_key}")
            endif()
        endif()
    endforeach()
    list(LENGTH _modal_configs _modal_config_count)
    if(NOT _modal_config_count EQUAL 1)
        _fullmag_windows_modal_fail("${package_name} prefix must contain exactly one named ${package_name}Config.cmake; found ${_modal_config_count}")
    endif()
    list(GET _modal_configs 0 _modal_selected_config)
    get_filename_component(_modal_selected_directory "${_modal_selected_config}" DIRECTORY)
    _fullmag_windows_modal_append_unique(FULLMAG_WINDOWS_MODAL_RECEIPT_FILES "${_modal_selected_config}")
    _fullmag_windows_modal_append_unique(FULLMAG_WINDOWS_MODAL_RECEIPT_CONFIGS "${_modal_selected_config}")
    set(${output_config} "${_modal_selected_config}" PARENT_SCOPE)
    set(${output_directory} "${_modal_selected_directory}" PARENT_SCOPE)
endfunction()

function(_fullmag_windows_modal_verify_loaded_config package_name expected_config)
    set(_modal_config_variable "${package_name}_CONFIG")
    if(NOT DEFINED ${_modal_config_variable})
        _fullmag_windows_modal_fail("${package_name} did not expose ${_modal_config_variable}; module/default discovery is not accepted")
    endif()
    set(_modal_loaded_config "${${_modal_config_variable}}")
    if(NOT EXISTS "${_modal_loaded_config}")
        _fullmag_windows_modal_fail("${package_name} loaded config does not exist: ${_modal_loaded_config}")
    endif()
    get_filename_component(_modal_loaded_real "${_modal_loaded_config}" REALPATH)
    file(TO_CMAKE_PATH "${_modal_loaded_real}" _modal_loaded_norm)
    file(TO_CMAKE_PATH "${expected_config}" _modal_expected_norm)
    string(TOLOWER "${_modal_loaded_norm}" _modal_loaded_lower)
    string(TOLOWER "${_modal_expected_norm}" _modal_expected_lower)
    if(NOT _modal_loaded_lower STREQUAL _modal_expected_lower)
        _fullmag_windows_modal_fail("${package_name} discovery was redirected outside the pinned config: ${_modal_loaded_config}")
    endif()
endfunction()

function(_fullmag_windows_modal_find_package package_name config_file config_directory)
    set(_modal_dir_variable "${package_name}_DIR")
    set(_modal_config_variable "${package_name}_CONFIG")
    # Replace stale cache/environment values with the selected directory. This
    # value is deliberately pinned so MFEM's find_dependency(MPI) reuses it.
    unset(${_modal_dir_variable} CACHE)
    unset(${_modal_dir_variable})
    unset(${_modal_config_variable} CACHE)
    unset(${_modal_config_variable})
    set(${_modal_dir_variable} "${config_directory}" CACHE PATH "Pinned Fullmag Windows ${package_name} provider directory" FORCE)
    set(${_modal_dir_variable} "${config_directory}")
    find_package(${package_name} CONFIG REQUIRED
        PATHS "${config_directory}"
        NO_DEFAULT_PATH
        NO_CMAKE_PATH
        NO_CMAKE_ENVIRONMENT_PATH
        NO_SYSTEM_ENVIRONMENT_PATH
        NO_CMAKE_SYSTEM_PATH
        NO_CMAKE_PACKAGE_REGISTRY
        NO_CMAKE_SYSTEM_PACKAGE_REGISTRY
    )
    _fullmag_windows_modal_verify_loaded_config("${package_name}" "${config_file}")
    _fullmag_windows_modal_collect_config_receipt("${FULLMAG_WINDOWS_MODAL_PROVIDER_PREFIX}")
    string(TOUPPER "${package_name}" _modal_package_upper)
    set(FULLMAG_WINDOWS_MODAL_${_modal_package_upper}_LOADED_CONFIG "${config_file}" CACHE INTERNAL "" FORCE)
endfunction()

function(_fullmag_windows_modal_collect_config_receipt prefix)
    # Config packages loaded by find_dependency() are often scoped to the
    # current find_package call. Capture their concrete paths while that scope
    # is still visible, so the packager can hash transitive adapters too.
    get_cmake_property(_modal_variables VARIABLES)
    foreach(_modal_variable IN LISTS _modal_variables)
        if(_modal_variable MATCHES "^FULLMAG_WINDOWS_MODAL_")
            continue()
        endif()
        string(TOUPPER "${_modal_variable}" _modal_variable_upper)
        if(NOT _modal_variable_upper MATCHES "(MPI|PETSC|SLEPC|HYPRE|CEED|MFEM).*_CONFIG$")
            continue()
        endif()
        set(_modal_value "${${_modal_variable}}")
        if(NOT _modal_value OR _modal_value MATCHES "-NOTFOUND$")
            continue()
        endif()
        foreach(_modal_candidate IN LISTS _modal_value)
            if(EXISTS "${_modal_candidate}" AND NOT IS_DIRECTORY "${_modal_candidate}")
                get_filename_component(_modal_real "${_modal_candidate}" REALPATH)
                _fullmag_windows_modal_path_within_prefix("${_modal_real}" "${prefix}" _modal_inside)
                if(NOT _modal_inside)
                    _fullmag_windows_modal_fail("transitive provider config escapes FULLMAG_FEM_DEPENDENCY_PREFIX: ${_modal_candidate}")
                endif()
                _fullmag_windows_modal_append_unique(FULLMAG_WINDOWS_MODAL_RECEIPT_FILES "${_modal_real}")
                _fullmag_windows_modal_append_unique(FULLMAG_WINDOWS_MODAL_RECEIPT_CONFIGS "${_modal_real}")
            endif()
        endforeach()
    endforeach()
endfunction()

function(_fullmag_windows_modal_verify_recorded_config package_name expected_config)
    string(TOUPPER "${package_name}" _modal_package_upper)
    set(_modal_recorded_variable "FULLMAG_WINDOWS_MODAL_${_modal_package_upper}_LOADED_CONFIG")
    if(NOT DEFINED ${_modal_recorded_variable})
        _fullmag_windows_modal_fail("${package_name} provider was not loaded by the pinned resolver")
    endif()
    file(TO_CMAKE_PATH "${${_modal_recorded_variable}}" _modal_recorded_norm)
    file(TO_CMAKE_PATH "${expected_config}" _modal_expected_norm)
    string(TOLOWER "${_modal_recorded_norm}" _modal_recorded_lower)
    string(TOLOWER "${_modal_expected_norm}" _modal_expected_lower)
    if(NOT _modal_recorded_lower STREQUAL _modal_expected_lower)
        _fullmag_windows_modal_fail("${package_name} recorded config changed after pinned discovery")
    endif()
endfunction()

function(_fullmag_windows_modal_validate_link_item target_name link_item prefix role)
    if(link_item STREQUAL "" OR link_item STREQUAL "debug" OR link_item STREQUAL "optimized" OR link_item STREQUAL "general")
        return()
    endif()
    if(link_item MATCHES "^\\$<")
        _fullmag_windows_modal_fail("${role} on ${target_name} contains an unresolved generator expression: ${link_item}")
    endif()
    if(TARGET "${link_item}")
        _fullmag_windows_modal_validate_target("${link_item}" "${prefix}")
        return()
    endif()
    if(IS_ABSOLUTE "${link_item}")
        get_filename_component(_modal_link_extension "${link_item}" EXT)
        string(TOLOWER "${_modal_link_extension}" _modal_link_extension_lower)
        if(_modal_link_extension_lower STREQUAL ".lib")
            _fullmag_windows_modal_require_file("${link_item}" "${prefix}" "${role} link input" "lib" _modal_link_real)
        elseif(_modal_link_extension_lower STREQUAL ".dll")
            _fullmag_windows_modal_require_file("${link_item}" "${prefix}" "${role} link input" "dll" _modal_link_real)
        else()
            _fullmag_windows_modal_fail("${role} on ${target_name} has an unsupported absolute link input: ${link_item}")
        endif()
        return()
    endif()
    string(TOLOWER "${link_item}" _modal_bare_link_lower)
    if(_modal_bare_link_lower MATCHES "(^|[/\\\\])(mpicc|mpicxx|mpifort|mpiexec|link)(\\.exe)?$" OR
       _modal_bare_link_lower MATCHES "(petsc|slepc|hypre|libceed|msmpi|mpich|openmpi)")
        _fullmag_windows_modal_fail("${role} on ${target_name} uses an ambient/provider bare link or compiler wrapper: ${link_item}")
    endif()
    set(_modal_system_libraries
        kernel32 kernel32.lib user32 user32.lib advapi32 advapi32.lib ws2_32 ws2_32.lib
        ole32 ole32.lib oleaut32 oleaut32.lib uuid uuid.lib gdi32 gdi32.lib shell32 shell32.lib
        comdlg32 comdlg32.lib version version.lib shlwapi shlwapi.lib setupapi setupapi.lib
        iphlpapi iphlpapi.lib psapi psapi.lib
    )
    list(FIND _modal_system_libraries "${_modal_bare_link_lower}" _modal_system_index)
    if(NOT _modal_system_index EQUAL -1)
        return()
    endif()
    _fullmag_windows_modal_fail("${role} on ${target_name} must reference an imported target or a prefix library, got '${link_item}'")
endfunction()

function(_fullmag_windows_modal_validate_link_items target_name prefix role)
    foreach(_modal_link_property IN ITEMS INTERFACE_LINK_LIBRARIES LINK_INTERFACE_LIBRARIES)
        get_target_property(_modal_links "${target_name}" "${_modal_link_property}")
        if(_modal_links AND NOT _modal_links MATCHES "-NOTFOUND$")
            foreach(_modal_link IN LISTS _modal_links)
                _fullmag_windows_modal_validate_link_item("${target_name}" "${_modal_link}" "${prefix}" "${role} ${_modal_link_property}")
            endforeach()
        endif()
    endforeach()
    string(TOUPPER "${CMAKE_BUILD_TYPE}" _modal_config_upper)
    foreach(_modal_link_property IN ITEMS
        "IMPORTED_LINK_INTERFACE_LIBRARIES_${_modal_config_upper}"
        IMPORTED_LINK_INTERFACE_LIBRARIES_NOCONFIG
        IMPORTED_LINK_INTERFACE_LIBRARIES
    )
        get_target_property(_modal_links "${target_name}" "${_modal_link_property}")
        if(_modal_links AND NOT _modal_links MATCHES "-NOTFOUND$")
            foreach(_modal_link IN LISTS _modal_links)
                _fullmag_windows_modal_validate_link_item("${target_name}" "${_modal_link}" "${prefix}" "${role} ${_modal_link_property}")
            endforeach()
        endif()
    endforeach()
endfunction()

function(_fullmag_windows_modal_validate_interface_property target_name prefix property_name role)
    get_target_property(_modal_values "${target_name}" "${property_name}")
    if(NOT _modal_values OR _modal_values MATCHES "-NOTFOUND$")
        return()
    endif()
    foreach(_modal_value IN LISTS _modal_values)
        if(_modal_value MATCHES "^\\$<")
            _fullmag_windows_modal_fail("${role} on ${target_name} contains an unresolved generator expression: ${_modal_value}")
        endif()
        string(TOLOWER "${_modal_value}" _modal_value_lower)
        if(_modal_value_lower MATCHES "(mpicc|mpicxx|mpifort|mpiexec|link\\.exe)")
            _fullmag_windows_modal_fail("${role} on ${target_name} contains an ambient MPI/compiler wrapper: ${_modal_value}")
        endif()
        if(_modal_value_lower MATCHES "(defaultlib|wholearchive|libpath|(^|[,: ])-l)")
            _fullmag_windows_modal_fail("${role} on ${target_name} resolves a library or wrapper through an unpinned linker option: ${_modal_value}")
        endif()
        if(_modal_value MATCHES "^/LIBPATH:(.+)$")
            _fullmag_windows_modal_require_directory("${CMAKE_MATCH_1}" "${prefix}" "${role} library path")
        elseif(IS_ABSOLUTE "${_modal_value}")
            if(IS_DIRECTORY "${_modal_value}")
                _fullmag_windows_modal_require_directory("${_modal_value}" "${prefix}" "${role}")
            else()
                _fullmag_windows_modal_require_file("${_modal_value}" "${prefix}" "${role}" "lib" _modal_interface_file)
            endif()
        elseif(_modal_value MATCHES "[A-Za-z]:[/\\\\]" OR _modal_value MATCHES "(^|[; ])-[IL]" OR _modal_value MATCHES "(^|[; ])(/|\\\\)")
            _fullmag_windows_modal_fail("${role} on ${target_name} contains an unpinned path or linker option: ${_modal_value}")
        endif()
    endforeach()
endfunction()

function(_fullmag_windows_modal_validate_config_mapping target_name)
    foreach(_modal_profile IN ITEMS Release Debug)
        string(TOUPPER "${_modal_profile}" _modal_profile_upper)
        get_property(_modal_mapping_set TARGET "${target_name}" PROPERTY "MAP_IMPORTED_CONFIG_${_modal_profile_upper}" SET)
        if(_modal_mapping_set)
            get_target_property(_modal_mapping "${target_name}" "MAP_IMPORTED_CONFIG_${_modal_profile_upper}")
            list(LENGTH _modal_mapping _modal_mapping_length)
            string(TOUPPER "${_modal_mapping}" _modal_mapping_upper)
            if(NOT _modal_mapping_length EQUAL 1 OR NOT _modal_mapping_upper STREQUAL _modal_profile_upper)
                _fullmag_windows_modal_fail("${target_name} has a non-identical MAP_IMPORTED_CONFIG_${_modal_profile_upper} mapping; only ${_modal_profile} -> ${_modal_profile} is allowed")
            endif()
        endif()
    endforeach()
endfunction()

function(_fullmag_windows_modal_validate_target target_name prefix)
    get_property(_modal_visited GLOBAL PROPERTY FULLMAG_WINDOWS_MODAL_VISITED_TARGETS)
    if(_modal_visited)
        list(FIND _modal_visited "${target_name}" _modal_visited_index)
        if(NOT _modal_visited_index EQUAL -1)
            return()
        endif()
    endif()
    if(NOT TARGET "${target_name}")
        _fullmag_windows_modal_fail("required imported target is missing: ${target_name}")
    endif()
    list(APPEND _modal_visited "${target_name}")
    set_property(GLOBAL PROPERTY FULLMAG_WINDOWS_MODAL_VISITED_TARGETS "${_modal_visited}")
    _fullmag_windows_modal_append_unique(FULLMAG_WINDOWS_MODAL_RECEIPT_TARGETS "${target_name}")

    get_target_property(_modal_imported "${target_name}" IMPORTED)
    if(NOT _modal_imported)
        _fullmag_windows_modal_fail("${target_name} must be an imported adapter target")
    endif()
    get_target_property(_modal_type "${target_name}" TYPE)
    string(TOUPPER "${CMAKE_BUILD_TYPE}" _modal_config_upper)
    _fullmag_windows_modal_validate_config_mapping("${target_name}")
    if(_modal_type STREQUAL "STATIC_LIBRARY")
        set(_modal_location "")
        foreach(_modal_property IN ITEMS
            "IMPORTED_LOCATION_${_modal_config_upper}" IMPORTED_LOCATION_NOCONFIG IMPORTED_LOCATION
        )
            get_target_property(_modal_candidate "${target_name}" "${_modal_property}")
            if(_modal_candidate AND NOT _modal_candidate MATCHES "-NOTFOUND$")
                set(_modal_location "${_modal_candidate}")
                break()
            endif()
        endforeach()
        if(NOT _modal_location)
            foreach(_modal_property IN ITEMS
                "IMPORTED_IMPLIB_${_modal_config_upper}" IMPORTED_IMPLIB_NOCONFIG IMPORTED_IMPLIB
            )
                get_target_property(_modal_candidate "${target_name}" "${_modal_property}")
                if(_modal_candidate AND NOT _modal_candidate MATCHES "-NOTFOUND$")
                    set(_modal_location "${_modal_candidate}")
                    break()
                endif()
            endforeach()
        endif()
        if(NOT _modal_location)
            _fullmag_windows_modal_fail("${target_name} has no ${CMAKE_BUILD_TYPE} static library")
        endif()
        _fullmag_windows_modal_require_file("${_modal_location}" "${prefix}" "${target_name} static library" "lib" _modal_real)
    elseif(_modal_type STREQUAL "SHARED_LIBRARY")
        set(_modal_runtime "")
        set(_modal_import_library "")
        foreach(_modal_property IN ITEMS
            "IMPORTED_LOCATION_${_modal_config_upper}" IMPORTED_LOCATION_NOCONFIG IMPORTED_LOCATION
        )
            get_target_property(_modal_candidate "${target_name}" "${_modal_property}")
            if(_modal_candidate AND NOT _modal_candidate MATCHES "-NOTFOUND$")
                set(_modal_runtime "${_modal_candidate}")
                break()
            endif()
        endforeach()
        foreach(_modal_property IN ITEMS
            "IMPORTED_IMPLIB_${_modal_config_upper}" IMPORTED_IMPLIB_NOCONFIG IMPORTED_IMPLIB
        )
            get_target_property(_modal_candidate "${target_name}" "${_modal_property}")
            if(_modal_candidate AND NOT _modal_candidate MATCHES "-NOTFOUND$")
                set(_modal_import_library "${_modal_candidate}")
                break()
            endif()
        endforeach()
        if(NOT _modal_runtime OR NOT _modal_import_library)
            _fullmag_windows_modal_fail("${target_name} requires both ${CMAKE_BUILD_TYPE} DLL and import library")
        endif()
        _fullmag_windows_modal_require_file("${_modal_runtime}" "${prefix}" "${target_name} shared runtime" "dll" _modal_runtime_real)
        _fullmag_windows_modal_require_file("${_modal_import_library}" "${prefix}" "${target_name} import library" "lib" _modal_import_real)
    elseif(_modal_type STREQUAL "INTERFACE_LIBRARY")
        get_target_property(_modal_interface_links "${target_name}" INTERFACE_LINK_LIBRARIES)
        set(_modal_has_concrete_interface_link FALSE)
        if(_modal_interface_links AND NOT _modal_interface_links MATCHES "-NOTFOUND$")
            foreach(_modal_interface_link IN LISTS _modal_interface_links)
                if(TARGET "${_modal_interface_link}" OR IS_ABSOLUTE "${_modal_interface_link}")
                    set(_modal_has_concrete_interface_link TRUE)
                endif()
            endforeach()
        endif()
        if(NOT _modal_has_concrete_interface_link)
            _fullmag_windows_modal_fail("${target_name} interface adapter must expose a concrete imported library target or prefix library")
        endif()
    else()
        _fullmag_windows_modal_fail("${target_name} must be an imported static, shared, or interface target; got ${_modal_type}")
    endif()

    _fullmag_windows_modal_validate_link_items("${target_name}" "${prefix}" "${target_name}")
    _fullmag_windows_modal_validate_interface_property("${target_name}" "${prefix}" INTERFACE_LINK_OPTIONS "${target_name} link options")
    _fullmag_windows_modal_validate_interface_property("${target_name}" "${prefix}" INTERFACE_INCLUDE_DIRECTORIES "${target_name} include directories")
    _fullmag_windows_modal_validate_interface_property("${target_name}" "${prefix}" INTERFACE_SYSTEM_INCLUDE_DIRECTORIES "${target_name} system include directories")
    _fullmag_windows_modal_validate_interface_property("${target_name}" "${prefix}" INTERFACE_COMPILE_OPTIONS "${target_name} compile options")
endfunction()

function(_fullmag_windows_modal_publish_receipt)
    get_property(_modal_files GLOBAL PROPERTY FULLMAG_WINDOWS_MODAL_RECEIPT_FILES)
    get_property(_modal_configs GLOBAL PROPERTY FULLMAG_WINDOWS_MODAL_RECEIPT_CONFIGS)
    get_property(_modal_targets GLOBAL PROPERTY FULLMAG_WINDOWS_MODAL_RECEIPT_TARGETS)
    list(SORT _modal_files)
    list(SORT _modal_configs)
    list(SORT _modal_targets)
    set(FULLMAG_WINDOWS_MODAL_PROVIDER_RECEIPT_SCHEMA "fullmag.windows.modal-provider.v1" CACHE INTERNAL "" FORCE)
    set(FULLMAG_WINDOWS_MODAL_PROVIDER_RECEIPT_FILES "${_modal_files}" CACHE INTERNAL "" FORCE)
    set(FULLMAG_WINDOWS_MODAL_PROVIDER_RECEIPT_CONFIGS "${_modal_configs}" CACHE INTERNAL "" FORCE)
    set(FULLMAG_WINDOWS_MODAL_PROVIDER_RECEIPT_TARGETS "${_modal_targets}" CACHE INTERNAL "" FORCE)
    set(FULLMAG_WINDOWS_MODAL_PROVIDER_PROFILE "${CMAKE_BUILD_TYPE}" CACHE INTERNAL "" FORCE)
endfunction()

function(_fullmag_windows_modal_reset_visited)
    set_property(GLOBAL PROPERTY FULLMAG_WINDOWS_MODAL_VISITED_TARGETS "")
endfunction()

function(fullmag_validate_windows_modal)
    if(NOT WIN32 OR NOT FULLMAG_FEM_WITH_SLEPC)
        return()
    endif()
    if(NOT DEFINED FULLMAG_WINDOWS_MODAL_PROVIDER_PREFIX OR NOT IS_DIRECTORY "${FULLMAG_WINDOWS_MODAL_PROVIDER_PREFIX}")
        _fullmag_windows_modal_fail("the pinned provider prefix is unavailable during post-validation")
    endif()
    if(NOT CMAKE_BUILD_TYPE MATCHES "^(Debug|Release)$")
        _fullmag_windows_modal_fail("CMAKE_BUILD_TYPE must remain Debug or Release during modal validation")
    endif()
    _fullmag_windows_modal_reset_visited()
    _fullmag_windows_modal_verify_recorded_config("MPI" "${FULLMAG_WINDOWS_MODAL_MPI_CONFIG}")
    _fullmag_windows_modal_verify_recorded_config("PETSc" "${FULLMAG_WINDOWS_MODAL_PETSC_CONFIG}")
    _fullmag_windows_modal_verify_recorded_config("SLEPc" "${FULLMAG_WINDOWS_MODAL_SLEPC_CONFIG}")
    _fullmag_windows_modal_validate_target("MPI::MPI_CXX" "${FULLMAG_WINDOWS_MODAL_PROVIDER_PREFIX}")
    _fullmag_windows_modal_validate_target("PETSC::petsc" "${FULLMAG_WINDOWS_MODAL_PROVIDER_PREFIX}")
    _fullmag_windows_modal_validate_target("SLEPC::slepc" "${FULLMAG_WINDOWS_MODAL_PROVIDER_PREFIX}")
    _fullmag_windows_modal_collect_config_receipt("${FULLMAG_WINDOWS_MODAL_PROVIDER_PREFIX}")
    _fullmag_windows_modal_publish_receipt()
endfunction()

function(fullmag_find_windows_modal)
    if(NOT WIN32 OR NOT FULLMAG_FEM_WITH_SLEPC)
        return()
    endif()
    if(NOT MSVC OR NOT CMAKE_SIZEOF_VOID_P EQUAL 8)
        _fullmag_windows_modal_fail("native modal providers require the x64 MSVC target")
    endif()
    if(NOT CMAKE_BUILD_TYPE MATCHES "^(Debug|Release)$")
        _fullmag_windows_modal_fail("native modal providers require CMAKE_BUILD_TYPE=Debug or Release")
    endif()
    if(NOT FULLMAG_FEM_DEPENDENCY_PREFIX OR NOT IS_DIRECTORY "${FULLMAG_FEM_DEPENDENCY_PREFIX}")
        _fullmag_windows_modal_fail("native modal providers require FULLMAG_FEM_DEPENDENCY_PREFIX")
    endif()
    get_filename_component(_modal_prefix "${FULLMAG_FEM_DEPENDENCY_PREFIX}" REALPATH)
    if(NOT IS_DIRECTORY "${_modal_prefix}")
        _fullmag_windows_modal_fail("the dependency prefix cannot be canonicalized")
    endif()
    set(_modal_redirect_guard "${_modal_prefix}/.fullmag-modal-no-package-redirects")
    if(EXISTS "${_modal_redirect_guard}")
        _fullmag_windows_modal_fail("redirect guard path must not exist: ${_modal_redirect_guard}")
    endif()
    # Keep this normal variable in the caller scope so MFEMConfig's
    # find_dependency(MPI) remains inside the same no-redirect boundary.
    set(CMAKE_FIND_PACKAGE_REDIRECTS_DIR "${_modal_redirect_guard}")
    set(CMAKE_FIND_PACKAGE_REDIRECTS_DIR "${_modal_redirect_guard}" PARENT_SCOPE)

    _fullmag_windows_modal_reset_receipt()
    set(FULLMAG_WINDOWS_MODAL_PROVIDER_PREFIX "${_modal_prefix}" CACHE INTERNAL "" FORCE)
    unset(MPI_DIR CACHE)
    unset(MPI_DIR)
    unset(PETSc_DIR CACHE)
    unset(PETSc_DIR)
    unset(SLEPc_DIR CACHE)
    unset(SLEPc_DIR)
    unset(MPI_ROOT CACHE)
    unset(MPI_ROOT)
    unset(PETSc_ROOT CACHE)
    unset(PETSc_ROOT)
    unset(SLEPc_ROOT CACHE)
    unset(SLEPc_ROOT)
    foreach(_modal_package IN ITEMS MPI PETSc SLEPc HYPRE CEED MFEM)
        unset(${_modal_package}_CONFIG CACHE)
        unset(${_modal_package}_CONFIG)
    endforeach()

    _fullmag_windows_modal_select_config("MPI" "${_modal_prefix}" _modal_mpi_config _modal_mpi_directory)
    _fullmag_windows_modal_select_config("PETSc" "${_modal_prefix}" _modal_petsc_config _modal_petsc_directory)
    _fullmag_windows_modal_select_config("SLEPc" "${_modal_prefix}" _modal_slepc_config _modal_slepc_directory)
    set(FULLMAG_WINDOWS_MODAL_MPI_CONFIG "${_modal_mpi_config}" CACHE INTERNAL "" FORCE)
    set(FULLMAG_WINDOWS_MODAL_PETSC_CONFIG "${_modal_petsc_config}" CACHE INTERNAL "" FORCE)
    set(FULLMAG_WINDOWS_MODAL_SLEPC_CONFIG "${_modal_slepc_config}" CACHE INTERNAL "" FORCE)

    # MPI is deliberately loaded first. The pinned MPI_DIR is then reused by
    # PETSc, SLEPc, and a later MFEM find_dependency(MPI).
    _fullmag_windows_modal_find_package("MPI" "${_modal_mpi_config}" "${_modal_mpi_directory}")
    _fullmag_windows_modal_find_package("PETSc" "${_modal_petsc_config}" "${_modal_petsc_directory}")
    _fullmag_windows_modal_find_package("SLEPc" "${_modal_slepc_config}" "${_modal_slepc_directory}")
    fullmag_validate_windows_modal()
endfunction()
