# Select the native Windows MFEM provider explicitly; preserve Linux discovery.
if(NOT DEFINED FULLMAG_FEM_DEPENDENCY_PREFIX)
    set(FULLMAG_FEM_DEPENDENCY_PREFIX "" CACHE PATH "Pinned native Windows FEM dependency prefix")
endif()

function(fullmag_check_windows_mfem_library target property extension prefix)
    string(TOUPPER "${CMAKE_BUILD_TYPE}" config)
    get_target_property(path ${target} "${property}_${config}")
    if(NOT path)
        get_target_property(path ${target} "${property}_NOCONFIG")
    endif()
    if(NOT path)
        get_target_property(path ${target} "${property}")
    endif()
    if(NOT path OR NOT EXISTS "${path}" OR IS_DIRECTORY "${path}")
        message(FATAL_ERROR "Windows MFEM ${property} is missing for ${CMAKE_BUILD_TYPE}")
    endif()
    get_filename_component(real_path "${path}" REALPATH)
    string(TOLOWER "${real_path}" lower_path)
    string(TOLOWER "${prefix}/" lower_prefix)
    string(FIND "${lower_path}" "${lower_prefix}" position)
    if(NOT position EQUAL 0 OR NOT lower_path MATCHES "\\.${extension}$")
        message(FATAL_ERROR "Windows MFEM ${property} must be a .${extension} inside the dependency prefix: ${path}")
    endif()
    file(SIZE "${real_path}" size)
    if(size EQUAL 0)
        message(FATAL_ERROR "Windows MFEM library is empty: ${path}")
    endif()
endfunction()

macro(fullmag_find_mfem)
    if(NOT WIN32)
        find_package(MFEM CONFIG REQUIRED)
    else()
        if(NOT MSVC OR NOT CMAKE_SIZEOF_VOID_P EQUAL 8)
            message(FATAL_ERROR "Native Windows FEM requires the x64 MSVC target")
        endif()
        if(NOT CMAKE_BUILD_TYPE)
            message(FATAL_ERROR "Windows FEM requires an explicit CMAKE_BUILD_TYPE for provider validation")
        endif()
        if(NOT FULLMAG_FEM_DEPENDENCY_PREFIX OR NOT IS_DIRECTORY "${FULLMAG_FEM_DEPENDENCY_PREFIX}")
            message(FATAL_ERROR "Native Windows FEM requires FULLMAG_FEM_DEPENDENCY_PREFIX")
        endif()
        get_filename_component(_fullmag_prefix "${FULLMAG_FEM_DEPENDENCY_PREFIX}" REALPATH)
        set(_fullmag_configs "")
        set(_fullmag_config_keys "")
        foreach(_fullmag_relative IN ITEMS "." "lib/cmake/mfem" "lib/cmake/MFEM" "share/mfem" "share/cmake/mfem")
            set(_fullmag_candidate "${_fullmag_prefix}/${_fullmag_relative}/MFEMConfig.cmake")
            if(EXISTS "${_fullmag_candidate}" AND NOT IS_DIRECTORY "${_fullmag_candidate}")
                get_filename_component(_fullmag_config "${_fullmag_candidate}" REALPATH)
                string(TOLOWER "${_fullmag_config}" _fullmag_config_key)
                if(NOT _fullmag_config_key IN_LIST _fullmag_config_keys)
                    list(APPEND _fullmag_configs "${_fullmag_config}")
                    list(APPEND _fullmag_config_keys "${_fullmag_config_key}")
                endif()
            endif()
        endforeach()
        list(LENGTH _fullmag_configs _fullmag_config_count)
        if(NOT _fullmag_config_count EQUAL 1)
            message(FATAL_ERROR "Windows FEM prefix must contain exactly one MFEMConfig.cmake; found ${_fullmag_config_count}")
        endif()
        list(GET _fullmag_configs 0 _fullmag_config)
        string(TOLOWER "${_fullmag_config}" _fullmag_config_lower)
        string(TOLOWER "${_fullmag_prefix}/" _fullmag_prefix_lower)
        string(FIND "${_fullmag_config_lower}" "${_fullmag_prefix_lower}" _fullmag_config_position)
        if(NOT _fullmag_config_position EQUAL 0)
            message(FATAL_ERROR "MFEM config escapes the Windows dependency prefix")
        endif()
        if(TARGET mfem OR TARGET MFEM::mfem)
            message(FATAL_ERROR "Windows MFEM target was already defined before pinned discovery")
        endif()
        # A normal variable overrides a stale MFEM_DIR cache/environment value.
        get_filename_component(MFEM_DIR "${_fullmag_config}" DIRECTORY)
        # Do not inherit capability claims from caller/cache variables.
        set(MFEM_USE_DOUBLE "")
        set(MFEM_USE_SINGLE "")
        set(MFEM_USE_CUDA "")
        find_package(MFEM CONFIG REQUIRED PATHS "${MFEM_DIR}" NO_DEFAULT_PATH)
        get_filename_component(_fullmag_loaded_config "${MFEM_CONFIG}" REALPATH)
        string(TOLOWER "${_fullmag_loaded_config}" _fullmag_loaded_config_lower)
        if(NOT _fullmag_loaded_config_lower STREQUAL _fullmag_config_lower)
            message(FATAL_ERROR "MFEM discovery was redirected outside the pinned config")
        endif()
        foreach(_fullmag_flag IN ITEMS MFEM_USE_DOUBLE MFEM_USE_SINGLE MFEM_USE_CUDA)
            string(TOUPPER "${${_fullmag_flag}}" _fullmag_flag_value)
            if(NOT _fullmag_flag_value MATCHES "^(ON|OFF|TRUE|FALSE|YES|NO|1|0)$")
                message(FATAL_ERROR "Pinned MFEM config must export a boolean ${_fullmag_flag}")
            endif()
        endforeach()
        if(NOT MFEM_USE_DOUBLE OR MFEM_USE_SINGLE)
            message(FATAL_ERROR "Windows MFEM provider must use double precision")
        endif()
        if((FULLMAG_ENABLE_CUDA AND NOT MFEM_USE_CUDA) OR
           (NOT FULLMAG_ENABLE_CUDA AND MFEM_USE_CUDA))
            message(FATAL_ERROR "Windows MFEM CUDA configuration differs from the requested build")
        endif()
        if(TARGET MFEM::mfem)
            set(_fullmag_mfem_target MFEM::mfem)
        elseif(TARGET mfem)
            set(_fullmag_mfem_target mfem)
        else()
            message(FATAL_ERROR "Pinned MFEM config did not define an MFEM target")
        endif()
        get_target_property(_fullmag_mfem_type ${_fullmag_mfem_target} TYPE)
        if(_fullmag_mfem_type STREQUAL "STATIC_LIBRARY")
            fullmag_check_windows_mfem_library(${_fullmag_mfem_target} IMPORTED_LOCATION lib "${_fullmag_prefix}")
        elseif(_fullmag_mfem_type STREQUAL "SHARED_LIBRARY")
            fullmag_check_windows_mfem_library(${_fullmag_mfem_target} IMPORTED_LOCATION dll "${_fullmag_prefix}")
            fullmag_check_windows_mfem_library(${_fullmag_mfem_target} IMPORTED_IMPLIB lib "${_fullmag_prefix}")
        else()
            message(FATAL_ERROR "Windows MFEM target must be an imported static or shared library")
        endif()
    endif()
endmacro()
