function(fullmag_require_fem_gpu_configuration)
    if(FULLMAG_FEM_REQUIRE_GPU)
        if(NOT FULLMAG_USE_MFEM_STACK)
            message(FATAL_ERROR "Required FEM GPU needs FULLMAG_USE_MFEM_STACK=ON")
        endif()
        if(NOT FULLMAG_ENABLE_CUDA)
            message(FATAL_ERROR "Required FEM GPU needs FULLMAG_ENABLE_CUDA=ON")
        endif()
        if(NOT FULLMAG_ENABLE_FEM_GPU)
            message(FATAL_ERROR "Required FEM GPU needs FULLMAG_ENABLE_FEM_GPU=ON")
        endif()
    endif()
endfunction()
