from __future__ import annotations

"""Temporary source specification for the production meshing documentation rewrite.

The file is consumed by the one-shot generator workflow and removed from the final
commit.  Each terminal page has its own numerical model, parameter scope, frontend
workflow, verification contract and implementation map.
"""


def row(name: str, unit: str, default: str, validation: str, effect: str) -> tuple[str, str, str, str, str]:
    return (name, unit, default, validation, effect)


FEM_BASE = [
    row("maximum_element_size / hmax", "m", "required or inherited", "finite and > 0", "Upper target for element size; local fields may request smaller cells."),
    row("minimum_element_size / hmin", "m", "unset", "finite, > 0 and <= hmax", "Lower clamp for curvature, interface and manually authored size fields."),
    row("maximum_element_growth_rate / growth_rate", "1", "preset-dependent", "finite and > 0", "Limits how abruptly neighboring size zones can coarsen."),
    row("calibrate_for", "1", "general_physics", "registered calibration name", "Selects a physics-aware family of mesh-size defaults."),
    row("size_preset", "1", "unset", "extremely_fine through extremely_coarse", "Populates growth, curvature and narrow-region defaults before explicit overrides."),
    row("size_factor", "1", "1", "finite and > 0", "Scales preset-derived target sizes without changing geometry."),
    row("curvature_factor", "1", "unset", "finite and > 0", "Controls curvature-driven refinement; smaller factors generally produce finer boundary sampling."),
    row("size_from_curvature", "points/circle", "0", "integer >= 0", "Legacy curvature control retained for direct Gmsh compatibility."),
    row("narrow_region_resolution", "1", "unset", "finite and > 0", "Requests additional resolution in thin gaps and narrow geometric features."),
    row("narrow_regions", "1", "0", "integer >= 0", "Legacy switch for Gmsh narrow-region sizing."),
    row("order", "1", "1", "integer >= 1; route may restrict to P1", "Polynomial order of the finite-element basis, distinct from cell topology."),
    row("algorithm_2d", "Gmsh ID", "6", "supported Gmsh 2-D algorithm", "Controls surface triangulation before volume construction."),
    row("algorithm_3d", "Gmsh ID", "1", "supported Gmsh 3-D algorithm", "Controls unstructured tetrahedralization where that route is used."),
    row("smoothing_steps", "passes", "1", "integer >= 0", "Relocates eligible nodes to improve quality without changing region markers."),
    row("optimize", "1", "unset", "supported optimizer name", "Requests a Gmsh quality optimizer; it does not replace a convergence study."),
    row("optimize_iters", "passes", "1", "integer >= 1", "Number of requested optimizer passes."),
    row("compute_quality", "1", "true in Control Room", "Boolean", "Creates global quality summaries and quality-gate evidence."),
    row("per_element_quality", "1", "true in Control Room", "Boolean", "Stores element-aligned SICN, gamma and volume arrays for diagnostics."),
    row("size_fields", "1", "[]", "supported field dictionaries", "Appends local box, distance, threshold or user-authored size controls."),
]

FEM_SWEEP = [
    row("mesh_strategy", "1", "auto", "auto, free_tetrahedral, thin_film_tetrahedral, swept_prism or swept_hex", "Selects the requested topology route."),
    row("through_thickness_elements", "layers", "route-dependent", "integer >= 1; exact prism UI currently capability-gated", "Number of volume-element layers through the sweep direction."),
    row("through_thickness_distribution", "1", "fixed/uniform", "fixed, linear or exponential in the object recipe", "Controls the positions of layer planes."),
    row("through_thickness_element_ratio", "1", "1", "finite and > 0", "Growth ratio for nonuniform through-thickness spacing."),
    row("through_thickness_symmetric", "1", "false", "Boolean", "Mirrors nonuniform grading around the mid-plane when supported."),
    row("sweep_face_meshing", "1", "strategy-derived", "triangular or quadrilateral", "Chooses the source-face topology: triangles for prisms, quads for hexes."),
    row("sweep_source", "1", "auto", "semantic selector or auto", "Identifies the source face of the sweep."),
    row("sweep_destination", "1", "auto", "semantic selector or auto", "Identifies the destination face paired with the source."),
    row("sweep_direction", "1", "auto", "auto, x, y or z", "Chooses or constrains the sweep axis."),
    row("topology", "1", "strategy-derived", "tetrahedral or prismatic", "Declares the expected realized topology and activates contradiction checks."),
    row("element_family", "1", "strategy-derived", "prism or hex", "Declares the requested swept volume-cell family."),
    row("transition_policy", "1", "reject", "pyramid_to_tetrahedra or reject", "Controls whether a conforming prism-to-tetrahedron transition shell is legal."),
    row("exact_layer_count", "1", "false", "Boolean", "Turns layer count into a strict realization certificate rather than a sizing hint."),
]

BOUNDARY_LAYER = [
    row("boundary_layer_count", "layers", "unset", "integer >= 1", "Number of extruded near-boundary layers."),
    row("boundary_layer_thickness", "m", "unset", "finite and > 0", "Target first-layer thickness in the current Python/Gmsh contract."),
    row("boundary_layer_stretching", "1", "unset", "finite and > 0", "Ratio between neighboring layer thicknesses."),
    row("boundary_layer_target_surface_tags", "1", "unset", "valid Gmsh surface tags", "Targets explicit surfaces after geometry synchronization."),
    row("boundary_layer_target_surface_selectors", "1", "unset", "resolved semantic selectors", "Targets stable authored surfaces without relying on volatile entity IDs."),
    row("boundary_layer_target_curve_tags/selectors", "1", "unset", "valid curves or resolvable selectors", "Constrains boundary-layer generation around selected curves."),
]

AIRBOX = [
    row("universe.mode", "1", "auto/manual", "supported universe mode", "Chooses geometry-derived or explicit exterior-domain bounds."),
    row("universe.size", "m", "unset", "three finite positive components", "Explicit outer-domain dimensions."),
    row("universe.center", "m", "geometry-derived", "three finite components", "Positions the exterior domain."),
    row("universe.padding", "m", "zero/unset", "three non-negative components", "Adds directional clearance around the magnetic bounding box."),
    row("padding_factor", "1", "3.0 in AirboxOptions", "finite and > 0", "Scales automatic airbox dimensions relative to magnetic bounds."),
    row("shape", "1", "bbox", "bbox or sphere when qualified", "Selects the requested outer-boundary geometry."),
    row("maximum_element_size / airbox_hmax", "m", "unset", "finite and > 0", "Far-field upper size target."),
    row("minimum_element_size / airbox_hmin", "m", "unset", "finite, > 0 and <= hmax", "Near-interface lower size clamp."),
    row("maximum_element_growth_rate / grading_ratio", "1", "1.3 in AirboxOptions", "finite and > 0", "Controls coarsening away from the magnet."),
    row("grading / grading_mode", "1", "geometric", "auto, geometric or linear", "Selects the distance-to-size law."),
    row("boundary_marker", "1", "99 in direct options", "positive integer distinct from region markers", "Identifies the outer boundary used by the field closure."),
    row("periodic_pair_ids", "1", "[]", "registered pair identifiers", "Carries periodic seam ownership into the generated facet contract."),
]

FDM_GRID = [
    row("FDM.cell / default_cell", "m", "required unless per_magnet is complete", "three finite positive components", "Native Cartesian cell spacing used by geometry voxelization and local operators."),
    row("FDM.per_magnet", "1", "unset", "mapping of nonempty names to FDMGrid", "Assigns object-owned native grids for multilayer/multi-magnet problems."),
    row("FDMGrid.cell", "m", "required", "three finite positive components", "Native spacing for one named ferromagnet."),
    row("grid origin", "m", "geometry/planner-derived", "finite and lattice-consistent", "Defines cell-center coordinates and phase alignment."),
    row("active/material mask", "1", "geometry-derived", "cardinality equals allocated grid", "Selects magnetic cells and region ownership."),
    row("boundary_correction", "1", "none/unset", "none, volume or full", "Selects staircasing correction for qualified local operators."),
    row("boundary_phi_floor", "1", "backend default", "0 < value < 1", "Prevents unstable division by very small magnetic volume fractions."),
    row("boundary_delta_min", "m", "backend default", "value >= 0", "Lower bound for effective boundary distances in full correction."),
]

FDM_DEMAG = [
    row("FDMDemag.strategy", "1", "auto", "auto, single_grid or multilayer_convolution", "Selects the nonlocal convolution-grid policy."),
    row("FDMDemag.mode", "1", "auto", "auto, two_d_stack or three_d", "Chooses stacked-2D or full-3D common-grid construction."),
    row("common_cells", "cells", "unset", "three positive integers; not with two_d_stack", "Explicit full-3D common convolution-grid dimensions."),
    row("common_cells_xy", "cells", "unset", "two positive integers; auto/two_d_stack only", "Explicit common in-plane dimensions."),
    row("common_cell_size", "m", "unset", "three positive components; exclusive with explicit counts", "Requests common-grid spacing instead of counts."),
    row("explain", "1", "true", "Boolean", "Requests a human-readable planner explanation before execution."),
]

SHARED = [
    row("interface_hmax_factor", "1", "0.5", "0 < value <= 1", "Refines shared material interfaces relative to the local object hmax."),
    row("enforce_conforming", "1", "true", "Boolean", "Requires shared vertices/facets across interfaces via OCC fragmentation."),
    row("airbox_hmax_factor", "1", "3.0", "finite and > 0", "Coarsens the exterior relative to the magnetic-domain target."),
    row("build_mode", "1", "strict/auto", "registered assembly mode", "Selects the qualified shared OCC/GEO construction path."),
    row("fallback_policy", "1", "strict reject", "registered policy", "Determines whether topology or shape degradation is legal."),
    row("region markers", "1", "assigned", "unique positive integers", "Bind cells to material and physical-region ownership."),
    row("interface/outer markers", "1", "assigned", "complete, non-colliding coverage", "Bind facets to coupling and outer-boundary semantics."),
]

PERIODIC = [
    row("periodic axes", "1", "none", "subset of x, y, z", "Chooses paired opposite boundaries."),
    row("pair tolerance", "m", "scale-derived", "positive and small relative to cell size", "Controls geometric matching of periodic nodes/facets."),
    row("image_counts", "images", "backend-specific", "non-negative integer triple", "Truncates FDM periodic demagnetization image sums."),
    row("Bloch wavevector k", "rad/m", "zero", "finite three-vector", "Applies phase-shifted periodicity in supported eigen/frequency-domain routes."),
    row("periodic_pair_ids", "1", "[]", "registered pair IDs", "Preserves seam identity through mesh extraction and solver lowering."),
    row("gauge policy", "1", "route-specific", "compatible with periodic scalar potential", "Removes the constant null mode of periodic Poisson systems."),
]

IMPORT_PARAMS = [
    row("source / mesh", "path", "required", "readable supported mesh file", "Selects the imported mesh asset."),
    row("coordinate_scale", "1", "1", "finite and > 0", "Converts source coordinates to SI metres when the file has no trusted unit metadata."),
    row("order", "1", "1", "supported imported element order", "Must match the solver's basis and connectivity contract."),
    row("region_map", "1", "file/author mapping", "complete and non-colliding", "Maps physical groups to Fullmag materials and regions."),
    row("boundary_map", "1", "file/author mapping", "complete for requested physics", "Maps facets to exterior, interface or periodic roles."),
    row("repair policy", "1", "reject", "explicit supported operation", "Controls whether orientation-only repair is allowed; unsupported topology is never truncated silently."),
    row("quality validation", "1", "enabled", "zero inverted/degenerate cells", "Validates Jacobians, volumes, markers and manifoldness before solver admission."),
]

GROUPS = {
    "fem": FEM_BASE,
    "sweep": FEM_SWEEP,
    "boundary_layer": BOUNDARY_LAYER,
    "airbox": AIRBOX,
    "fdm": FDM_GRID,
    "fdm_demag": FDM_DEMAG,
    "shared": SHARED,
    "periodic": PERIODIC,
    "import": IMPORT_PARAMS,
}


COMMON_IMPL_FEM = [
    ("Python authoring and validation", "packages/fullmag-py/src/fullmag/model/discretization.py", "FEM, PerObjectMeshRecipe, SweepDistribution, SweptMeshControls"),
    ("Gmsh options and realized mesh data", "packages/fullmag-py/src/fullmag/meshing/_gmsh_types.py", "MeshOptions, MeshData, MeshQualityReport, MeshRealizationReport"),
    ("Generic Gmsh generation", "packages/fullmag-py/src/fullmag/meshing/_gmsh_generators.py", "generate_mesh and size-field lowering"),
    ("Control Room object policy", "apps/control-room/src/modules/inspector/panels/ObjectMeshPolicyPanel.tsx", "ObjectMeshPolicyPanel"),
    ("Rust API mesh contracts", "crates/fullmag-api/src/schemas/mesh.rs", "mesh request/resource schemas"),
]

COMMON_IMPL_FDM = [
    ("Python FDM authoring", "packages/fullmag-py/src/fullmag/model/discretization.py", "FDM, FDMGrid, FDMDemag"),
    ("Analytic demag tensor", "crates/fullmag-fdm-demag/src/newell.rs", "Newell kernel generation"),
    ("CPU FFT realization", "crates/fullmag-engine/src/fdm/cpu/fft.rs", "open and periodic kernel spectra"),
    ("Study/grid authoring UI", "apps/control-room/src/modules/inspector/panels/StudyInspectorPanel.tsx", "StudyInspectorPanel"),
]


PAGES: dict[str, dict[str, object]] = {
    "index.md": {
        "title": "Meshing and spatial discretization",
        "scope": "A decision framework linking magnetic length scales, geometry error, discrete operators, realized topology, backend capability and convergence evidence.",
        "groups": ["fdm", "fem", "airbox", "shared"],
        "equations": [
            ("Smallest magnetic scale", r"\ell_{\mathrm{ex}}=\sqrt{2A/(\mu_0M_s^2)},\qquad \delta_{\mathrm{DW}}\approx\pi\sqrt{A/K_{\mathrm{eff}}}.", "The mesh must resolve the smallest active physical and geometric scale, not merely the exchange length."),
            ("Error budget", r"\varepsilon_Q\lesssim \varepsilon_{\mathrm{geometry}}+\varepsilon_{\mathrm{discretization}}+\varepsilon_{\mathrm{boundary}}+\varepsilon_{\mathrm{algebraic}}.", "Mesh refinement addresses only part of the total error; airbox and solver tolerances require separate studies."),
            ("Cost models", r"C_{\mathrm{FDM,demag}}=\mathcal O(N\log N),\qquad C_{\mathrm{FEM,assembly}}=\mathcal O(N_e).", "The fastest valid discretization depends on geometry, field realization and the requested observable."),
        ],
        "example": "general",
        "ui": ["Select the study backend and device before authoring mesh controls.", "For FDM, edit the structured grid at study level; for FEM, edit each object-owned policy and the Universe airbox policy separately.", "Apply policies, build, then inspect requested/effective/realized values and the immutable mesh revision.", "Reject stale resources, unsupported cell families, missing markers or unreported fallback before starting the solver."],
        "impl": COMMON_IMPL_FEM + COMMON_IMPL_FDM,
        "accept": ["At least three controlled resolutions are compared.", "Geometry, mesh and solver revisions are recorded.", "Energy, field, switching or modal observables satisfy the declared tolerance.", "Changing airbox extent and algebraic tolerance does not dominate the reported mesh trend."],
        "fail": ["Choosing h from a single rule of thumb and omitting convergence.", "Treating a UI label as proof of realized topology.", "Reusing a mesh after geometry or object-policy edits.", "Comparing FDM and FEM without separating geometry and boundary-condition errors."],
        "refs": ["Abert, EPJ B 92, 120 (2019), doi:10.1140/epjb/e2019-90599-6", "Geuzaine and Remacle, IJNME 79, 1309 (2009), doi:10.1002/nme.2579"],
    },
    "fdm-grids.md": {
        "title": "FDM Cartesian grids",
        "scope": "Cell-centred Cartesian discretization, region masks, Nyquist limits, geometry voxelization, local stencils and FFT-demagnetization grid identity.",
        "groups": ["fdm", "fdm_demag"],
        "equations": [
            ("Cell centres and volume", r"\mathbf r_{ijk}=\mathbf r_0+((i+\tfrac12)\Delta x,(j+\tfrac12)\Delta y,(k+\tfrac12)\Delta z),\quad V_c=\Delta x\Delta y\Delta z.", "Origin and spacing define both geometry sampling and discrete operator phase alignment."),
            ("Resolvable wavevector", r"|k_q|\le k_{\mathrm N,q}=\pi/\Delta q.", "A mode close to Nyquist is poorly resolved even though it is formally representable."),
            ("Anisotropic exchange stencil", r"\nabla_h^2m_{ijk}=\sum_{q=x,y,z}(m_{i+e_q}-2m_i+m_{i-e_q})/\Delta q^2.", "Anisotropic cells enter local operators through direction-specific squared spacings."),
        ],
        "example": "fdm",
        "ui": ["Open Study → Discretization and choose FDM.", "Enter dx, dy and dz in SI units; verify the derived cell counts and allocated extent.", "Inspect active-cell and region-mask previews at curved boundaries.", "For multiple magnets, inspect the planner explanation for native and common convolution grids."],
        "impl": COMMON_IMPL_FDM,
        "accept": ["Every active magnetic feature spans enough cells in each relevant direction.", "The grid origin and dimensions are stable across compared runs.", "FFT padding/common-grid provenance is recorded.", "The target mode spectrum is separated from directional Nyquist limits."],
        "fail": ["Using one cell through thickness while interpreting nonuniform thickness modes.", "Changing the grid origin between convergence runs.", "Assuming volume correction repairs an under-resolved geometry.", "Comparing different common-grid interpolation policies as pure h-refinement."],
        "refs": ["Newell, Williams and Dunlop, JGR 98, 9551 (1993)", "Abert, EPJ B 92, 120 (2019)"],
    },
    "airbox.md": {
        "title": "FEM airbox meshing",
        "scope": "Finite exterior-domain approximation for scalar-potential magnetostatics, including geometry, interface resolution, far-field grading and outer-boundary convergence.",
        "groups": ["airbox", "fem", "shared"],
        "equations": [
            ("Exterior-domain Poisson problem", r"\nabla\cdot(-\nabla u+\mathbf M)=0\ \text{in }\Omega_m\cup\Omega_a,\qquad \mathbf H_d=-\nabla u.", "The airbox is part of the field solve, not a graphical padding object."),
            ("Robin closure", r"\partial_nu+\beta u=0\quad\text{on }\Gamma_{\mathrm{out}}.", "The closure and outer distance jointly control truncation error."),
            ("Independent convergence", r"Q=Q(h_m,h_a,R_a,\tau_{\mathrm{lin}}).", "Magnet mesh, air mesh, outer radius and linear tolerance must be varied independently."),
        ],
        "example": "airbox",
        "ui": ["Select Universe → Airbox Geometry and define automatic padding or explicit size/center.", "Select Universe → Airbox Mesh and set near-interface/far-field sizes plus grading.", "Select the demag interaction and choose its outer-boundary closure separately.", "Build the shared domain and verify the air marker, magnetic-air interface and outer marker."],
        "impl": COMMON_IMPL_FEM + [("Airbox geometry", "packages/fullmag-py/src/fullmag/meshing/_gmsh_airbox.py", "airbox construction and grading"), ("OCC shared geometry", "packages/fullmag-py/src/fullmag/meshing/_gmsh_occ.py", "fragmented magnetic/air domain")],
        "accept": ["All six magnetic-to-outer-boundary clearances are reported.", "Magnetic-air interfaces are conforming and completely marked.", "Moving the outer boundary changes the target observable below tolerance.", "Refining the air mesh at fixed geometry no longer changes the result materially."],
        "fail": ["Refining a too-small airbox and mistaking convergence to the truncated problem for open-space convergence.", "Using the outer boundary marker to infer the physical closure.", "Allowing a coarse first air layer next to a fine magnet boundary.", "Omitting the scalar-potential gauge/null-space policy."],
        "refs": ["Fredkin and Koehler, IEEE Trans. Magn. 26, 415 (1990)", "Gmsh reference manual, fields and OCC fragments"],
    },
    "fem-shared-domain.md": {
        "title": "FEM shared-domain construction",
        "scope": "One conforming magnetic-plus-air mesh with deterministic region/facet ownership, shared traces, assembly provenance and strict fallback reporting.",
        "groups": ["fem", "shared", "airbox"],
        "equations": [
            ("Partition", r"\overline\Omega=\bigcup_r\overline{\Omega_r},\qquad \Omega_r\cap\Omega_s=\varnothing\ (r\ne s).", "Each volume cell belongs to one physical role while interfaces are represented once with explicit adjacency."),
            ("Conforming trace", r"u_h|_{\Gamma_{rs}}^{(r)}=u_h|_{\Gamma_{rs}}^{(s)}.", "Shared nodal traces are required by the ordinary H1 conforming route."),
            ("Flux balance", r"\mathbf n_r\cdot\mathbf q_r+\mathbf n_s\cdot\mathbf q_s=0\quad\text{on }\Gamma_{rs}.", "Interface orientation and marker ownership enter weak-form assembly."),
        ],
        "example": "shared",
        "ui": ["Author object mesh policies first, then select Universe → Shared Domain.", "Keep conforming assembly enabled for coupled H1 operators.", "Build and inspect region counts, interface adjacency and outer-boundary coverage.", "Open History to compare requested build mode with the actual OCC/GEO strategy and any fallback reason."],
        "impl": COMMON_IMPL_FEM + [("Shared OCC assembly", "packages/fullmag-py/src/fullmag/meshing/_gmsh_occ.py", "fragment and physical-group assignment"), ("Build report", "packages/fullmag-py/src/fullmag/meshing/mesh_build_report.py", "requested/effective/realized provenance")],
        "accept": ["Every cell and required facet has exactly one valid semantic owner.", "No unmatched, orphan, coincident or nonmanifold interface facets remain.", "Material volumes agree with authored geometry within tolerance.", "The solver capability covers every realized cell family."],
        "fail": ["Concatenating independently meshed bodies and assuming coincident coordinates imply conformity.", "Losing material markers during OCC fragmentation.", "Accepting a spherical-to-box airbox change without degradation provenance.", "Passing mixed topology to a tetra-only operator."],
        "refs": ["Ciarlet, The Finite Element Method for Elliptic Problems", "Geuzaine and Remacle, IJNME 79, 1309 (2009)"],
    },
    "refinement.md": {
        "title": "Mesh refinement and convergence",
        "scope": "Controlled h-, p-, layer-, interface- and airbox-refinement studies tied to observable error rather than element count alone.",
        "groups": ["fem", "fdm", "airbox"],
        "equations": [
            ("Relative change", r"\varepsilon_h=|Q_h-Q_{h/\rho}|/\max(|Q_{h/\rho}|,Q_{\mathrm{scale}}).", "A documented scale is required when the observable can cross zero."),
            ("Observed order", r"p_{\mathrm{obs}}=\log(|Q_h-Q_{h/\rho}|/|Q_{h/\rho}-Q_{h/\rho^2}|)/\log\rho.", "The estimate is meaningful only in an asymptotic regime with unchanged modeling choices."),
            ("Mode overlap", r"\eta=|\langle\psi_h,M\psi_{h/\rho}\rangle|/(\|\psi_h\|_M\|\psi_{h/\rho}\|_M).", "Eigenmodes must be compared with a phase-invariant, mass-weighted metric."),
        ],
        "example": "refinement",
        "ui": ["Duplicate the study as a parameter sweep rather than editing one run in place.", "Change only one resolution family per sweep: cell size, hmax, layer count, airbox size or tolerance.", "Pin geometry, materials, initial state, sampling and solver tolerances.", "Use Results → Convergence to compare scalar observables and field/mode norms."],
        "impl": COMMON_IMPL_FEM + COMMON_IMPL_FDM + [("Mesh statistics", "packages/fullmag-py/src/fullmag/meshing/_gmsh_types.py", "MeshStatisticsReport")],
        "accept": ["At least three ordered resolutions are present.", "The refinement ratio is reported.", "Observed values are in a monotone/asymptotic regime or nonmonotonicity is explained.", "Field or mode comparisons use a common physical domain and norm."],
        "fail": ["Changing mesh, timestep and airbox simultaneously.", "Using element count as the convergence observable.", "Comparing eigenmode indices without tracking branch identity.", "Claiming convergence from two nearly identical meshes."],
        "refs": ["Roache, Verification and Validation in Computational Science and Engineering", "Babuška and Strouboulis, The Finite Element Method and Its Reliability"],
    },
    "swept-meshes.md": {
        "title": "Swept and layered FEM meshes",
        "scope": "Source-face discretization, layer-plane distributions, prism/hex mappings, exact-layer certification and conforming transitions to surrounding tetrahedra.",
        "groups": ["fem", "sweep", "shared"],
        "equations": [
            ("Uniform planes", r"z_j=z_0+j t/N,\qquad j=0,\ldots,N.", "N volume layers require N+1 strictly ordered node planes."),
            ("Geometric thicknesses", r"d_j=d_0r^j,\qquad d_0=t(1-r)/(1-r^N).", "Nonuniform grading changes the location of degrees of freedom and is not compatible with the current exact-uniform certificate."),
            ("Layer aspect ratio", r"\mathrm{AR}_j\sim h_{\parallel}/d_j.", "A swept topology avoids arbitrary tetrahedral diagonals but does not make extreme aspect ratios harmless."),
        ],
        "example": "swept",
        "ui": ["Select the object's Mesh node and open Thin-Film Sweep Strategy.", "Choose source-face topology, layer count/distribution and sweep direction.", "Enable exact layers only for a qualified uniform route.", "Inspect realized layer planes, cell-family counts and transition-facet conformity."],
        "impl": COMMON_IMPL_FEM + [("Swept generator", "packages/fullmag-py/src/fullmag/meshing/_gmsh_swept.py", "generate_swept_mesh"), ("Mixed topology certificate", "packages/fullmag-py/src/fullmag/meshing/_gmsh_types.py", "MixedLayerTopologyCertificate")],
        "accept": ["Source and destination are topologically compatible.", "N requested layers produce N realized layers and N+1 planes when exact.", "All prism/hex Jacobians are positive.", "Transition cells preserve complete facet conformity."],
        "fail": ["Using auto sweep direction for a nearly isotropic body without checking the resolved axis.", "Calling a size hint an exact layer count.", "Interpreting swept hex as supported when only the authoring vocabulary exists.", "Ignoring through-thickness convergence of dynamic modes."],
        "refs": ["Gmsh reference manual, Extrude and Transfinite Mesh", "Knupp, Int. J. Numer. Meth. Eng. 48, 1165 (2000)"],
    },
    "fdm/index.md": {
        "title": "FDM meshing overview",
        "scope": "Authoring, resolving and validating structured magnetic grids, object-owned masks, periodicity and nonlocal common-grid plans.",
        "groups": ["fdm", "fdm_demag", "periodic"],
        "equations": [
            ("Allocated dimensions", r"N_q=\lceil L_q/\Delta q\rceil,\qquad L_q^{\mathrm{alloc}}=N_q\Delta q.", "The allocated box can exceed nominal geometry and must be included in provenance."),
            ("Discrete volume", r"V_m^h=\sum_{ijk}\phi_{ijk}\Delta x\Delta y\Delta z.", "Binary masks use phi in {0,1}; sub-cell policies use a qualified fractional realization."),
            ("FFT convolution", r"\mathbf H_d^h=\mathcal F^{-1}[\widehat{\mathsf N}^h\,\mathcal F(\mathbf M^h)].", "The demag kernel is tied to cell geometry, padding and periodic policy."),
        ],
        "example": "fdm",
        "ui": ["Set the default cell size in Study → FDM Grid.", "Inspect derived counts and allocated extent before building.", "Open each object mask to verify region ownership at boundaries.", "For multilayer demag, inspect the common-grid plan and transfer method."],
        "impl": COMMON_IMPL_FDM,
        "accept": ["Allocated dimensions and origin are recorded.", "Magnetic volume error is quantified.", "Boundary and periodic policies are explicit.", "The demag kernel fingerprint matches the realized grid."],
        "fail": ["Changing cell counts without checking the physical allocated extent.", "Mixing object-native grids without a declared nonlocal coupling policy.", "Assuming periodic local stencils imply periodic demag.", "Using a binary mask for a geometry whose boundary error dominates the observable."],
        "refs": ["Brown, Micromagnetics (1963)", "Newell et al., JGR 98, 9551 (1993)"],
    },
    "fdm/boundary-correction.md": {
        "title": "FDM boundary correction",
        "scope": "Qualified fractional-volume and effective-boundary-distance corrections for staircased Cartesian representations of curved magnetic surfaces.",
        "groups": ["fdm"],
        "equations": [
            ("Fractional volume", r"\phi_i=|C_i\cap\Omega_m|/|C_i|,\qquad 0\le\phi_i\le1.", "Volume correction changes weights but cannot reconstruct unresolved geometry."),
            ("Directed face fraction", r"f_{i\to j}=|F_{ij}\cap\Omega_m|/|F_{ij}|.", "A full correction needs direction-resolved geometry, not only cell occupancy."),
            ("Corrected normal distance", r"D_n m_i\approx(m_j-m_i)/\max(\delta_{ij},\delta_{\min}).", "The distance floor is a stability regularizer and must be reported."),
        ],
        "example": "fdm_boundary",
        "ui": ["Open Study → FDM Grid → Boundary Representation.", "Choose none, volume or full only when the selected backend/precision advertises it.", "Set phi floor and distance floor in SI units when overriding defaults.", "Inspect occupancy, directed faces and the count of clamped cells."],
        "impl": COMMON_IMPL_FDM + [("Boundary geometry diagnostics", "packages/fullmag-py/tests/_diag_fields.py", "fraction/face diagnostic fixtures")],
        "accept": ["Corrected magnetic volume approaches the CAD/reference volume.", "No NaN/Inf or excessive clamping occurs.", "A curved-geometry benchmark improves relative to the uncorrected grid.", "The same correction is used for all compared resolutions."],
        "fail": ["Treating phi floor as a physical material fraction.", "Enabling full correction on an unsupported FP32/device lane.", "Using correction instead of refining a one-cell feature.", "Applying asymmetric face data without checking conservation."],
        "refs": ["Rave, Hubert and Ramstöck, J. Magn. Magn. Mater. 183, 329 (1998)", "Abert, EPJ B 92, 120 (2019)"],
    },
    "fdm/multi-magnet-grids.md": {
        "title": "FDM multi-magnet and multilayer grids",
        "scope": "Object-native Cartesian grids coupled through an explicit common convolution grid with deterministic projection, restriction and conservation diagnostics.",
        "groups": ["fdm", "fdm_demag"],
        "equations": [
            ("Transfer to common grid", r"\mathbf M_c=\sum_r\mathcal P_{r\to c}\mathbf M_r,\qquad \mathbf H_r=\mathcal R_{c\to r}\mathbf H_c.", "Projection and restriction are part of the numerical method and must appear in provenance."),
            ("Moment consistency", r"\sum_c\mathbf M_cV_c\approx\sum_r\sum_i\mathbf M_{r,i}V_{r,i}.", "Transfer diagnostics should preserve the integrated magnetic moment within tolerance."),
            ("Common-grid Nyquist", r"k_{N,c,q}=\pi/\Delta q_c.", "The common grid must resolve the shortest wavelength that contributes to nonlocal coupling."),
        ],
        "example": "fdm_multi",
        "ui": ["Create native grids under each ferromagnet's Mesh child.", "Open Study → Demag Grid Policy and choose multilayer convolution.", "Select two_d_stack or three_d and author common counts/spacing if auto is insufficient.", "Inspect transfer conservation, common bounds and kernel cache identity."],
        "impl": COMMON_IMPL_FDM,
        "accept": ["Every magnet is completely contained in the common grid.", "Projection/restriction conservation error is reported.", "Common-grid spacing resolves the requested coupling spectrum.", "No silent fallback to a single native grid occurs."],
        "fail": ["Using incompatible origins without a defined transfer operator.", "Choosing common cells from the largest native spacing.", "Assuming two_d_stack represents arbitrary 3-D offsets.", "Comparing strategies without including interpolation error."],
        "refs": ["Newell et al., JGR 98, 9551 (1993)", "García-Cervera, J. Comput. Phys. 184, 37 (2003)"],
    },
    "fdm/periodic-grids.md": {
        "title": "FDM periodic grids",
        "scope": "Local stencil wrapping, geometry seam consistency, truncated-image demagnetization and the distinction between ordinary periodic and Bloch-phase boundary conditions.",
        "groups": ["fdm", "periodic"],
        "equations": [
            ("Ordinary periodicity", r"\mathbf m(\mathbf r+L_q\mathbf e_q)=\mathbf m(\mathbf r).", "Opposite cell faces share local-neighbor semantics."),
            ("Finite image sum", r"\mathbf H_d(\mathbf r)=\sum_{n=-N_q}^{N_q}\mathbf H_d^{(0)}(\mathbf r+nL_q\mathbf e_q).", "FDM image_counts defines a truncated periodic demag realization, not an infinite Ewald sum."),
            ("Bloch phase", r"\delta\mathbf m(\mathbf r+\mathbf L)=e^{-i\mathbf k\cdot\mathbf L}\delta\mathbf m(\mathbf r).", "Nonzero-k phase periodicity belongs to supported linearized/eigen routes and must not be emulated by ordinary wrapping."),
        ],
        "example": "fdm_periodic",
        "ui": ["Enable periodic axes in Study → Boundary Conditions.", "Verify opposite geometry/mask seams match cell-for-cell.", "Set demag image counts separately from local periodicity.", "For eigen studies, inspect the advertised Bloch/Floquet capability before entering k."],
        "impl": COMMON_IMPL_FDM,
        "accept": ["Opposite masks and material IDs match exactly.", "Local stencil and demag periodic policies are both explicit.", "Image-count convergence is demonstrated for the target observable.", "The reported k convention and units are rad/m."],
        "fail": ["Assuming image_counts=0 means infinite periodicity.", "Using a nonperiodic geometry across a wrapped seam.", "Mixing exp(+ikL) and exp(-ikL) conventions.", "Applying Bloch phase to a nonlinear time-domain field without a supported formulation."],
        "refs": ["Tewary, Phys. Rev. B 69, 094109 (2004)", "Kittel, Introduction to Solid State Physics, Bloch theorem"],
    },
    "fem/index.md": {
        "title": "FEM meshing overview",
        "scope": "Geometry-conforming finite-element spaces, cell mappings, marker semantics, object policies, shared domains and backend element-family admission.",
        "groups": ["fem", "shared", "airbox"],
        "equations": [
            ("Finite-element space", r"V_h=\{v_h\in H^1(\Omega):v_h|_K\in\mathcal P_p(K)\ \forall K\in\mathcal T_h\}.", "Topology and polynomial order jointly define the trial space."),
            ("Element mapping", r"\mathbf x=F_K(\boldsymbol\xi),\qquad J_K=\partial F_K/\partial\boldsymbol\xi.", "Positive, sufficiently conditioned Jacobians are mandatory."),
            ("Weak gradient term", r"a(u_h,v_h)=\sum_K\int_K c\,\nabla u_h\cdot\nabla v_h\,dV.", "Mesh quality affects both interpolation error and matrix conditioning."),
        ],
        "example": "fem",
        "ui": ["Choose FEM and a qualified device/precision in Study.", "Author object mesh policies under each object's Mesh node.", "Author Universe/Airbox and shared-domain policies independently.", "Build, inspect cell families/markers/quality, then verify solver capability admission."],
        "impl": COMMON_IMPL_FEM,
        "accept": ["All cell Jacobians are positive.", "Markers provide complete volume and boundary ownership.", "Requested order and topology match the realized report.", "The selected operator/device supports every realized family."],
        "fail": ["Confusing p-order with geometric element family.", "Accepting a visually smooth surface with inverted volume cells.", "Dropping boundary markers during conversion.", "Using a tetra-only quality threshold for prisms or pyramids without qualification."],
        "refs": ["Ciarlet, The Finite Element Method for Elliptic Problems", "Knupp, IJNME 48, 1165 (2000)"],
    },
    "fem/ferromagnet/index.md": {
        "title": "FEM ferromagnet meshing",
        "scope": "Magnetic-domain discretization for exchange, DMI, anisotropy, LLG dynamics and coupling to the exterior demagnetization domain.",
        "groups": ["fem", "sweep", "boundary_layer"],
        "equations": [
            ("Exchange energy", r"E_{ex,h}=\sum_K\int_K A\,\nabla\mathbf m_h:\nabla\mathbf m_h\,dV.", "Magnetic cells must resolve texture gradients and carry correct material markers."),
            ("Discrete normalization", r"\|\mathbf m_i\|=1\quad\text{at solver degrees of freedom, subject to the selected projection policy}.", "Badly conditioned cells amplify projection and time-integration error."),
            ("Interface ownership", r"\Gamma_{rs}=\partial\Omega_r\cap\partial\Omega_s.", "Each interface must distinguish material coupling from a free exterior surface."),
        ],
        "example": "fem",
        "ui": ["Select a ferromagnet's Mesh node.", "Choose free tetrahedral, thin-film tetrahedral or a qualified swept route.", "Configure local interface/edge/core fields and quality reporting.", "Build and verify magnetic marker, boundary roles and operator support."],
        "impl": COMMON_IMPL_FEM,
        "accept": ["The mesh resolves exchange/DMI/domain-wall scales.", "Magnetic volume and surface area agree with geometry.", "Material and boundary markers are complete.", "Dynamic observables converge under spatial refinement."],
        "fail": ["Using airbox hmax as the magnetic hmax.", "Omitting through-thickness resolution for nonuniform modes.", "Treating a touching body as exchange-coupled without an explicit model.", "Ignoring DMI boundary sensitivity."],
        "refs": ["Abert, EPJ B 92, 120 (2019)", "García-Cervera, J. Comput. Phys. 184, 37 (2003)"],
    },
    "fem/ferromagnet/free-tetrahedral.md": {
        "title": "Free tetrahedral ferromagnet mesh",
        "scope": "Unstructured tet4 generation for arbitrary CAD/STL magnetic bodies with curvature, narrow-region and local size-field controls.",
        "groups": ["fem"],
        "equations": [
            ("Linear tetrahedron", r"v_h|_K=\sum_{a=1}^{4}v_a\lambda_a,\qquad \sum_a\lambda_a=1.", "P1 tet4 fields use barycentric basis functions with constant element gradients."),
            ("Signed volume", r"V_K=\det[\mathbf x_2-\mathbf x_1,\mathbf x_3-\mathbf x_1,\mathbf x_4-\mathbf x_1]/6.", "V_K must be positive under the canonical node ordering."),
            ("Size transition", r"h(\mathbf x)=\min_s h_s(\mathbf x).", "Overlapping size fields resolve to the most restrictive target."),
        ],
        "example": "fem_free",
        "ui": ["Choose Free tetrahedral in Object Mesh Policy.", "Set global hmin/hmax, growth, curvature and narrow-region controls.", "Add distance/box fields only where physics or geometry requires them.", "Inspect worst elements by SICN, gamma and volume before solving."],
        "impl": COMMON_IMPL_FEM,
        "accept": ["Zero inverted and degenerate tetrahedra.", "Curved boundaries and narrow gaps meet the requested geometric tolerance.", "Worst-tail quality is reported, not only the mean.", "The target observable converges with hmax/hmin refinement."],
        "fail": ["Using optimizer passes to hide an under-resolved boundary.", "Applying a global fine hmax when a local field is sufficient.", "Accepting slivers because average quality is high.", "Changing Gmsh algorithm between convergence points without reporting it."],
        "refs": ["Geuzaine and Remacle, IJNME 79, 1309 (2009)", "Shewchuk, What Is a Good Linear Element? (2002)"],
    },
    "fem/ferromagnet/thin-film-tetrahedral.md": {
        "title": "Thin-film tetrahedral mesh",
        "scope": "Thickness-aware tetrahedralization used when an exact swept prism route is unavailable or unsuitable, with explicit layer-sampling diagnostics.",
        "groups": ["fem", "sweep"],
        "equations": [
            ("Nominal thickness sampling", r"N_t\approx\lceil t/h_\perp\rceil.", "This is a sizing estimate, not an exact topological certificate."),
            ("Thickness-mode wavelength", r"k_{z,n}\approx n\pi/t,\qquad \lambda_{z,n}=2t/n.", "A target thickness mode requires multiple degrees of freedom per half-wavelength."),
            ("Anisotropy of resolution", r"h_\perp\ll h_\parallel\ \text{may be required even for isotropic tetrahedra}.", "Unstructured tetrahedra can create variable layer sampling and diagonal bias."),
        ],
        "example": "fem_thin_tet",
        "ui": ["Choose Thin-film tetrahedral.", "Set through-thickness target elements as a sizing request and choose the resolved axis.", "Use a finer normal-direction target than the in-plane hmax when thickness physics requires it.", "Inspect actual node-plane distribution and minimum elements across thickness."],
        "impl": COMMON_IMPL_FEM,
        "accept": ["Every relevant cross-section has sufficient through-thickness sampling.", "No collapsed/sliver cells occur near top and bottom surfaces.", "Mode frequencies/profiles converge with thickness refinement.", "The report does not claim exact layers for a tetrahedral route."],
        "fail": ["Interpreting through_thickness_elements as exact for tetrahedra.", "Using one tetrahedron across thickness for a nonuniform dynamic mode.", "Comparing prism and tetra results without matching effective resolution.", "Ignoring top/bottom surface marker completeness."],
        "refs": ["Abert, EPJ B 92, 120 (2019)", "Gmsh reference manual, anisotropic size fields"],
    },
    "fem/ferromagnet/swept-prism.md": {
        "title": "Swept-prism ferromagnet mesh",
        "scope": "Strict P1 prism6 layers generated from triangular source faces, with exact plane certification and qualified pyramid5-to-tet4 transition shells.",
        "groups": ["fem", "sweep", "shared"],
        "equations": [
            ("Prism interpolation", r"\mathbf x(\xi,\eta,\zeta)=\sum_{a=1}^{6}N_a(\xi,\eta,\zeta)\mathbf x_a.", "The canonical prism6 node order couples corresponding source/destination triangle vertices."),
            ("Exact layer planes", r"z_j=z_0+j(z_N-z_0)/N,\quad j=0,\ldots,N.", "The certificate compares N+1 realized planes with these authored coordinates using scale-aware tolerances."),
            ("Ideal cell volume", r"V_{T,j}=A_Td_j.", "Positive mapped Jacobians are checked for every prism; ideal volume alone is insufficient for warped geometries."),
            ("Transition conformity", r"\partial K_{prism}^{quad}=\bigcup\partial K_{pyramid}^{quad},\qquad \partial K_{pyramid}^{tri}=\bigcup\partial K_{tet}^{tri}.", "Pyramid5 cells reconcile quadrilateral prism faces with triangular tetrahedral faces."),
        ],
        "example": "swept_prism",
        "ui": ["Select Object → Mesh → Thin-Film Sweep Strategy and choose Swept prism.", "Use triangular source faces, P1, prism family, exact layer count and pyramid-to-tetrahedra transition.", "Choose only layer counts advertised by mesh.exact_layer_count capability.", "After build, inspect N+1 planes, prism/pyramid/tet counts, marker coverage and the accepted mixed topology certificate."],
        "impl": COMMON_IMPL_FEM + [("Swept prism generation", "packages/fullmag-py/src/fullmag/meshing/_gmsh_swept.py", "generate_swept_mesh"), ("Mixed shared-domain certificate", "packages/fullmag-py/src/fullmag/meshing/_gmsh_types.py", "MixedLayerTopologyCertificate"), ("Mixed topology tests", "packages/fullmag-py/tests/test_mixed_element_meshing.py", "prism/pyramid/tet acceptance fixtures")],
        "accept": ["Requested and resolved axis/layer count/order are identical.", "N layers yield N+1 strictly ordered planes.", "Prism6 and pyramid5 Jacobians are positive and quality tails pass the qualified gate.", "Interface marker coverage is complete and all nonconforming/orphan counts are zero.", "Exchange, demag and dynamics converge with in-plane size and layer count."],
        "fail": ["Allowing a tetrahedral replacement inside the exact prism region.", "Using nonuniform distribution with exact_layer_count in the current strict helper.", "Selecting order > 1 on the qualified mixed-P1 route.", "Assuming source/destination faces are sweepable without checking topology.", "Passing prisms/pyramids to an operator that advertises tet4 only."],
        "refs": ["Gmsh reference manual, extrusion and element types", "Knupp, IJNME 48, 1165 (2000)", "Fullmag ADR 0021: native mixed P1 FEM topology"],
    },
    "fem/ferromagnet/swept-hex.md": {
        "title": "Swept-hexahedral ferromagnet mesh",
        "scope": "Hex8 authoring vocabulary, transfinite prerequisites, Jacobian requirements and the explicit boundary between schema support and qualified execution support.",
        "groups": ["fem", "sweep"],
        "equations": [
            ("Trilinear mapping", r"\mathbf x(\xi,\eta,\zeta)=\sum_{a=1}^{8}N_a(\xi,\eta,\zeta)\mathbf x_a.", "A positive Jacobian is required throughout the reference cube, not only at the centre."),
            ("Logical grid", r"N_{hex}=N_uN_vN_w.", "A true structured hex mesh requires compatible source/destination quad partitions."),
            ("Warping sensitivity", r"\kappa_J=\sigma_{max}(J)/\sigma_{min}(J).", "Strongly warped hexes can be poorly conditioned even with positive volume."),
        ],
        "example": "swept_hex",
        "ui": ["The option must remain disabled unless an executable swept_hex capability is advertised.", "When enabled in a future qualified route, require quadrilateral source faces, compatible transfinite counts and transition=reject unless a supported hex transition exists.", "Inspect resolved topology and per-cell Jacobian evidence.", "Do not substitute prisms/tetrahedra silently for a strict hex request."],
        "impl": COMMON_IMPL_FEM + [("Authoring contradiction checks", "packages/fullmag-py/src/fullmag/model/discretization.py", "PerObjectMeshRecipe hex validation")],
        "accept": ["Execution capability explicitly includes hex8 for every active operator/device.", "Source and destination quad meshes are one-to-one compatible.", "Jacobian and warping metrics pass a hex-specific gate.", "No unsupported transition is introduced."],
        "fail": ["Presenting schema vocabulary as production solver support.", "Using pyramid_to_tetrahedra with hex family.", "Generating recombined quads without deterministic correspondence.", "Applying tetrahedral quality thresholds to hexes."],
        "refs": ["Knupp, IJNME 48, 1165 (2000)", "Gmsh reference manual, transfinite and recombination"],
    },
    "fem/ferromagnet/boundary-layers.md": {
        "title": "FEM boundary-layer meshing",
        "scope": "Surface- and curve-targeted near-boundary extrusion with explicit first-layer thickness, stretching, total thickness and interaction-specific justification.",
        "groups": ["fem", "boundary_layer"],
        "equations": [
            ("Geometric layer sequence", r"d_j=d_0r^j,\qquad T_N=d_0(r^N-1)/(r-1).", "The current thickness key is interpreted as first-layer thickness; total thickness must be derived and reported."),
            ("Normal resolution", r"h_n\approx d_j,\qquad h_t\ \text{set by the surface mesh}.", "Boundary layers introduce deliberate anisotropy that must be supported by the operator and quality metrics."),
            ("Exchange-scale check", r"\max_j d_j\lesssim c\,\ell_{\mathrm{ex}}.", "The constant c is study-dependent and must be justified by convergence."),
        ],
        "example": "boundary_layer",
        "ui": ["Open Object Mesh Policy → Backend Mesh Parameters → Boundary Layers.", "Resolve semantic surface/curve selectors before build.", "Enter count, first thickness and stretching; review the derived total thickness.", "Inspect matched entities, realized widths and transition quality."],
        "impl": COMMON_IMPL_FEM + [("Boundary-layer options", "packages/fullmag-py/src/fullmag/meshing/_gmsh_types.py", "MeshOptions boundary_layer_* fields")],
        "accept": ["All requested selectors resolve exactly once or according to an explicit multiplicity rule.", "Realized layer count and thickness distribution match the request.", "No negative/near-zero Jacobians occur at layer termination.", "The scientific observable improves or remains converged relative to a suitable reference mesh."],
        "fail": ["Confusing first-layer thickness with total thickness.", "Applying layers to all surfaces when only a subset is physically relevant.", "Creating extreme anisotropy unsupported by the solver.", "Using volatile Gmsh tags instead of semantic selectors in persistent authoring."],
        "refs": ["Gmsh reference manual, BoundaryLayer field", "Knupp, IJNME 48, 1165 (2000)"],
    },
    "fem/ferromagnet/imported-mesh.md": {
        "title": "Imported FEM ferromagnet meshes",
        "scope": "Trusted ingestion of external tet4/prism6/pyramid5/hex8 meshes with SI scaling, canonical node ordering, marker maps and strict rejection of unsupported high-order connectivity.",
        "groups": ["import", "fem"],
        "equations": [
            ("Coordinate normalization", r"\mathbf x_{SI}=s\,\mathbf x_{file}.", "The scale factor is part of mesh identity and must never be guessed from visual extent."),
            ("Orientation check", r"\det J_K>\varepsilon_{vol}.", "Canonical reordering may repair orientation only when topology is known and connectivity remains complete."),
            ("Marker coverage", r"\bigcup_r\mathcal T_r=\mathcal T_h,\qquad \mathcal T_r\cap\mathcal T_s=\varnothing.", "Every volume cell must map to exactly one physical region."),
        ],
        "example": "imported",
        "ui": ["Select Object Mesh → Source → Imported mesh.", "Choose the file and explicit coordinate unit/scale.", "Map physical groups to materials, exterior boundaries, interfaces and periodic seams.", "Run validation before admission; inspect rejected element types and repair actions."],
        "impl": COMMON_IMPL_FEM + [("Canonical extraction", "packages/fullmag-py/src/fullmag/meshing/_gmsh_extraction.py", "linear element dispatch and node ordering"), ("Mesh asset IR", "crates/fullmag-ir/src/mesh_assets.rs", "persistent mesh asset contract")],
        "accept": ["Only supported linear families are present or a separately qualified high-order importer is used.", "SI bounds match the authored geometry.", "All markers and facet roles are complete.", "No inverted, degenerate, orphan or nonmanifold entities remain."],
        "fail": ["Truncating high-order connectivity to the first corner nodes.", "Inferring millimetres or nanometres from file size.", "Dropping physical groups during conversion.", "Using a surface-only mesh as a volume discretization."],
        "refs": ["Gmsh MSH file format reference", "VTK UnstructuredGrid cell-type reference"],
    },
    "fem/ferromagnet/mixed-elements.md": {
        "title": "Mixed-element FEM ferromagnet meshes",
        "scope": "Typed cell/facet blocks, canonical ordering, conforming prism-pyramid-tetrahedron interfaces and solver capability admission for mixed P1 meshes.",
        "groups": ["fem", "sweep", "shared"],
        "equations": [
            ("Typed partition", r"\mathcal T_h=\mathcal T_{tet4}\cup\mathcal T_{prism6}\cup\mathcal T_{pyramid5}\cup\mathcal T_{hex8}.", "Each cell family retains its own arity and canonical interpolation."),
            ("Facet incidence", r"n_f=1\ \text{on exterior},\qquad n_f=2\ \text{on conforming interior facets}.", "Unexpected incidence signals orphan or nonmanifold topology."),
            ("Family-wise quality", r"q_{p05}^{(f)}=\operatorname{percentile}_{5}\{q_K:K\in\mathcal T_f\}.", "Quality gates must be evaluated by family, not hidden in a global average."),
        ],
        "example": "mixed",
        "ui": ["Choose a qualified mixed topology route such as swept prism with pyramid transition.", "Build and open Quality → Cell families.", "Inspect counts, markers, Jacobian minima and worst-tail quality for each family.", "Verify every active operator/device capability lists the complete family set."],
        "impl": COMMON_IMPL_FEM + [("Typed block contract", "packages/fullmag-py/src/fullmag/meshing/_gmsh_types.py", "MeshCellBlockView, MeshFacetBlockView"), ("Mixed topology tests", "packages/fullmag-py/tests/test_mixed_element_meshing.py", "family and conformity qualification")],
        "accept": ["Cell/facet arities and canonical ordering are validated.", "Interior facet incidence is exactly two and exterior incidence exactly one.", "Family-wise Jacobian and quality tails pass qualified thresholds.", "Backend capability admits all families without conversion."],
        "fail": ["Flattening mixed connectivity into one rectangular array.", "Using one global quality mean.", "Converting pyramids to arbitrary tetrahedra after certification.", "Losing stable source ordinals during extraction."],
        "refs": ["Fullmag ADR 0021: native mixed P1 FEM topology", "VTK cell-type reference"],
    },
    "fem/airbox/index.md": {
        "title": "FEM airbox overview",
        "scope": "Exterior-domain ownership spanning geometry, graded mesh, boundary markers, closure, periodic alternatives and separate convergence controls.",
        "groups": ["airbox", "fem", "shared", "periodic"],
        "equations": [
            ("Domain split", r"\Omega=\Omega_m\cup\Omega_a,\qquad \Omega_m\cap\Omega_a=\varnothing.", "The air region has no magnetic material but carries scalar-potential degrees of freedom."),
            ("Open-space approximation", r"u(\mathbf r)=\mathcal O(1/r)\quad\text{as }r\to\infty.", "Finite boundaries approximate this decay through distance and closure choice."),
            ("Exterior degree count", r"N_a\sim\int_{\Omega_a}h(\mathbf x)^{-3}dV.", "Grading is essential to control cost while preserving interface accuracy."),
        ],
        "example": "airbox",
        "ui": ["Configure Airbox Geometry, Airbox Mesh and Boundary Closure as separate nodes.", "Build the shared domain only after object policies are applied.", "Inspect air volume, interface and outer marker scopes.", "Run airbox-size and grading convergence independently."],
        "impl": COMMON_IMPL_FEM + [("Airbox generation", "packages/fullmag-py/src/fullmag/meshing/_gmsh_airbox.py", "bbox/sphere and grading fields")],
        "accept": ["Air and magnetic roles are disjoint and complete.", "The outer marker is complete.", "Interface resolution is compatible with magnetic hmax.", "Truncation error is below the study tolerance."],
        "fail": ["Treating airbox geometry, mesh and closure as one setting.", "Coarsening immediately at the magnetic surface.", "Using ordinary open airbox for a periodic problem.", "Reporting only total node count."],
        "refs": ["Fredkin and Koehler, IEEE Trans. Magn. 26, 415 (1990)", "Gmsh reference manual, mesh fields"],
    },
    "fem/airbox/geometry.md": {
        "title": "FEM airbox geometry",
        "scope": "Automatic/explicit bounding boxes or qualified spheres, directional clearances, containment, shape degradation and geometry-owned outer boundaries.",
        "groups": ["airbox"],
        "equations": [
            ("Directional clearance", r"d_q^-=x_{m,q}^{min}-x_{a,q}^{min},\qquad d_q^+=x_{a,q}^{max}-x_{m,q}^{max}.", "All six clearances matter for displaced or asymmetric magnets."),
            ("Padding-factor intent", r"L_{a,q}=pL_{m,q}.", "The realized report is authoritative because clipping, centering and fallback can alter this nominal relation."),
            ("Containment", r"\overline{\Omega_m}\subset\Omega_a^{total}.", "Touching the outer boundary invalidates the intended exterior-domain separation."),
        ],
        "example": "airbox_geometry",
        "ui": ["Open Universe → Airbox Geometry.", "Choose automatic padding or explicit size and centre.", "Select bbox or sphere only when the current assembly mode supports the requested shape.", "Inspect realized bounds and all six clearances."],
        "impl": COMMON_IMPL_FEM + [("Airbox geometry", "packages/fullmag-py/src/fullmag/meshing/_gmsh_airbox.py", "AirboxOptions and geometry realization")],
        "accept": ["The magnetic geometry is strictly contained.", "Minimum clearance satisfies the truncation study design.", "Requested and actual shape match or degradation is explicitly accepted.", "Bounds and units are recorded in SI."],
        "fail": ["Using total airbox volume instead of minimum clearance.", "Assuming a sphere survives every shared-domain fallback.", "Allowing the magnet to touch the outer boundary.", "Changing centre between convergence runs."],
        "refs": ["Fredkin and Koehler, IEEE Trans. Magn. 26, 415 (1990)", "Gmsh OCC geometry reference"],
    },
    "fem/airbox/grading.md": {
        "title": "FEM airbox grading",
        "scope": "Distance-based near-interface refinement and controlled far-field coarsening with explicit growth, clamps and degree-of-freedom consequences.",
        "groups": ["airbox", "fem"],
        "equations": [
            ("Geometric target", r"h_j=\min(h_{far},\max(h_{near},h_0r^j)).", "The ratio is a target field; conformity and overlapping controls determine realized sizes."),
            ("Continuous exponential model", r"h(d)=\min(h_{far},h_{near}e^{\alpha d}).", "This form explains how grading length and growth interact."),
            ("Local size ratio", r"g_f=h_{max,f}/h_{min,f}.", "A large realized ratio across adjacent cells can degrade conditioning even when both endpoints are valid."),
        ],
        "example": "airbox_grading",
        "ui": ["Open Universe → Airbox Mesh → Grading.", "Set near-interface hmin, far-field hmax and maximum growth.", "Preview size versus distance and inspect overlap with object/interface fields.", "After build, compare realized size histograms by distance shell."],
        "impl": COMMON_IMPL_FEM + [("Airbox size fields", "packages/fullmag-py/src/fullmag/meshing/_gmsh_airbox.py", "geometric/linear grading")],
        "accept": ["First air cells are commensurate with adjacent magnetic boundary cells.", "Growth is smooth enough for the selected solver/preconditioner.", "Far-field coarsening does not change the observable beyond tolerance.", "Realized shell histograms follow the intended trend."],
        "fail": ["Applying hfar directly at the magnetic interface.", "Treating requested ratio as an exact neighbor ratio.", "Using aggressive grading with an unqualified anisotropic operator.", "Changing airbox size and grading simultaneously during convergence."],
        "refs": ["Gmsh reference manual, Distance/Threshold fields", "Babuška and Strouboulis, FEM reliability"],
    },
    "fem/airbox/boundary-closure.md": {
        "title": "FEM airbox boundary closure",
        "scope": "Outer-facet marker ownership and the separate physical choice of Dirichlet, Robin or other qualified scalar-potential closures, including gauge handling.",
        "groups": ["airbox"],
        "equations": [
            ("Dirichlet closure", r"u=0\quad\text{on }\Gamma_{out}.", "Simple truncation can require a large airbox to suppress boundary bias."),
            ("Robin closure", r"\partial_nu+\beta(\mathbf x)u=0\quad\text{on }\Gamma_{out}.", "Beta belongs to the physical/numerical field solver, not to mesh generation."),
            ("Gauge constraint", r"\int_{\Omega}u\,dV=0\quad\text{or an equivalent null-space treatment}.", "Neumann/periodic formulations require explicit gauge handling."),
        ],
        "example": "boundary_closure",
        "ui": ["Verify the mesh exposes one complete outer-boundary marker.", "Select Demag → Boundary Closure separately from Airbox Mesh.", "Choose the supported closure and gauge policy.", "Run a boundary-distance study for the selected closure."],
        "impl": COMMON_IMPL_FEM + [("FEM Poisson demag contract", "docs/physics/fem_demag_poisson.md", "outer closure and gauge semantics")],
        "accept": ["Outer facets are complete and exclude internal interfaces.", "Closure parameters and gauge are recorded.", "The field/energy is insensitive to further boundary displacement.", "No artificial surface charge is introduced by marker mistakes."],
        "fail": ["Assuming boundary_marker selects Robin automatically.", "Applying Dirichlet to internal magnetic-air interfaces.", "Leaving a periodic/Neumann null space untreated.", "Comparing closures at different airbox sizes without accounting for both changes."],
        "refs": ["Fredkin and Koehler, IEEE Trans. Magn. 26, 415 (1990)", "Jackson, Classical Electrodynamics, multipole decay"],
    },
    "fem/airbox/periodic-airbox.md": {
        "title": "Periodic FEM airbox",
        "scope": "Paired outer facets and nodes for qualified k=0 periodic scalar-potential problems, with explicit separation from nonzero-k Floquet and open-boundary formulations.",
        "groups": ["airbox", "periodic", "shared"],
        "equations": [
            ("k=0 pairing", r"u(\mathbf r+\mathbf L)=u(\mathbf r).", "Paired degrees of freedom are identified subject to a gauge constraint."),
            ("Floquet generalization", r"u(\mathbf r+\mathbf L)=e^{-i\mathbf k\cdot\mathbf L}u(\mathbf r).", "Nonzero-k support is a separate complex-valued solver capability."),
            ("Mean-zero gauge", r"\int_{\Omega_{cell}}u\,dV=0.", "Periodic Poisson has a constant null mode that must be removed."),
        ],
        "example": "periodic_airbox",
        "ui": ["Choose Periodic Airbox only when the backend capability is executable.", "Define periodic axes and pair IDs; preview source/destination facet matching.", "For k=0, select the supported gauge.", "For nonzero k, require explicit Floquet demag support rather than reusing k=0."],
        "impl": COMMON_IMPL_FEM + [("Periodic pair schema", "crates/fullmag-api/src/schemas/mesh.rs", "periodic mesh pair resources"), ("Periodic smoke examples", "examples/fem_eigen_k0_kittel_periodic_airbox.py", "k=0 periodic airbox workflow")],
        "accept": ["Paired facet meshes have one-to-one geometric correspondence.", "Pair transforms and IDs are deterministic.", "Gauge/null-space handling is explicit.", "The selected demag route advertises the requested k regime."],
        "fail": ["Using ordinary open airbox with periodic boundary labels.", "Treating k=0 support as nonzero-k support.", "Pairing facets with different subdivisions.", "Omitting the phase-sign convention."],
        "refs": ["Bloch theorem", "Tewary, Phys. Rev. B 69, 094109 (2004)"],
    },
    "fem/shared-domain/index.md": {
        "title": "FEM shared-domain overview",
        "scope": "Assembly of magnetic bodies, transition regions and exterior air into a single immutable mesh resource with semantic scopes and provenance.",
        "groups": ["shared", "fem", "airbox"],
        "equations": [
            ("Total domain", r"\Omega=\left(\bigcup_r\Omega_{m,r}\right)\cup\Omega_a.", "Magnetic regions and air are separate volume roles inside one conforming mesh."),
            ("Volume accounting", r"V_{mesh}=\sum_f\sum_{K\in\mathcal T_f}|K|.", "Family-wise volumes must reproduce expected magnetic, air and shared-domain volumes."),
            ("Semantic scope", r"S=(\text{role},\text{marker},\text{adjacency},\text{revision}).", "A marker without role/adjacency/revision is insufficient for robust solver coupling."),
        ],
        "example": "shared",
        "ui": ["Apply all object policies.", "Configure Universe/Airbox and shared assembly.", "Build the full domain, not independent object meshes, for conforming coupled solves.", "Inspect global, per-region, per-interface and outer-boundary scopes."],
        "impl": COMMON_IMPL_FEM + [("Shared-domain report", "packages/fullmag-py/src/fullmag/meshing/mesh_build_report.py", "scope and fallback provenance")],
        "accept": ["Volume accounting closes within tolerance.", "All semantic scopes are complete and revision-locked.", "Interface adjacency is correct.", "No stale object mesh is substituted into the shared resource."],
        "fail": ["Solving on independently generated object meshes in a conforming formulation.", "Using marker numbers without semantic roles.", "Ignoring air volume in accounting.", "Reusing shared mesh after one object changes."],
        "refs": ["Ciarlet, FEM for Elliptic Problems", "Gmsh OCC fragment documentation"],
    },
    "fem/shared-domain/assembly-and-conformity.md": {
        "title": "Shared-domain assembly and conformity",
        "scope": "OCC fragmentation, shared node/facet construction, orientation, adjacency and exact criteria for conforming multi-region FEM assembly.",
        "groups": ["shared", "fem"],
        "equations": [
            ("Matching interface", r"\mathcal F_{rs}^{(r)}=\mathcal F_{rs}^{(s)}\ \text{as one shared facet set}.", "Coincident but independently owned facets are not conforming."),
            ("Opposite normals", r"\mathbf n_r=-\mathbf n_s\quad\text{on }\Gamma_{rs}.", "Canonical orientation is required for flux and boundary terms."),
            ("Euler/manifold check", r"n_f\in\{1,2\}\ \text{for ordinary volume meshes}.", "Facet incidence outside this set signals orphan or nonmanifold topology."),
        ],
        "example": "shared",
        "ui": ["Enable Enforce conforming in Shared Domain Policy.", "Build through the OCC fragment route.", "Inspect interface facet count, adjacency pairs and coincident-face diagnostics.", "Block solver execution if any conformity counter is nonzero."],
        "impl": COMMON_IMPL_FEM + [("OCC assembly", "packages/fullmag-py/src/fullmag/meshing/_gmsh_occ.py", "fragment and interface extraction")],
        "accept": ["Each interior facet has exactly two adjacent cells.", "Interface normals and material pairs are consistent.", "No duplicated coincident surfaces remain.", "Shared nodes are identical by index, not only by coordinates."],
        "fail": ["Welding nodes by a loose tolerance after independent meshing.", "Keeping duplicate interface facets.", "Losing orientation during extraction.", "Allowing nonmanifold intersections without a dedicated formulation."],
        "refs": ["Gmsh OCC boolean fragments", "Ciarlet, FEM for Elliptic Problems"],
    },
    "fem/shared-domain/build-modes-and-fallbacks.md": {
        "title": "Shared-domain build modes and fallbacks",
        "scope": "Strict requested/effective/realized state, qualified OCC/GEO routes, degradation reasons and fail-closed behavior for topology or geometry substitutions.",
        "groups": ["shared", "fem", "airbox", "sweep"],
        "equations": [
            ("State mapping", r"R_{requested}\xrightarrow{normalize}R_{effective}\xrightarrow{build}R_{realized}.", "Every nonidentity transition must be represented in provenance."),
            ("Strict acceptance", r"A_{strict}=1\iff R_{requested}=R_{realized}\ \land\ C_{solver}(R_{realized})=1.", "Strict mode rejects hidden topology, layer, axis, order or shape changes."),
            ("Degradation record", r"D=(\text{reason},\text{requested},\text{actual},\text{capability},\text{revision}).", "A warning string without structured context is not sufficient."),
        ],
        "example": "fallbacks",
        "ui": ["Choose strict mode for research runs that require a specific topology.", "Open Build Plan to inspect normalized/effective settings before execution.", "After build, compare actual_method and fallbacks_triggered.", "Approve a degraded result only through an explicit study-specific decision; never silently."],
        "impl": COMMON_IMPL_FEM + [("Build-report normalization", "packages/fullmag-py/src/fullmag/meshing/mesh_build_report.py", "requested/actual/status/reason fields"), ("Fallback tests", "packages/fullmag-py/tests/test_meshing_fallbacks.py", "strict and degraded scenarios")],
        "accept": ["Strict builds have no fallback markers.", "Permissive builds record every substitution.", "Actual method/topology/order/layers are displayed in UI and artifacts.", "Solver admission is evaluated after realization."],
        "fail": ["Reporting success because a mesh exists.", "Converting sphere to bbox or prism to tet without reason.", "Checking capability only against the request.", "Discarding degradation provenance during export."],
        "refs": ["Fullmag mesh realization report v1", "Fullmag capability matrix v0"],
    },
    "fem/shared-domain/selectors-and-attributes.md": {
        "title": "Shared-domain selectors and attributes",
        "scope": "Stable semantic selection of volumes, surfaces, curves and periodic pairs, plus deterministic marker/role lowering after CAD topology changes.",
        "groups": ["shared", "fem", "periodic"],
        "equations": [
            ("Semantic selection", r"S=\{e\in\mathcal E:\ P(e;\theta)=\mathrm{true}\}.", "Selectors are predicates over geometry semantics, not persistent raw Gmsh tags."),
            ("Geometric tolerance", r"|g(e)-g_*|\le\tau_{abs}+\tau_{rel}|g_*|.", "Scale-aware tolerances are required for stable plane/normal/position selectors."),
            ("Deterministic identity", r"\mathrm{id}(S)=\mathrm{sha256}(\text{normalized predicate, matches, geometry revision}).", "The resolved set and geometry revision belong to provenance."),
        ],
        "example": "selectors",
        "ui": ["Author selections by semantic role, normal, location, object and adjacency.", "Preview matched entities before applying.", "Set explicit multiplicity expectations: exactly one, pair, nonempty set or all matching.", "After geometry edits, require selector re-resolution and mesh invalidation."],
        "impl": COMMON_IMPL_FEM + [("Selector lowering", "packages/fullmag-py/src/fullmag/meshing/_size_field_plan.py", "semantic selector resolution"), ("Region lifecycle", "apps/control-room/src/shared/domain/mesh/regionMeshLifecycle.ts", "revision and invalidation behavior")],
        "accept": ["Each selector resolves with the expected multiplicity.", "Resolved entities are stored with geometry revision.", "Marker IDs are deterministic and non-colliding.", "Periodic pairs and interface adjacency remain consistent after lowering."],
        "fail": ["Persisting raw entity tags across rebuilds.", "Using an unbounded geometric tolerance.", "Accepting an empty selector silently.", "Reusing a resolved selection after geometry revision changes."],
        "refs": ["Gmsh physical groups and OCC entity semantics", "Fullmag mesh roundtrip semantics v1"],
    },
}


TOCTREES = {
    "index.md": ["fdm/index", "fem/index", "fdm-grids", "fem-shared-domain", "airbox", "refinement", "swept-meshes"],
    "fdm/index.md": ["boundary-correction", "multi-magnet-grids", "periodic-grids"],
    "fem/index.md": ["ferromagnet/index", "airbox/index", "shared-domain/index"],
    "fem/ferromagnet/index.md": ["free-tetrahedral", "thin-film-tetrahedral", "swept-prism", "swept-hex", "boundary-layers", "imported-mesh", "mixed-elements"],
    "fem/airbox/index.md": ["geometry", "grading", "boundary-closure", "periodic-airbox"],
    "fem/shared-domain/index.md": ["assembly-and-conformity", "build-modes-and-fallbacks", "selectors-and-attributes"],
}
