from __future__ import annotations

import json
import re
import unittest
from collections.abc import Mapping
from pathlib import Path

import fullmag as fm
from fullmag.runtime.scene_document import (
    build_builder_from_scene_document,
    build_scene_document_from_builder,
)


REPO_ROOT = Path(__file__).resolve().parents[3]
MANIFEST_PATH = REPO_ROOT / "docs/specs/spin-transport-authoring-parameter-parity-v1.json"


def _path_values(root: object, path: str) -> list[object]:
    """Resolve a dotted manifest path over objects, mappings, and ``[*]`` lists."""

    tokens = [token for token in path.split(".") if token]

    def walk(value: object, remaining: list[str]) -> list[object]:
        if not remaining:
            return [value]
        token = remaining[0]
        match = re.fullmatch(r"([^\[]+)(?:\[\*\])?", token)
        if match is None:
            raise AssertionError(f"invalid parity path token {token!r}")
        name = match.group(1)
        wildcard = "[*]" in token
        if isinstance(value, Mapping):
            if name not in value:
                return []
            child = value[name]
        else:
            try:
                child = getattr(value, name)
            except AttributeError:
                # schema/constitutive versions are generated by ``to_ir`` and
                # are still public Python authoring semantics.
                to_ir = getattr(value, "to_ir", None)
                if not callable(to_ir):
                    to_ir = getattr(value, "to_ir_module", None)
                if not callable(to_ir):
                    return []
                generated = to_ir()
                if not isinstance(generated, Mapping) or name not in generated:
                    return []
                child = generated[name]
        if wildcard:
            if not isinstance(child, (list, tuple)):
                return []
            result: list[object] = []
            for item in child:
                result.extend(walk(item, remaining[1:]))
            return result
        return walk(child, remaining[1:])

    return walk(root, tokens)


def _region(object_id: str = "stack", region_id: str = "ferromagnet") -> fm.RegionRef:
    return fm.RegionRef(object_id, region_id)


def _surface(surface_id: str = "top") -> fm.SurfaceRef:
    return fm.SurfaceRef("stack", surface_id, (0.0, 0.0, 1.0))


def build_parity_fixtures() -> dict[tuple[str, str], list[dict[str, object]]]:
    """Build non-default, signed fixtures for every manifest variant.

    A list is used for variants with mutually-exclusive bindings (prescribed
    current versus named source) or mutually-exclusive transient capacitance
    representations.  Coverage is the union of those valid authoring forms.
    """

    target = _region()
    normal = fm.RegionRef("stack", "normal_metal")
    top = _surface()
    closed_view = fm.ConservativeCurrentView(
        stable_vertex_ids=[10, 20, 30, 40],
        boundary_faces=[
            fm.ConservativeCurrentBoundaryFace((10, 20, 30), "source_cut", "drive"),
            fm.ConservativeCurrentBoundaryFace((10, 20, 40), "source_cut", "drive"),
            fm.ConservativeCurrentBoundaryFace((10, 30, 40), "insulating_outer"),
        ],
        identity=fm.ConservativeCurrentIdentity(
            source_module_id="charge-ohmic",
            source_state_revision="state-1",
            source_field_digest="field-1",
            conductivity_digest="sigma-1",
            mesh_revision="mesh-1",
            topology_revision="topology-1",
            geometry_digest="geometry-1",
            envelope_revision="envelope-1",
            envelope_digest="envelope-1",
            evaluated_envelope_multiplier=1.0,
            evaluation_time_s=0.0,
            stage_identity=1,
        ),
        pins=fm.ConservativeCurrentPins(
            required_source_state_revision="state-1",
            required_source_field_digest="field-1",
            required_mesh_revision="mesh-1",
            required_topology_revision="topology-1",
        ),
        closure=fm.ConservativeCurrentClosedGeometry(
            "fem_charge_rt0.v1",
            "closure-1",
            "closure-1",
            [fm.ConservativeCurrentSourceCut(
                "cut-x",
                (1.0, 0.0, 0.0),
                0.1,
                [fm.ConservativeCurrentSourceCutFacePair((10, 20, 30), (10, 20, 40))],
            )],
        ),
        algebraic_relative_tolerance=1.0e-10,
        physical_relative_gate=1.0e-8,
        physical_absolute_gate_a=1.0e-12,
    )
    charge_one_way = fm.CurrentTransport(
        name="charge-ohmic",
        model="ohmic_poisson",
        domain=[target],
        materials=[
            fm.ChargeTransportMaterialAssignment(
                target,
                fm.ChargeTransportMaterial(4.2e6),
            )
        ],
        boundaries=[fm.VoltageElectrode("top", [top], potential_V=-0.031)],
        gauge=fm.ChargePotentialGauge("dirichlet_reference"),
        solver=fm.ChargeSolverPolicy(
            relative_tolerance=2.0e-9,
            absolute_tolerance=3.0e-12,
            max_iterations=321,
        ),
        time_envelope=fm.SinusoidalEnvelope(
            amplitude=0.35,
            frequency_hz=1.2e9,
            phase_rad=-0.4,
            offset=0.9,
        ),
        conservative_current_view=closed_view,
    )
    charge_reciprocal = fm.CurrentTransport(
        name="charge-m2",
        model="ohmic_poisson",
        coupling="bidirectional",
        domain=[normal, target],
        materials=[
            fm.ChargeTransportMaterialAssignment(
                normal,
                fm.ChargeTransportMaterial(
                    5.2e6,
                    sigma_parallel_Spm=5.3e6,
                    sigma_perpendicular_Spm=4.9e6,
                    sigma_AHE_Spm=-0.12e6,
                ),
            ),
            fm.ChargeTransportMaterialAssignment(
                target,
                fm.ChargeTransportMaterial(
                    3.1e6,
                    sigma_parallel_Spm=3.4e6,
                    sigma_perpendicular_Spm=2.8e6,
                    sigma_AHE_Spm=0.07e6,
                ),
            ),
        ],
        boundaries=[fm.VoltageElectrode("top-m2", [top], potential_V=0.017)],
        gauge=fm.ChargePotentialGauge("zero_mean"),
        solver=fm.ChargeSolverPolicy(
            engine="block_gmres",
            relative_tolerance=3.0e-9,
            absolute_tolerance=4.0e-12,
            max_iterations=654,
            operator_version="fdm_coupled_charge_spin_fv_block_gmres.v1",
        ),
    )
    spin_materials = [
        fm.SpinTransportMaterialAssignment(
            normal,
            fm.SpinTransportMaterial(
                sigma_s_Spm=5.0e6,
                polarization_p=-0.18,
                theta_sh=0.13,
                lambda_sf_m=1.7e-9,
            ),
        ),
        fm.SpinTransportMaterialAssignment(
            target,
            fm.SpinTransportMaterial(
                sigma_s_Spm=3.0e6,
                polarization_p=0.47,
                theta_sh=-0.02,
                lambda_sf_m=4.2e-9,
                lambda_j_m=1.1e-9,
                lambda_phi_m=0.9e-9,
            ),
        ),
    ]
    spin_steady = fm.SpinDriftDiffusion(
        id="spin-steady",
        current_source_id=charge_one_way.name,
        domain=[normal, target],
        materials=spin_materials,
        interfaces=[
            fm.TransparentSpinInterface("transparent", normal, target, (0.0, 0.0, 1.0)),
            fm.MixingConductanceSpinInterface(
                id="mixing",
                normal_to_ferromagnet=(0.0, 0.0, 1.0),
                normal_side=normal,
                ferromagnet_side=target,
                g_up_Spm2=1.1e15,
                g_down_Spm2=0.8e15,
                g_r_Spm2=2.2e15,
                g_i_Spm2=-0.16e15,
                spin_memory_loss=fm.SpinMemoryLossReservoir(
                    g_n_Spm2=0.12e15,
                    g_f_Spm2=0.21e15,
                    g_lattice_Spm2=0.33e15,
                ),
            ),
        ],
        boundaries=[
            fm.SpinSink("sink", [top]),
        ],
        solver=fm.SpinSolverPolicy(
            engine="gmres",
            relative_tolerance=4.0e-9,
            absolute_tolerance=5.0e-12,
            max_iterations=777,
            operator_version="fv_spin_upwind_v1",
            default_external_boundary="reject_unassigned",
            reciprocal_nonlinear=fm.ReciprocalNonlinearSolverPolicy(
                gmres_restart=23,
                max_picard_iterations=5,
                relative_update_tolerance=6.0e-8,
                eta_transport=0.31,
            ),
        ),
        requested_execution=fm.TransportExecution(
            discretization="fem",
            device="cpu",
            precision="double",
            execution_mode="extended",
        ),
    )
    transient_cap = fm.SpinDriftDiffusion(
        id="spin-transient-cap",
        current_source_id=charge_one_way.name,
        domain=[target],
        materials=[
            fm.SpinTransportMaterialAssignment(
                target,
                fm.SpinTransportMaterial(
                    sigma_s_Spm=2.1e6,
                    polarization_p=0.11,
                    theta_sh=0.08,
                    lambda_sf_m=2.4e-9,
                    spin_capacitance_As_per_V_m3=4.0e-3,
                    capacitance_formula_version="dos_isotropic_nonmagnetic.fullmag.v1",
                ),
            )
        ],
        mode="transient",
    )
    transient_dos = fm.SpinDriftDiffusion(
        id="spin-transient-dos",
        current_source_id=charge_one_way.name,
        domain=[target],
        materials=[
            fm.SpinTransportMaterialAssignment(
                target,
                fm.SpinTransportMaterial(
                    sigma_s_Spm=2.2e6,
                    polarization_p=-0.09,
                    theta_sh=-0.06,
                    lambda_sf_m=2.7e-9,
                    density_of_states_per_spin_Jinv_m3=1.8e37,
                    capacitance_formula_version="dos_isotropic_nonmagnetic.fullmag.v1",
                ),
            )
        ],
        mode="transient",
    )

    zhang_density = fm.ZhangLiSTT(
        current_density=(-4.2e11, 1.1e11, -2.0e10),
        degree=0.61,
        beta=0.07,
        id="zl-density",
        target=target,
        lande_g=2.0,
        operator_version="zl_mumax3_central_v1",
    )
    zhang_source = fm.ZhangLiSTT(
        current_source="charge-ohmic",
        degree=0.53,
        beta=0.09,
        id="zl-source",
        target=target,
        lande_g=2.08,
        operator_version="zl_central_reference_v1",
    )
    slon_density = fm.SlonczewskiSTT(
        current_density=(0.0, 0.0, -3.7e11),
        spin_polarization=(0.2, -0.3, 0.9),
        degree=0.57,
        lambda_asymmetry=1.31,
        epsilon_prime=-0.06,
        free_layer_thickness_m=2.2e-9,
        id="slon-density",
        target=target,
        stack_normal=(0.0, 0.0, 1.0),
    )
    slon_source = fm.SlonczewskiSTT(
        current_source="charge-ohmic",
        spin_polarization=(-0.1, 0.4, 0.8),
        degree=0.49,
        lambda_asymmetry=1.17,
        epsilon_prime=0.03,
        free_layer_thickness_m=1.8e-9,
        id="slon-source",
        target=target,
        stack_normal=(0.0, 1.0, 0.0),
    )
    prescribed_sot = fm.PrescribedSpinOrbitTorque(
        "sot",
        target,
        fm.SignedScalarDrive(
            -3.4e11,
            (0.0, 1.0, -0.2),
            fm.SinusoidalEnvelope(amplitude=0.8, frequency_hz=2.4e9, phase_rad=-0.3, offset=0.1),
        ),
        xi_dl=-0.23,
        xi_fl=0.07,
        free_layer_thickness_m=1.6e-9,
    )
    oersted_cylinder = fm.OerstedCylinder(
        current=-0.018,
        radius=24e-9,
        center=(2e-9, -3e-9, 1e-9),
        axis=(0.0, 1.0, 1.0),
        time_dependence=fm.Sinusoidal(frequency_hz=1.7e9, phase_rad=-0.2, offset=0.15),
    )
    oersted_field = fm.OerstedField(source="charge-ohmic")

    def case(python: dict[str, object], ir: object) -> dict[str, object]:
        if hasattr(ir, "to_ir"):
            lowered = ir.to_ir()
        elif hasattr(ir, "to_ir_module"):
            lowered = ir.to_ir_module()
        else:
            lowered = ir
        return {"python": python, "ir": lowered}

    return {
        ("current_transport", "prescribed_density"): [
            case({"CurrentTransport": fm.CurrentTransport(
                name="drive",
                current_density=(-4.2e10, 1.5e10, -2.0e9),
                solve_region="film",
                time_envelope=fm.PulseEnvelope(
                    amplitude=0.8,
                    t_on_s=2.0e-12,
                    t_off_s=5.0e-12,
                ),
            )}, fm.CurrentTransport(
                name="drive",
                current_density=(-4.2e10, 1.5e10, -2.0e9),
                solve_region="film",
                time_envelope=fm.PulseEnvelope(
                    amplitude=0.8,
                    t_on_s=2.0e-12,
                    t_off_s=5.0e-12,
                ),
            ))
        ],
        ("current_transport", "ohmic_poisson"): [
            case({"CurrentTransport": charge_one_way}, charge_one_way),
            case({"CurrentTransport": charge_reciprocal}, charge_reciprocal),
        ],
        ("spin_transport", "steady"): [
            case({"SpinDriftDiffusion": spin_steady}, spin_steady.to_ir())
        ],
        ("spin_transport", "transient"): [
            case({"SpinDriftDiffusion": transient_cap}, transient_cap.to_ir()),
            case({"SpinDriftDiffusion": transient_dos}, transient_dos.to_ir()),
        ],
        ("spin_torque", "zhang_li"): [
            case({"ZhangLiSTT": zhang_density}, zhang_density),
            case({"ZhangLiSTT": zhang_source}, zhang_source),
        ],
        ("spin_torque", "slonczewski"): [
            case({"SlonczewskiSTT": slon_density}, slon_density),
            case({"SlonczewskiSTT": slon_source}, slon_source),
        ],
        ("spin_torque", "prescribed_sot"): [
            case({"PrescribedSpinOrbitTorque": prescribed_sot}, prescribed_sot)
        ],
        ("oersted", "oersted_cylinder"): [
            case({"OerstedCylinder": oersted_cylinder}, oersted_cylinder)
        ],
        ("oersted", "oersted_field"): [
            case({"OerstedField": oersted_field}, oersted_field)
        ],
    }


class SpinTransportAuthoringParameterParityTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls) -> None:
        cls.manifest = json.loads(MANIFEST_PATH.read_text(encoding="utf-8"))
        cls.fixtures = build_parity_fixtures()

    def test_every_non_forbidden_manifest_path_is_represented_in_python_and_ir(self) -> None:
        for parameter in self.manifest["parameters"]:
            if parameter["round_trip"] == "forbidden":
                continue
            key = (parameter["family"], parameter["variant"])
            cases = self.fixtures.get(key)
            self.assertIsNotNone(cases, f"missing fixture for {key}")
            python_values = [
                value
                for item in cases or []
                for value in _path_values(item["python"], parameter["python_path"])
            ]
            ir_values = [
                value
                for item in cases or []
                for value in _path_values(item["ir"], parameter["ir_path"])
            ]
            self.assertTrue(
                python_values,
                f"{parameter['id']} missing from typed Python fixtures",
            )
            self.assertTrue(
                ir_values,
                f"{parameter['id']} missing from lowered IR fixtures",
            )

    def test_scene_document_round_trip_preserves_current_torque_and_oersted_contracts(self) -> None:
        current = build_parity_fixtures()[("current_transport", "ohmic_poisson")][0]["ir"]
        torques = [
            build_parity_fixtures()[("spin_torque", "zhang_li")][0]["ir"],
            build_parity_fixtures()[("spin_torque", "slonczewski")][0]["ir"],
            build_parity_fixtures()[("spin_torque", "prescribed_sot")][0]["ir"],
        ]
        oersted = [
            build_parity_fixtures()[("oersted", "oersted_cylinder")][0]["ir"],
            build_parity_fixtures()[("oersted", "oersted_field")][0]["ir"],
        ]
        builder = {
            "revision": 7,
            "geometries": [],
            "current_modules": [current],
            "spin_torques": torques,
            "oersted_terms": oersted,
        }
        scene = build_scene_document_from_builder(builder)
        inverse = build_builder_from_scene_document(scene)
        self.assertEqual(scene["current_transports"], [current])
        self.assertEqual(inverse["current_modules"], [current])
        self.assertEqual(inverse["spin_torques"], torques)
        self.assertEqual(inverse["oersted_terms"], oersted)


if __name__ == "__main__":
    unittest.main()
