//! OpenAPI spec assembly.

use utoipa::OpenApi;

#[derive(OpenApi)]
#[openapi(
    paths(
        crate::router_v1::handlers::status::get_status,
        crate::router_v1::handlers::domain::get_domain_meta,
        crate::router_v1::handlers::domain::get_domain_topology,
        crate::router_v1::handlers::domain::get_domain_coordinates,
        crate::router_v1::handlers::fields::get_field_catalog,
        crate::router_v1::handlers::fields::get_field_meta,
        crate::router_v1::handlers::fields::get_field_vector,
        crate::router_v1::handlers::scalars::get_scalars,
        crate::router_v1::handlers::display::update_display,
        crate::router_v1::handlers::display::patch_display,
        crate::router_v1::handlers::commands::submit_command,
        crate::router_v1::handlers::assets::import_asset,
        crate::router_v1::handlers::artifacts::list_artifacts,
        crate::router_v1::handlers::artifacts::get_artifact,
        crate::router_v1::handlers::eigen::get_spectrum,
        crate::router_v1::handlers::eigen::get_mode,
        crate::router_v1::handlers::eigen::get_dispersion,
        crate::router_v1::handlers::eigen::get_branches,
        crate::router_v1::handlers::system::get_engine_log,
        crate::router_v1::handlers::system::get_gpu_telemetry,
        crate::router_v1::handlers::session::export_session,
        crate::router_v1::handlers::session::inspect_session,
        crate::router_v1::handlers::session::commit_session,
        crate::router_v1::handlers::system::get_capabilities,
        crate::router_v1::handlers::system::get_health,
    ),
    components(schemas(
        crate::schemas::status::LiveStatus,
        crate::schemas::status::SessionSummary,
        crate::schemas::status::RunSummary,
        crate::schemas::status::SolverSummary,
        crate::schemas::status::DisplaySelection,
        crate::schemas::status::DomainSummary,
        crate::schemas::status::ResourceRevisionMap,
        crate::schemas::status::CapabilityMap,
        crate::schemas::status::EnergySummary,
        crate::schemas::status::MetricsSummary,
        crate::schemas::domain::DomainMeta,
        crate::schemas::domain::Bounds3,
        crate::schemas::domain::DomainCounts,
        crate::schemas::domain::StructuredGridDescriptor,
        crate::schemas::fields::FieldCatalog,
        crate::schemas::fields::FieldDescriptor,
        crate::schemas::fields::FieldMeta,
        crate::schemas::fields::FieldStats,
        crate::schemas::scalars::ScalarWindow,
        crate::schemas::display::DisplayUpdate,
        crate::schemas::commands::CommandRequest,
        crate::schemas::commands::CommandResponse,
        crate::schemas::common::ApiErrorResponse,
        crate::schemas::common::HealthResponse,
        crate::types::ImportSessionAssetRequest,
        crate::types::SessionAssetImportResponse,
        crate::types::ImportedAssetSummary,
        crate::types::BoundsSummary,
    )),
    tags(
        (name = "status", description = "Live status summary"),
        (name = "domain", description = "Domain / mesh metadata"),
        (name = "fields", description = "Field catalog and data"),
        (name = "scalars", description = "Scalar time-series"),
        (name = "display", description = "Display selection"),
        (name = "commands", description = "Control commands"),
        (name = "artifacts", description = "Run artifacts"),
        (name = "eigen", description = "Eigenmode / frequency analysis"),
        (name = "session", description = "Session persistence"),
        (name = "system", description = "System / health"),
    ),
    info(
        title = "Fullmag API v1",
        version = "1.0.0",
        description = "Resource-first REST API for Fullmag micromagnetics platform",
    )
)]
pub struct ApiDoc;
