//! OpenAPI spec assembly.

use utoipa::OpenApi;

#[derive(OpenApi)]
#[openapi(
    paths(
        crate::router_v1::handlers::status::get_status,
        crate::router_v1::handlers::domain::get_domain_meta,
        crate::router_v1::handlers::domain::get_domain_topology,
        crate::router_v1::handlers::quantities::get_quantities_catalog,
        crate::router_v1::handlers::fields::get_field_catalog,
        crate::router_v1::handlers::fields::get_field_meta,
        crate::router_v1::handlers::fields::get_field_vector,
        crate::router_v1::handlers::scalars::get_scalars,
        crate::router_v1::handlers::display::get_display,
        crate::router_v1::handlers::display::replace_display,
        crate::router_v1::handlers::display::patch_display,
        crate::router_v1::handlers::scene::get_scene_document,
        crate::router_v1::handlers::scene::replace_scene_document,
        crate::router_v1::handlers::authoring::get_authoring_scene,
        crate::router_v1::handlers::authoring::replace_authoring_scene,
        crate::router_v1::handlers::authoring::patch_authoring_scene,
        crate::router_v1::handlers::authoring::commit_authoring_transaction,
        crate::router_v1::handlers::authoring::get_authoring_study_runtime,
        crate::router_v1::handlers::authoring::patch_authoring_study_runtime,
        crate::router_v1::handlers::authoring::get_authoring_material,
        crate::router_v1::handlers::authoring::patch_authoring_material,
        crate::router_v1::handlers::authoring::get_authoring_script_source,
        crate::router_v1::handlers::authoring::sync_authoring_script,
        crate::router_v1::handlers::commands::submit_command,
        crate::router_v1::handlers::runtime::get_command_status,
        crate::router_v1::handlers::runtime::get_command_detail,
        crate::router_v1::handlers::assets::import_asset,
        crate::router_v1::handlers::runtime::get_current_run,
        crate::router_v1::handlers::runtime::get_stage_execution,
        crate::router_v1::handlers::runtime::get_solver_status,
        crate::router_v1::handlers::runtime::get_solver_energies_current,
        crate::router_v1::handlers::runtime::get_solver_energies_history,
        crate::router_v1::handlers::artifacts::list_artifacts,
        crate::router_v1::handlers::artifacts::get_artifact,
        crate::router_v1::handlers::eigen::get_spectrum,
        crate::router_v1::handlers::eigen::get_mode,
        crate::router_v1::handlers::eigen::get_dispersion,
        crate::router_v1::handlers::eigen::get_branches,
        crate::router_v1::handlers::system::get_engine_log,
        crate::router_v1::handlers::system::get_gpu_telemetry,
        crate::router_v1::handlers::session::export_session,
        crate::router_v1::handlers::session::inspect_session,
        crate::router_v1::handlers::session::commit_session,
        crate::router_v1::handlers::session::list_checkpoints,
        crate::router_v1::handlers::session::list_recovery,
        crate::router_v1::handlers::session::clear_recovery,
        crate::router_v1::handlers::system::get_capabilities,
        crate::router_v1::handlers::system::get_health,
    ),
    components(schemas(
        crate::schemas::status::LiveStatus,
        crate::schemas::status::SessionSummary,
        crate::schemas::status::RunSummary,
        crate::schemas::status::SolverSummary,
        crate::schemas::status::DisplaySelection,
        crate::schemas::status::DomainSummary,
        crate::schemas::status::ResourceRevisionMap,
        crate::schemas::status::CapabilityMap,
        crate::schemas::status::EnergySummary,
        crate::schemas::status::MetricsSummary,
        crate::schemas::domain::DomainMeta,
        crate::schemas::domain::Bounds3,
        crate::schemas::domain::DomainCounts,
        crate::schemas::domain::StructuredGridDescriptor,
        crate::schemas::quantities::QuantityCatalogResponse,
        crate::schemas::quantities::QuantityCatalogEntry,
        crate::schemas::fields::FieldCatalog,
        crate::schemas::fields::FieldDescriptor,
        crate::schemas::fields::FieldMeta,
        crate::schemas::fields::FieldStats,
        crate::schemas::logs::EngineLogResource,
        crate::schemas::scalars::ScalarWindow,
        crate::schemas::display::DisplayPatch,
        crate::schemas::commands::StructuredCommandRequest,
        crate::schemas::commands::CommandResponse,
        crate::schemas::authoring::ScenePatchRequest,
        crate::schemas::authoring::AuthoringTransactionRequest,
        crate::schemas::authoring::AuthoringTransactionResponse,
        crate::schemas::authoring::StudyRuntimeResource,
        crate::schemas::authoring::StudyRuntimePatchRequest,
        crate::schemas::authoring::MaterialPropertiesResource,
        crate::schemas::authoring::MaterialResource,
        crate::schemas::authoring::MaterialPropertiesPatchRequest,
        crate::schemas::authoring::MaterialPatchRequest,
        crate::schemas::runtime::CurrentRunResource,
        crate::schemas::runtime::StageExecutionResource,
        crate::schemas::runtime::StageExecutionRecordResource,
        crate::schemas::runtime::SolverStatusResource,
        crate::schemas::runtime::SolverEnergyCurrentResource,
        crate::schemas::runtime::SolverEnergyHistoryResource,
        crate::schemas::runtime::SolverEnergyRow,
        crate::schemas::runtime::CommandQueueStatusResource,
        crate::schemas::runtime::CommandStatusResource,
        crate::schemas::runtime::CommandDetailResource,
        crate::schemas::common::ApiErrorResponse,
        crate::schemas::common::HealthResponse,
        crate::types::ImportSessionAssetRequest,
        crate::types::SessionAssetImportResponse,
        crate::types::ImportedAssetSummary,
        crate::types::BoundsSummary,
        crate::types::ScriptSyncRequest,
        crate::types::ScriptSyncResponse,
        crate::types::ScriptSourceResponse,
        crate::types::EngineLogEntry,
        crate::types::GpuTelemetryDevice,
        crate::types::GpuTelemetryResponse,
        crate::session_persistence::SessionExportRequest,
        crate::session_persistence::SessionExportResponse,
        crate::session_persistence::SessionImportInspectRequest,
        crate::session_persistence::SessionImportInspectResponse,
        crate::session_persistence::SessionImportCommitRequest,
        crate::session_persistence::SessionImportCommitResponse,
        crate::session_persistence::CheckpointListResponse,
        crate::session_persistence::CheckpointEntry,
        crate::session_persistence::RecoveryListResponse,
        crate::session_persistence::RecoveryEntry,
        crate::session_persistence::RecoveryClearResponse,
        fullmag_session::SaveProfile,
        fullmag_session::RestoreClass,
        fullmag_session::CompressionProfile,
        fullmag_session::SessionInspection,
        fullmag_session::CheckpointSummary,
    )),
    tags(
        (name = "status", description = "Live status summary"),
        (name = "domain", description = "Domain / mesh metadata"),
        (name = "quantities", description = "Quantity catalog"),
        (name = "fields", description = "Field catalog and data"),
        (name = "scalars", description = "Scalar time-series"),
        (name = "display", description = "Display selection"),
        (name = "scene", description = "Scene document resource"),
        (name = "authoring", description = "Canonical authoring scene and script resources"),
        (name = "commands", description = "Control commands"),
        (name = "runtime", description = "Runs, stages, solver state, and runtime read-models"),
        (name = "artifacts", description = "Run artifacts"),
        (name = "eigen", description = "Eigenmode / frequency analysis"),
        (name = "session", description = "Session persistence"),
        (name = "system", description = "System / health"),
    ),
    info(
        title = "Fullmag API v1",
        version = "1.0.0",
        description = "Resource-first REST API for Fullmag micromagnetics platform",
    )
)]
pub struct ApiDoc;
