use crate::schemas::realtime::RealtimeCommunicationPolicy;
use fullmag_session::communication_policy::{
    LIVE_ERROR_RETRY_MS, LIVE_REALTIME_COALESCE_WINDOW_MS,
    LIVE_REALTIME_DIAGNOSTICS_SUMMARY_WINDOW_MS, LIVE_REALTIME_FIELD_SAMPLE_COALESCE_WINDOW_MS,
    LIVE_REALTIME_HEARTBEAT_SECS, LIVE_REALTIME_RECONNECT_MS, LIVE_REALTIME_REPLAY_CAPACITY,
    LIVE_SCALAR_TELEMETRY_INTERVAL_MS, LIVE_STATUS_REFRESH_MS, LIVE_TABLE_ROWS_MIN_REFETCH_MS,
};

pub(crate) const CURRENT_LIVE_REALTIME_REPLAY_CAPACITY: usize = LIVE_REALTIME_REPLAY_CAPACITY;
pub(crate) const CURRENT_LIVE_REALTIME_HEARTBEAT_SECS: u64 = LIVE_REALTIME_HEARTBEAT_SECS;
pub(crate) const CURRENT_LIVE_REALTIME_COALESCE_WINDOW_MS: u32 = LIVE_REALTIME_COALESCE_WINDOW_MS;
pub(crate) const CURRENT_LIVE_REALTIME_FIELD_SAMPLE_COALESCE_WINDOW_MS: u32 =
    LIVE_REALTIME_FIELD_SAMPLE_COALESCE_WINDOW_MS;
pub(crate) const CURRENT_LIVE_SCALAR_TELEMETRY_PUBLISH_MS: u32 =
    LIVE_SCALAR_TELEMETRY_INTERVAL_MS as u32;
pub(crate) const CURRENT_LIVE_TABLE_ROWS_MIN_REFETCH_MS: u32 = LIVE_TABLE_ROWS_MIN_REFETCH_MS;
pub(crate) const CURRENT_LIVE_REALTIME_DIAGNOSTICS_SUMMARY_WINDOW_MS: u32 =
    LIVE_REALTIME_DIAGNOSTICS_SUMMARY_WINDOW_MS;
pub(crate) const CURRENT_LIVE_REALTIME_RECONNECT_MS: u32 = LIVE_REALTIME_RECONNECT_MS;
pub(crate) const CURRENT_LIVE_STATUS_REFRESH_MS: u32 = LIVE_STATUS_REFRESH_MS;
pub(crate) const CURRENT_LIVE_ERROR_RETRY_MS: u32 = LIVE_ERROR_RETRY_MS;

pub(crate) fn current_live_realtime_communication_policy() -> RealtimeCommunicationPolicy {
    RealtimeCommunicationPolicy {
        ws_replay_capacity: CURRENT_LIVE_REALTIME_REPLAY_CAPACITY as u32,
        ws_heartbeat_ms: CURRENT_LIVE_REALTIME_HEARTBEAT_SECS.saturating_mul(1_000) as u32,
        ws_reconnect_ms: CURRENT_LIVE_REALTIME_RECONNECT_MS,
        lifecycle_coalesce_ms: CURRENT_LIVE_REALTIME_COALESCE_WINDOW_MS,
        table_rows_min_refetch_ms: CURRENT_LIVE_TABLE_ROWS_MIN_REFETCH_MS,
        field_sample_publish_ms: CURRENT_LIVE_REALTIME_FIELD_SAMPLE_COALESCE_WINDOW_MS,
        scalar_telemetry_publish_ms: CURRENT_LIVE_SCALAR_TELEMETRY_PUBLISH_MS,
        diagnostics_summary_ms: CURRENT_LIVE_REALTIME_DIAGNOSTICS_SUMMARY_WINDOW_MS,
        status_refresh_ms: CURRENT_LIVE_STATUS_REFRESH_MS,
        error_retry_ms: CURRENT_LIVE_ERROR_RETRY_MS,
    }
}
