"""Ownership-oriented public-documentation information architecture.

This module overlays the historical manifest without deleting stable public pages.
The visible tree is organized by Frontend, Backend, and Python API ownership.
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[3] / "scripts"))

import public_docs_information_architecture as legacy
from public_docs_information_architecture import *  # noqa: F401,F403

_REPLACEMENTS = {
    'index.md': PageSpec(path='index.md', title='FullMag documentation', label='public-docs-root', status='partial', doc_kind='reference', scope='the canonical documentation page for FullMag documentation', children=('getting-started/index.md', 'frontend/index.md', 'backend/index.md', 'python-api/index.md', 'validation/index.md'), navigation_maxdepth=5),
    'getting-started/index.md': PageSpec(path='getting-started/index.md', title='Getting started', label='public-docs-getting-started-root', status='partial', doc_kind='reference', scope='the getting-started documentation family', children=('getting-started/installation.md', 'getting-started/first-fdm-simulation.md', 'getting-started/first-fem-simulation.md', 'getting-started/choosing-a-solver.md', 'getting-started/control-room.md'), navigation_maxdepth=1),
    'python-api/index.md': PageSpec(path='python-api/index.md', title='Python API', label='public-docs-python-api-root', status='implemented', doc_kind='reference', scope='the canonical documentation page for Python API', children=('python-api/problem/index.md', 'python-api/geometry/index.md', 'python-api/materials/index.md', 'python-api/magnets-and-textures/index.md', 'python-api/interactions/index.md', 'python-api/current-and-excitations/index.md', 'python-api/boundary-conditions/index.md', 'python-api/meshing/index.md', 'python-api/discretization/index.md', 'python-api/dynamics/index.md', 'python-api/studies/index.md', 'python-api/outputs/index.md', 'python-api/runtime/index.md'), navigation_maxdepth=4),
    'python-api/discretization/index.md': PageSpec(path='python-api/discretization/index.md', title='Low-Level Discretization Hints', label='public-docs-python-api-discretization-root', status='implemented', doc_kind='reference', scope='the canonical documentation page for Low-Level Discretization Hints', children=('python-api/discretization/discretization-hints.md', 'python-api/discretization/hybrid.md'), navigation_maxdepth=1),
    'numerical-methods/index.md': PageSpec(path='numerical-methods/index.md', title='Numerical Methods', label='public-docs-numerical-methods-root', status='implemented', doc_kind='reference', scope='the canonical documentation page for Numerical Methods', children=('numerical-methods/time-integration/index.md', 'numerical-methods/relaxation/index.md', 'numerical-methods/demag-solvers/index.md', 'numerical-methods/eigensolvers/index.md', 'numerical-methods/frequency-domain/index.md', 'numerical-methods/interpolation-and-state-transfer/index.md'), navigation_maxdepth=2),
    'numerical-methods/meshing/index.md': PageSpec(path='numerical-methods/meshing/index.md', title='Meshing', label='public-docs-numerical-methods-meshing-root', status='implemented', doc_kind='reference', scope='the canonical documentation page for Meshing', children=('numerical-methods/meshing/fdm/index.md', 'numerical-methods/meshing/fem/index.md', 'numerical-methods/meshing/refinement.md'), navigation_maxdepth=4),
}

_BASE_SPECS = tuple(_REPLACEMENTS.get(spec.path, spec) for spec in legacy.PAGE_SPECS)

_NEW_SPECS = (
    PageSpec(path='frontend/index.md', title='Frontend', label='public-docs-frontend-root', status='implemented', doc_kind='reference', scope='the canonical documentation page for Frontend', children=('frontend/control-room/index.md', 'frontend/capability-register.md', 'frontend/meshing/index.md', 'frontend/visualization/index.md', 'frontend/state-and-commands/index.md'), navigation_maxdepth=3),
    PageSpec(path='frontend/control-room/index.md', title='Control Room', label='public-docs-frontend-control-room-root', status='implemented', doc_kind='reference', scope='the canonical documentation page for Control Room', children=(), navigation_maxdepth=1),
    PageSpec(path='frontend/capability-register.md', title='Frontend Capability Register', label='public-docs-frontend-capability-register', status='implemented', doc_kind='reference', scope='the canonical documentation page for Frontend Capability Register', children=(), navigation_maxdepth=1),
    PageSpec(path='frontend/meshing/index.md', title='Meshing UI', label='public-docs-frontend-meshing-root', status='implemented', doc_kind='reference', scope='the canonical documentation page for Meshing UI', children=('frontend/meshing/object-mesh.md', 'frontend/meshing/airbox-mesh.md', 'frontend/meshing/region-mesh.md', 'frontend/meshing/fdm-grid-view.md', 'frontend/meshing/build-lifecycle.md', 'frontend/meshing/quality-and-reports.md', 'frontend/meshing/python-round-trip.md'), navigation_maxdepth=2),
    PageSpec(path='frontend/meshing/object-mesh.md', title='FEM Object Mesh Panel', label='public-docs-frontend-meshing-object-mesh', status='implemented', doc_kind='reference', scope='the canonical documentation page for FEM Object Mesh Panel', children=(), navigation_maxdepth=1),
    PageSpec(path='frontend/meshing/airbox-mesh.md', title='FEM Airbox Mesh Panel', label='public-docs-frontend-meshing-airbox-mesh', status='implemented', doc_kind='reference', scope='the canonical documentation page for FEM Airbox Mesh Panel', children=(), navigation_maxdepth=1),
    PageSpec(path='frontend/meshing/region-mesh.md', title='FEM Region Mesh Panel', label='public-docs-frontend-meshing-region-mesh', status='implemented', doc_kind='reference', scope='the canonical documentation page for FEM Region Mesh Panel', children=(), navigation_maxdepth=1),
    PageSpec(path='frontend/meshing/fdm-grid-view.md', title='FDM Grid Inspector', label='public-docs-frontend-meshing-fdm-grid-view', status='implemented', doc_kind='reference', scope='the canonical documentation page for FDM Grid Inspector', children=(), navigation_maxdepth=1),
    PageSpec(path='frontend/meshing/build-lifecycle.md', title='Mesh Build Lifecycle', label='public-docs-frontend-meshing-build-lifecycle', status='implemented', doc_kind='reference', scope='the canonical documentation page for Mesh Build Lifecycle', children=(), navigation_maxdepth=1),
    PageSpec(path='frontend/meshing/quality-and-reports.md', title='Mesh Quality and Reports', label='public-docs-frontend-meshing-quality-and-reports', status='implemented', doc_kind='reference', scope='the canonical documentation page for Mesh Quality and Reports', children=(), navigation_maxdepth=1),
    PageSpec(path='frontend/meshing/python-round-trip.md', title='UI and Python Round-Trip', label='public-docs-frontend-meshing-python-round-trip', status='implemented', doc_kind='reference', scope='the canonical documentation page for UI and Python Round-Trip', children=(), navigation_maxdepth=1),
    PageSpec(path='frontend/visualization/index.md', title='Frontend Visualization', label='public-docs-frontend-visualization-root', status='partial', doc_kind='reference', scope='the canonical documentation page for Frontend Visualization', children=(), navigation_maxdepth=1),
    PageSpec(path='frontend/state-and-commands/index.md', title='Frontend State and Commands', label='public-docs-frontend-state-and-commands-root', status='partial', doc_kind='reference', scope='the canonical documentation page for Frontend State and Commands', children=(), navigation_maxdepth=1),
    PageSpec(path='backend/index.md', title='Backend', label='public-docs-backend-root', status='implemented', doc_kind='reference', scope='the canonical documentation page for Backend', children=('architecture/index.md', 'physics/index.md', 'numerical-methods/meshing/index.md', 'numerical-methods/index.md'), navigation_maxdepth=4),
    PageSpec(path='numerical-methods/meshing/fdm/index.md', title='FDM Meshing', label='public-docs-numerical-methods-meshing-fdm-root', status='implemented', doc_kind='reference', scope='the canonical documentation page for FDM Meshing', children=('numerical-methods/meshing/fdm-grids.md', 'numerical-methods/meshing/fdm/boundary-correction.md', 'numerical-methods/meshing/fdm/multi-magnet-grids.md', 'numerical-methods/meshing/fdm/periodic-grids.md'), navigation_maxdepth=2),
    PageSpec(path='numerical-methods/meshing/fdm/boundary-correction.md', title='FDM Boundary Correction', label='public-docs-numerical-methods-meshing-fdm-boundary-correction', status='partial', doc_kind='reference', scope='the canonical documentation page for FDM Boundary Correction', children=(), navigation_maxdepth=1),
    PageSpec(path='numerical-methods/meshing/fdm/multi-magnet-grids.md', title='FDM Multi-Magnet Grids', label='public-docs-numerical-methods-meshing-fdm-multi-magnet-grids', status='partial', doc_kind='reference', scope='the canonical documentation page for FDM Multi-Magnet Grids', children=(), navigation_maxdepth=1),
    PageSpec(path='numerical-methods/meshing/fdm/periodic-grids.md', title='FDM Periodic Grids', label='public-docs-numerical-methods-meshing-fdm-periodic-grids', status='partial', doc_kind='reference', scope='the canonical documentation page for FDM Periodic Grids', children=(), navigation_maxdepth=1),
    PageSpec(path='numerical-methods/meshing/fem/index.md', title='FEM Meshing', label='public-docs-numerical-methods-meshing-fem-root', status='implemented', doc_kind='reference', scope='the canonical documentation page for FEM Meshing', children=('numerical-methods/meshing/fem/shared-domain/index.md', 'numerical-methods/meshing/fem/ferromagnet/index.md', 'numerical-methods/meshing/fem/airbox/index.md'), navigation_maxdepth=3),
    PageSpec(path='numerical-methods/meshing/fem/shared-domain/index.md', title='FEM Shared Domain', label='public-docs-numerical-methods-meshing-fem-shared-domain-root', status='implemented', doc_kind='reference', scope='the canonical documentation page for FEM Shared Domain', children=('numerical-methods/meshing/fem-shared-domain.md', 'numerical-methods/meshing/fem/shared-domain/assembly-and-conformity.md', 'numerical-methods/meshing/fem/shared-domain/selectors-and-attributes.md', 'numerical-methods/meshing/fem/shared-domain/build-modes-and-fallbacks.md'), navigation_maxdepth=2),
    PageSpec(path='numerical-methods/meshing/fem/shared-domain/assembly-and-conformity.md', title='FEM Assembly and Conformity', label='public-docs-numerical-methods-meshing-fem-shared-domain-assembly-and-conformity', status='partial', doc_kind='reference', scope='the canonical documentation page for FEM Assembly and Conformity', children=(), navigation_maxdepth=1),
    PageSpec(path='numerical-methods/meshing/fem/shared-domain/selectors-and-attributes.md', title='FEM Selectors and Attributes', label='public-docs-numerical-methods-meshing-fem-shared-domain-selectors-and-attributes', status='partial', doc_kind='reference', scope='the canonical documentation page for FEM Selectors and Attributes', children=(), navigation_maxdepth=1),
    PageSpec(path='numerical-methods/meshing/fem/shared-domain/build-modes-and-fallbacks.md', title='FEM Build Modes and Fallbacks', label='public-docs-numerical-methods-meshing-fem-shared-domain-build-modes-and-fallbacks', status='partial', doc_kind='reference', scope='the canonical documentation page for FEM Build Modes and Fallbacks', children=(), navigation_maxdepth=1),
    PageSpec(path='numerical-methods/meshing/fem/ferromagnet/index.md', title='FEM Ferromagnet Meshing', label='public-docs-numerical-methods-meshing-fem-ferromagnet-root', status='implemented', doc_kind='reference', scope='the canonical documentation page for FEM Ferromagnet Meshing', children=('numerical-methods/meshing/fem/ferromagnet/free-tetrahedral.md', 'numerical-methods/meshing/fem/ferromagnet/thin-film-tetrahedral.md', 'numerical-methods/meshing/swept-meshes.md', 'numerical-methods/meshing/fem/ferromagnet/swept-prism.md', 'numerical-methods/meshing/fem/ferromagnet/swept-hex.md', 'numerical-methods/meshing/fem/ferromagnet/boundary-layers.md', 'numerical-methods/meshing/fem/ferromagnet/imported-mesh.md', 'numerical-methods/meshing/fem/ferromagnet/mixed-elements.md'), navigation_maxdepth=2),
    PageSpec(path='numerical-methods/meshing/fem/ferromagnet/free-tetrahedral.md', title='Free Tetrahedral Mesh', label='public-docs-numerical-methods-meshing-fem-ferromagnet-free-tetrahedral', status='implemented', doc_kind='reference', scope='the canonical documentation page for Free Tetrahedral Mesh', children=(), navigation_maxdepth=1),
    PageSpec(path='numerical-methods/meshing/fem/ferromagnet/thin-film-tetrahedral.md', title='Thin-Film Tetrahedral Mesh', label='public-docs-numerical-methods-meshing-fem-ferromagnet-thin-film-tetrahedral', status='partial', doc_kind='reference', scope='the canonical documentation page for Thin-Film Tetrahedral Mesh', children=(), navigation_maxdepth=1),
    PageSpec(path='numerical-methods/meshing/fem/ferromagnet/swept-prism.md', title='Swept Prism Mesh', label='public-docs-numerical-methods-meshing-fem-ferromagnet-swept-prism', status='implemented', doc_kind='reference', scope='the canonical documentation page for Swept Prism Mesh', children=(), navigation_maxdepth=1),
    PageSpec(path='numerical-methods/meshing/fem/ferromagnet/swept-hex.md', title='Swept Hex Mesh', label='public-docs-numerical-methods-meshing-fem-ferromagnet-swept-hex', status='partial', doc_kind='reference', scope='the canonical documentation page for Swept Hex Mesh', children=(), navigation_maxdepth=1),
    PageSpec(path='numerical-methods/meshing/fem/ferromagnet/boundary-layers.md', title='FEM Boundary Layers', label='public-docs-numerical-methods-meshing-fem-ferromagnet-boundary-layers', status='partial', doc_kind='reference', scope='the canonical documentation page for FEM Boundary Layers', children=(), navigation_maxdepth=1),
    PageSpec(path='numerical-methods/meshing/fem/ferromagnet/imported-mesh.md', title='Imported FEM Mesh', label='public-docs-numerical-methods-meshing-fem-ferromagnet-imported-mesh', status='partial', doc_kind='reference', scope='the canonical documentation page for Imported FEM Mesh', children=(), navigation_maxdepth=1),
    PageSpec(path='numerical-methods/meshing/fem/ferromagnet/mixed-elements.md', title='Mixed Prism–Pyramid–Tetrahedron Mesh', label='public-docs-numerical-methods-meshing-fem-ferromagnet-mixed-elements', status='implemented', doc_kind='reference', scope='the canonical documentation page for Mixed Prism–Pyramid–Tetrahedron Mesh', children=(), navigation_maxdepth=1),
    PageSpec(path='numerical-methods/meshing/fem/airbox/index.md', title='FEM Airbox Meshing', label='public-docs-numerical-methods-meshing-fem-airbox-root', status='implemented', doc_kind='reference', scope='the canonical documentation page for FEM Airbox Meshing', children=('numerical-methods/meshing/airbox.md', 'numerical-methods/meshing/fem/airbox/geometry.md', 'numerical-methods/meshing/fem/airbox/grading.md', 'numerical-methods/meshing/fem/airbox/boundary-closure.md', 'numerical-methods/meshing/fem/airbox/periodic-airbox.md'), navigation_maxdepth=2),
    PageSpec(path='numerical-methods/meshing/fem/airbox/geometry.md', title='Airbox Geometry', label='public-docs-numerical-methods-meshing-fem-airbox-geometry', status='partial', doc_kind='reference', scope='the canonical documentation page for Airbox Geometry', children=(), navigation_maxdepth=1),
    PageSpec(path='numerical-methods/meshing/fem/airbox/grading.md', title='Airbox Grading', label='public-docs-numerical-methods-meshing-fem-airbox-grading', status='partial', doc_kind='reference', scope='the canonical documentation page for Airbox Grading', children=(), navigation_maxdepth=1),
    PageSpec(path='numerical-methods/meshing/fem/airbox/boundary-closure.md', title='Airbox Boundary Closure', label='public-docs-numerical-methods-meshing-fem-airbox-boundary-closure', status='partial', doc_kind='reference', scope='the canonical documentation page for Airbox Boundary Closure', children=(), navigation_maxdepth=1),
    PageSpec(path='numerical-methods/meshing/fem/airbox/periodic-airbox.md', title='Periodic and Floquet Airbox', label='public-docs-numerical-methods-meshing-fem-airbox-periodic-airbox', status='partial', doc_kind='reference', scope='the canonical documentation page for Periodic and Floquet Airbox', children=(), navigation_maxdepth=1),
    PageSpec(path='python-api/meshing/index.md', title='Meshing', label='public-docs-python-api-meshing-root', status='implemented', doc_kind='reference', scope='the canonical documentation page for Meshing', children=('python-api/meshing/fdm/index.md', 'python-api/meshing/fem/index.md'), navigation_maxdepth=4),
    PageSpec(path='python-api/meshing/fdm/index.md', title='FDM Meshing API', label='public-docs-python-api-meshing-fdm-root', status='implemented', doc_kind='reference', scope='the canonical documentation page for FDM Meshing API', children=('python-api/discretization/fdm.md', 'python-api/meshing/fdm/grid.md', 'python-api/meshing/fdm/per-magnet-grids.md', 'python-api/meshing/fdm/boundary-correction.md', 'python-api/discretization/fdm-multilayer-convolution.md'), navigation_maxdepth=2),
    PageSpec(path='python-api/meshing/fdm/grid.md', title='FDM Default Grid', label='public-docs-python-api-meshing-fdm-grid', status='implemented', doc_kind='reference', scope='the canonical documentation page for FDM Default Grid', children=(), navigation_maxdepth=1),
    PageSpec(path='python-api/meshing/fdm/per-magnet-grids.md', title='FDM Per-Magnet Grids', label='public-docs-python-api-meshing-fdm-per-magnet-grids', status='partial', doc_kind='reference', scope='the canonical documentation page for FDM Per-Magnet Grids', children=(), navigation_maxdepth=1),
    PageSpec(path='python-api/meshing/fdm/boundary-correction.md', title='FDM Boundary-Correction API', label='public-docs-python-api-meshing-fdm-boundary-correction', status='partial', doc_kind='reference', scope='the canonical documentation page for FDM Boundary-Correction API', children=(), navigation_maxdepth=1),
    PageSpec(path='python-api/meshing/fem/index.md', title='FEM Meshing API', label='public-docs-python-api-meshing-fem-root', status='implemented', doc_kind='reference', scope='the canonical documentation page for FEM Meshing API', children=('python-api/discretization/fem.md', 'python-api/meshing/fem/study-defaults.md', 'python-api/discretization/mesh-controls.md', 'python-api/meshing/fem/ferromagnet/index.md', 'python-api/meshing/fem/airbox/index.md', 'python-api/meshing/fem/regions.md', 'python-api/meshing/fem/build-and-quality.md'), navigation_maxdepth=3),
    PageSpec(path='python-api/meshing/fem/study-defaults.md', title='FEM Study Defaults', label='public-docs-python-api-meshing-fem-study-defaults', status='implemented', doc_kind='reference', scope='the canonical documentation page for FEM Study Defaults', children=(), navigation_maxdepth=1),
    PageSpec(path='python-api/meshing/fem/ferromagnet/index.md', title='FEM Ferromagnet Mesh API', label='public-docs-python-api-meshing-fem-ferromagnet-root', status='implemented', doc_kind='reference', scope='the canonical documentation page for FEM Ferromagnet Mesh API', children=('python-api/discretization/per-object-meshing.md', 'python-api/meshing/fem/ferromagnet/free-tetrahedral.md', 'python-api/meshing/fem/ferromagnet/thin-film-tetrahedral.md', 'python-api/meshing/fem/ferromagnet/swept-prism.md', 'python-api/meshing/fem/ferromagnet/swept-hex.md', 'python-api/meshing/fem/ferromagnet/boundary-layers.md', 'python-api/meshing/fem/ferromagnet/imported-mesh.md'), navigation_maxdepth=2),
    PageSpec(path='python-api/meshing/fem/ferromagnet/free-tetrahedral.md', title='Free-Tetrahedral API', label='public-docs-python-api-meshing-fem-ferromagnet-free-tetrahedral', status='implemented', doc_kind='reference', scope='the canonical documentation page for Free-Tetrahedral API', children=(), navigation_maxdepth=1),
    PageSpec(path='python-api/meshing/fem/ferromagnet/thin-film-tetrahedral.md', title='Thin-Film Tetrahedral API', label='public-docs-python-api-meshing-fem-ferromagnet-thin-film-tetrahedral', status='partial', doc_kind='reference', scope='the canonical documentation page for Thin-Film Tetrahedral API', children=(), navigation_maxdepth=1),
    PageSpec(path='python-api/meshing/fem/ferromagnet/swept-prism.md', title='Swept-Prism API', label='public-docs-python-api-meshing-fem-ferromagnet-swept-prism', status='implemented', doc_kind='reference', scope='the canonical documentation page for Swept-Prism API', children=(), navigation_maxdepth=1),
    PageSpec(path='python-api/meshing/fem/ferromagnet/swept-hex.md', title='Swept-Hex API', label='public-docs-python-api-meshing-fem-ferromagnet-swept-hex', status='partial', doc_kind='reference', scope='the canonical documentation page for Swept-Hex API', children=(), navigation_maxdepth=1),
    PageSpec(path='python-api/meshing/fem/ferromagnet/boundary-layers.md', title='Boundary-Layer API', label='public-docs-python-api-meshing-fem-ferromagnet-boundary-layers', status='partial', doc_kind='reference', scope='the canonical documentation page for Boundary-Layer API', children=(), navigation_maxdepth=1),
    PageSpec(path='python-api/meshing/fem/ferromagnet/imported-mesh.md', title='Imported-Mesh API', label='public-docs-python-api-meshing-fem-ferromagnet-imported-mesh', status='partial', doc_kind='reference', scope='the canonical documentation page for Imported-Mesh API', children=(), navigation_maxdepth=1),
    PageSpec(path='python-api/meshing/fem/airbox/index.md', title='FEM Airbox Mesh API', label='public-docs-python-api-meshing-fem-airbox-root', status='implemented', doc_kind='reference', scope='the canonical documentation page for FEM Airbox Mesh API', children=('python-api/meshing/fem/airbox/geometry.md', 'python-api/meshing/fem/airbox/grading.md', 'python-api/meshing/fem/airbox/build.md'), navigation_maxdepth=2),
    PageSpec(path='python-api/meshing/fem/airbox/geometry.md', title='Airbox Geometry API', label='public-docs-python-api-meshing-fem-airbox-geometry', status='implemented', doc_kind='reference', scope='the canonical documentation page for Airbox Geometry API', children=(), navigation_maxdepth=1),
    PageSpec(path='python-api/meshing/fem/airbox/grading.md', title='Airbox Grading API', label='public-docs-python-api-meshing-fem-airbox-grading', status='implemented', doc_kind='reference', scope='the canonical documentation page for Airbox Grading API', children=(), navigation_maxdepth=1),
    PageSpec(path='python-api/meshing/fem/airbox/build.md', title='Airbox Build API', label='public-docs-python-api-meshing-fem-airbox-build', status='implemented', doc_kind='reference', scope='the canonical documentation page for Airbox Build API', children=(), navigation_maxdepth=1),
    PageSpec(path='python-api/meshing/fem/regions.md', title='FEM Region Mesh API', label='public-docs-python-api-meshing-fem-regions', status='partial', doc_kind='reference', scope='the canonical documentation page for FEM Region Mesh API', children=(), navigation_maxdepth=1),
    PageSpec(path='python-api/meshing/fem/build-and-quality.md', title='FEM Build and Quality API', label='public-docs-python-api-meshing-fem-build-and-quality', status='implemented', doc_kind='reference', scope='the canonical documentation page for FEM Build and Quality API', children=(), navigation_maxdepth=1),
)

_MESHING_SPECS = {
    spec.path: spec
    for spec in (
        PageSpec(path='numerical-methods/meshing/index.md', title='Meshing and spatial discretization', label='public-docs-numerical-methods-meshing-index', status='implemented', doc_kind='reference', scope='meshing and spatial discretization', children=('numerical-methods/meshing/fdm/index.md', 'numerical-methods/meshing/fdm-grids.md', 'numerical-methods/meshing/fem/index.md', 'numerical-methods/meshing/airbox.md', 'numerical-methods/meshing/fem-shared-domain.md', 'numerical-methods/meshing/refinement.md', 'numerical-methods/meshing/swept-meshes.md'), navigation_maxdepth=2),
        PageSpec(path='numerical-methods/meshing/fdm-grids.md', title='FDM Cartesian grids', label='public-docs-numerical-methods-meshing-fdm-grids', status='implemented', doc_kind='reference', scope='FDM Cartesian grids', children=(), navigation_maxdepth=1),
        PageSpec(path='numerical-methods/meshing/fem-shared-domain.md', title='FEM shared-domain meshing', label='public-docs-numerical-methods-meshing-fem-shared-domain', status='implemented', doc_kind='reference', scope='FEM shared-domain meshing', children=(), navigation_maxdepth=1),
        PageSpec(path='numerical-methods/meshing/airbox.md', title='FEM airbox meshing', label='public-docs-numerical-methods-meshing-airbox', status='implemented', doc_kind='reference', scope='FEM airbox meshing', children=(), navigation_maxdepth=1),
        PageSpec(path='numerical-methods/meshing/swept-meshes.md', title='Swept and layered FEM meshes', label='public-docs-numerical-methods-meshing-swept-meshes', status='partial', doc_kind='reference', scope='swept and layered FEM meshes', children=(), navigation_maxdepth=1),
        PageSpec(path='numerical-methods/meshing/refinement.md', title='Mesh sizing, local refinement and convergence', label='public-docs-numerical-methods-meshing-refinement', status='implemented', doc_kind='reference', scope='mesh sizing, local refinement and convergence', children=(), navigation_maxdepth=1),
        PageSpec(path='numerical-methods/meshing/fdm/index.md', title='Finite-difference meshing', label='public-docs-numerical-methods-meshing-fdm-index', status='implemented', doc_kind='reference', scope='finite-difference meshing', children=('numerical-methods/meshing/fdm-grids.md', 'numerical-methods/meshing/fdm/boundary-correction.md', 'numerical-methods/meshing/fdm/multi-magnet-grids.md', 'numerical-methods/meshing/fdm/periodic-grids.md'), navigation_maxdepth=2),
        PageSpec(path='numerical-methods/meshing/fdm/boundary-correction.md', title='FDM boundary correction', label='public-docs-numerical-methods-meshing-fdm-boundary-correction', status='implemented', doc_kind='reference', scope='FDM boundary correction', children=(), navigation_maxdepth=1),
        PageSpec(path='numerical-methods/meshing/fdm/multi-magnet-grids.md', title='FDM multi-magnet grids', label='public-docs-numerical-methods-meshing-fdm-multi-magnet-grids', status='implemented', doc_kind='reference', scope='FDM multi-magnet grids', children=(), navigation_maxdepth=1),
        PageSpec(path='numerical-methods/meshing/fdm/periodic-grids.md', title='FDM periodic grids', label='public-docs-numerical-methods-meshing-fdm-periodic-grids', status='partial', doc_kind='reference', scope='FDM periodic grids', children=(), navigation_maxdepth=1),
        PageSpec(path='numerical-methods/meshing/fem/index.md', title='Finite-element meshing', label='public-docs-numerical-methods-meshing-fem-index', status='implemented', doc_kind='reference', scope='finite-element meshing', children=('numerical-methods/meshing/fem/shared-domain/index.md', 'numerical-methods/meshing/fem/ferromagnet/index.md', 'numerical-methods/meshing/fem/airbox/index.md'), navigation_maxdepth=2),
        PageSpec(path='numerical-methods/meshing/fem/shared-domain/index.md', title='FEM shared-domain assembly', label='public-docs-numerical-methods-meshing-fem-shared-domain-index', status='implemented', doc_kind='reference', scope='FEM shared-domain assembly', children=('numerical-methods/meshing/fem/shared-domain/assembly-and-conformity.md', 'numerical-methods/meshing/fem/shared-domain/build-modes-and-fallbacks.md', 'numerical-methods/meshing/fem/shared-domain/selectors-and-attributes.md'), navigation_maxdepth=2),
        PageSpec(path='numerical-methods/meshing/fem/shared-domain/assembly-and-conformity.md', title='Shared-domain assembly and conformity', label='public-docs-numerical-methods-meshing-fem-shared-domain-assembly-and-conformity', status='implemented', doc_kind='reference', scope='shared-domain assembly and conformity', children=(), navigation_maxdepth=1),
        PageSpec(path='numerical-methods/meshing/fem/shared-domain/selectors-and-attributes.md', title='Mesh selectors, markers and semantic attributes', label='public-docs-numerical-methods-meshing-fem-shared-domain-selectors-and-attributes', status='implemented', doc_kind='reference', scope='mesh selectors, markers and semantic attributes', children=(), navigation_maxdepth=1),
        PageSpec(path='numerical-methods/meshing/fem/shared-domain/build-modes-and-fallbacks.md', title='Shared-domain build modes and fallback semantics', label='public-docs-numerical-methods-meshing-fem-shared-domain-build-modes-and-fallbacks', status='implemented', doc_kind='reference', scope='shared-domain build modes and fallback semantics', children=(), navigation_maxdepth=1),
        PageSpec(path='numerical-methods/meshing/fem/ferromagnet/index.md', title='FEM ferromagnet meshes', label='public-docs-numerical-methods-meshing-fem-ferromagnet-index', status='implemented', doc_kind='reference', scope='FEM ferromagnet meshes', children=('numerical-methods/meshing/fem/ferromagnet/free-tetrahedral.md', 'numerical-methods/meshing/fem/ferromagnet/thin-film-tetrahedral.md', 'numerical-methods/meshing/fem/ferromagnet/swept-prism.md', 'numerical-methods/meshing/fem/ferromagnet/swept-hex.md', 'numerical-methods/meshing/fem/ferromagnet/boundary-layers.md', 'numerical-methods/meshing/fem/ferromagnet/imported-mesh.md', 'numerical-methods/meshing/fem/ferromagnet/mixed-elements.md'), navigation_maxdepth=2),
        PageSpec(path='numerical-methods/meshing/fem/ferromagnet/free-tetrahedral.md', title='Free tetrahedral ferromagnet mesh', label='public-docs-numerical-methods-meshing-fem-ferromagnet-free-tetrahedral', status='implemented', doc_kind='reference', scope='free tetrahedral ferromagnet mesh', children=(), navigation_maxdepth=1),
        PageSpec(path='numerical-methods/meshing/fem/ferromagnet/thin-film-tetrahedral.md', title='Thin-film tetrahedral ferromagnet mesh', label='public-docs-numerical-methods-meshing-fem-ferromagnet-thin-film-tetrahedral', status='implemented', doc_kind='reference', scope='thin-film tetrahedral ferromagnet mesh', children=(), navigation_maxdepth=1),
        PageSpec(path='numerical-methods/meshing/fem/ferromagnet/swept-prism.md', title='Swept-prism ferromagnet mesh', label='public-docs-numerical-methods-meshing-fem-ferromagnet-swept-prism', status='partial', doc_kind='reference', scope='swept-prism ferromagnet mesh', children=(), navigation_maxdepth=1),
        PageSpec(path='numerical-methods/meshing/fem/ferromagnet/swept-hex.md', title='Swept-hexahedral ferromagnet mesh', label='public-docs-numerical-methods-meshing-fem-ferromagnet-swept-hex', status='unsupported', doc_kind='reference', scope='swept-hexahedral ferromagnet mesh', children=(), navigation_maxdepth=1),
        PageSpec(path='numerical-methods/meshing/fem/ferromagnet/boundary-layers.md', title='FEM boundary-layer mesh controls', label='public-docs-numerical-methods-meshing-fem-ferromagnet-boundary-layers', status='partial', doc_kind='reference', scope='FEM boundary-layer mesh controls', children=(), navigation_maxdepth=1),
        PageSpec(path='numerical-methods/meshing/fem/ferromagnet/imported-mesh.md', title='Imported geometry and FEM mesh assets', label='public-docs-numerical-methods-meshing-fem-ferromagnet-imported-mesh', status='partial', doc_kind='reference', scope='imported geometry and FEM mesh assets', children=(), navigation_maxdepth=1),
        PageSpec(path='numerical-methods/meshing/fem/ferromagnet/mixed-elements.md', title='Mixed-element FEM meshes', label='public-docs-numerical-methods-meshing-fem-ferromagnet-mixed-elements', status='partial', doc_kind='reference', scope='mixed-element FEM meshes', children=(), navigation_maxdepth=1),
        PageSpec(path='numerical-methods/meshing/fem/airbox/index.md', title='FEM airbox mesh', label='public-docs-numerical-methods-meshing-fem-airbox-index', status='implemented', doc_kind='reference', scope='FEM airbox mesh', children=('numerical-methods/meshing/fem/airbox/geometry.md', 'numerical-methods/meshing/fem/airbox/grading.md', 'numerical-methods/meshing/fem/airbox/boundary-closure.md', 'numerical-methods/meshing/fem/airbox/periodic-airbox.md'), navigation_maxdepth=2),
        PageSpec(path='numerical-methods/meshing/fem/airbox/geometry.md', title='Airbox geometry and enclosure', label='public-docs-numerical-methods-meshing-fem-airbox-geometry', status='implemented', doc_kind='reference', scope='airbox geometry and enclosure', children=(), navigation_maxdepth=1),
        PageSpec(path='numerical-methods/meshing/fem/airbox/grading.md', title='Airbox mesh grading', label='public-docs-numerical-methods-meshing-fem-airbox-grading', status='implemented', doc_kind='reference', scope='airbox mesh grading', children=(), navigation_maxdepth=1),
        PageSpec(path='numerical-methods/meshing/fem/airbox/boundary-closure.md', title='Airbox outer-boundary closure', label='public-docs-numerical-methods-meshing-fem-airbox-boundary-closure', status='implemented', doc_kind='reference', scope='airbox outer-boundary closure', children=(), navigation_maxdepth=1),
        PageSpec(path='numerical-methods/meshing/fem/airbox/periodic-airbox.md', title='Periodic FEM airbox mesh', label='public-docs-numerical-methods-meshing-fem-airbox-periodic-airbox', status='partial', doc_kind='reference', scope='periodic FEM airbox mesh', children=(), navigation_maxdepth=1),
    )
}

PAGE_SPECS = tuple(
    _MESHING_SPECS.get(spec.path, spec)
    for spec in _BASE_SPECS + _NEW_SPECS
)

# Existing compatibility URLs remain valid. New canonical branches are additive,
# so no source URL is retired by this restructuring.
LEGACY_REDIRECTS = dict(legacy.LEGACY_REDIRECTS)
LEGACY_INTERACTION_REDIRECTS = legacy.LEGACY_INTERACTION_REDIRECTS
LEGACY_NAVIGATION_REDIRECTS = legacy.LEGACY_NAVIGATION_REDIRECTS
